### ISSUE TITLE
Configure LIFX tab recommendations to improve UX. 

### ISSUE THREAD

**Issue by BBQSean** [isaacrlevin/PresenceLight#10]
1. Rename "Lifx Api Key" to "LIFX Token"
2. Add a "Get Token" Link to Configure LIFX tab that goes to https://cloud.lifx.com/settings 
3. Global - update Lifx to LIFX to reflect brand

**Comment by isaacrlevin** [comment]
open a PR?

**Comment by isaacrlevin** [comment]
Fixed with [this commit](https://github.com/isaacrlevin/PresenceLight/commit/7a0ccbedad0e362096851c27c36e9f1b18f171ff)
