### ISSUE TITLE
Lifx Not Working

### ISSUE THREAD

**Issue by cconrado** [isaacrlevin/PresenceLight#110]
Unable to connect to Lifx and getting error. Also it cleared my previous settings (api key) and it's unable to save settings.
![image](https://user-images.githubusercontent.com/9168464/88065039-b17fcc00-cb31-11ea-9711-af61ed87bb57.png)

**Comment by isaacrlevin** [comment]
What version?

**Comment by patrimal** [comment]
I have the same problem in 3.0.5.0

**Comment by cconrado** [comment]
@isaacrlevin oh sorry its the windows store version 3.0.5.0

**Comment by isaacrlevin** [comment]
@cconrado when you click get token, what happens?

**Comment by cconrado** [comment]
@isaacrlevin it takes me to the lifx site to login. So I can get the api token. That worked fine.

**Comment by isaacrlevin** [comment]
Ok, but entering in a token manually does not work? Just trying to confirm the issue. As a heads up, all settings will get cleared when updating to 3.0.5 due to a breaking settings change

**Comment by cconrado** [comment]
@isaacrlevin wait was that the expected action, click the link and it auto populates the key? If so that didn't happen. It just showed get personal token which I did then copied pasted the key. Then clicked saved and it displayed that it did. Then I closed & opened the app but everything was clear again.

So the two issues were that I couldn't save the api key and check "Connect to Lifx Light"

**Comment by isaacrlevin** [comment]
Is there a way you can record it? Using ScreenToGif?

**Comment by cconrado** [comment]
@isaacrlevin what's your email so i can send the gif? It shows my api key so didn't want to post it.

**Comment by cconrado** [comment]
@isaacrlevin btw uninstall and reinstall worked fixed it for me. So I don't think it's an issue anymore.
