### ISSUE TITLE
Running on Linux in docker container

### ISSUE THREAD

**Issue by Xyolyp** [isaacrlevin/PresenceLight#112]
I don't have a Windows server running but a Linux one running docker. 

It would be amazing if there was a docker image provided on any registry. 

Currently I'm running the tool on my windows desktop but it would be more ideal to have it running on my server because I wouldn't have to worry about the tokens expiring while the tool isn't running because the Linux server is running 24/7 and could renew the tokens whenever it's required. 

I've seen you are already working towards something like this but I wanted to explain my wish for a read to run container image for use on a Linux server.

**Comment by isaacrlevin** [comment]
Have you looked at this?
https://github.com/isaacrlevin/PresenceLight/blob/main/src/PresenceLight.Worker/Dockerfile

**Comment by Xyolyp** [comment]
I haven't done it yet, but I will take a look at it on the weekend. Deployment via a well known container image source would simplify the deployment even further, wouldn't it?

**Comment by isaacrlevin** [comment]
The container is hosted on Microsoft Container Registry. 
https://azure.microsoft.com/en-us/services/container-registry/

**Comment by isaacrlevin** [comment]
@Xyolyp any questions here?

**Comment by Xyolyp** [comment]
@isaacrlevin I have no further questions regarding docker right now. Thank you for bringing this up and guiding me in the right direction.
