### ISSUE TITLE
Presence API Issue?

### ISSUE THREAD

**Issue by Xyolyp** [isaacrlevin/PresenceLight#114]
I was in a call for a couple of minutes and sometimes the status shown in the PresenceLight application switches from Busy/InACall to Busy/InAMeeting although I'm still in the call. I'm logged in to teams and have it open on a desktop and a laptop and have it installed and runnning in the background on an iPhone.

**To Reproduce**
1. Create an appointment in the future in your teams calendar
2. log in with two clients (I don't know if this is requiered)
3. Join the appointment
4. Wait until the issue occurs (it's sporadic, maybe once every ten to twenty calls)

**Expected behavior**
I would expect the status to remain Busy/InACall as long as I'm in a call or appointment-call on any device.

I'm not sure if this is an issue in this application or in the api but I assume that you have a bit more leverage with the api mantaining team as you are working at microsoft.

**Comment by isaacrlevin** [comment]
This is not a PresenceLight issue, @jthake-msft how is the best way to report this?
