### ISSUE TITLE
Custom API Question

### ISSUE THREAD

**Issue by Spanishu** [isaacrlevin/PresenceLight#116]
Hi,
sorry was quite busy in the last couple of weeks. I have looked at the custom API part, however, I am really not a coder so I am a bit lost here. The solution I would like to interface with is https://github.com/dresden-elektronik/deconz-rest-plugin/wiki
If you feel like it and have some time, would be cool to get some guidance.
I have been able to make some progress. This is what my api URL looks like right now
192.168.1.95/api/59575AFCF3/lights/5/state/"on": true
Probably there is a syntax error, but I am not a coder and I have used Postman to try this out, where it does work. Any hint
Thanks a lot in advance

**Comment by isaacrlevin** [comment]
Do you get an error?

**Comment by Spanishu** [comment]
Yes, I do, is there a log file from which I can get the error. I see an error but i am not able to capture it. URI and 404

**Comment by isaacrlevin** [comment]
you can try to open Fiddler before you make the request, if you give me that I may be able to help. 404 usually means you have the uri wrong

**Comment by Spanishu** [comment]
Took another look on fiddler. I guess one of the problems is that I need to use PUT instead of post. However there will be more to it. Some guidacnce would be great!

**Comment by isaacrlevin** [comment]
Not sure what guidance I can give you. Can you provide the RAW Fiddler request for your postman call AND PresenceLight.

on a side note, the screenshot you took above should be removed

**Comment by Spanishu** [comment]
Hi
PUT http://192.168.1.95/api/07A3909DDC/lights/5/state HTTP/1.1
Host: 192.168.1.95
Content-Length: 13

{ "on": true}
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 41
ETag: "0feaf979c15c19f9be949d8ec6eb805d"

[{"success":{"/lights/5/state/on":true}}]

hope this is what you are looking for

**Comment by isaacrlevin** [comment]
This is one of them, if you can label them with '>' for instance

> This is a quote

and

> this is another quote

**Comment by Spanishu** [comment]
I got this on the side of the composer
`HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 41
ETag: "0feaf979c15c19f9be949d8ec6eb805d"

[{"success":{"/lights/5/state/on":true}}]`

**Comment by isaacrlevin** [comment]
Which one is which?

**Comment by Spanishu** [comment]
Updated the previous comment: with the full entries

**Comment by isaacrlevin** [comment]
Which one fails?

**Comment by Spanishu** [comment]
Of these none: I do not get a capture from the presencelight app.

**Comment by isaacrlevin** [comment]
Make sure PresenceLight is completely closed before opening Fiddler. Once Fiddler is running, open PresenceLight, should be able to see it than

**Comment by Spanishu** [comment]
Thanks for the patience:
Request
`POST http://192.168.1.95/api/07A3909DDC/lights/5/state/%22on%22:%20true HTTP/1.1
Host: 192.168.1.95
Content-Length: 0`

Response
`HTTP/1.1 404 Not Found
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 150

[{"error":{"address":"/lights/5/state/\"on\": true","description":"method, POST, not available for resource, /lights/5/state/\"on\": true","type":4}}]`

**Comment by isaacrlevin** [comment]
Well it seems that uri is not structured properly, it is not sending an Http body. That and the affect PUT is not wired up in PresenceLight at all is a challenge. I can't build this sadly as I have no HW to test. If you wanted to take a swipe at it I could help.

**Comment by Spanishu** [comment]
I am afraid I am not I have never coded. However I will see that I can put my Zigbee Outlet onto the Philipps HUE Bridge. That might be far easier. Question, Can I control with the app simple on / off scenario ? For me it is enough that I can simple turn on a light when I am "busy". a bit like "On-Air" Thanks for the help and the patience

**Comment by Xyolyp** [comment]
@Spanishu it is far easier to use the custom api implementation with some sort of sortware smart home solution like node red, home assistant, iobroker, fhem or whatever you like. node red and iobroker offer a graphical interface to configure the logic engine which would control your deconz conbee.

**Comment by Spanishu** [comment]
I have decided to take a different route.
I have linked my Ikea Tradfri Plug to the Philipps Hue Bridge (direct integration)
Works until here. What I would be missing is a "probably" simple feature:
- My status is Red = Light goes on
- My status is Green = Light goes off

I have not been able to see this feature, If there is a workaround please let me know... Almost there! Thanks a lot for the help!

**Comment by isaacrlevin** [comment]
This would be custom light controls per status, which was asked in #77. Closing this
