### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Xyolyp** [isaacrlevin/PresenceLight#119]
The application closes after being frozen for a couple of seconds just after startup.

**To Reproduce**
I don't know how you can reproduce this issue but I have attached some crash dumps.
How can I get this up and running again? I have tried deleting the data via windows app settings and also uninstalling and reinstalling the application.

[CrashDumps.zip](https://github.com/isaacrlevin/PresenceLight/files/5042872/CrashDumps.zip)

**Comment by isaacrlevin** [comment]
What version of app are you on?

**Comment by Xyolyp** [comment]
Sorry for the late answer. I was on the latest Microsoft Store Version that was available. A couple of days later the issue just stopped and now the application works as intended again. Maybe there are some valuable insights in the dumps anyways.

**Comment by isaacrlevin** [comment]
I looked into logs, didn't see anything. If you can easily repro, go ahead and reopen
