### ISSUE TITLE
Feature: Overriding Presence Status from Info Bar

### ISSUE THREAD

**Issue by Shrekmachine** [isaacrlevin/PresenceLight#12]
Would be awesome to control a timeboxed presence per right mouse click on the app icon

**Comment by isaacrlevin** [comment]
Not following, can you give an example?

**Comment by Shrekmachine** [comment]
like in Teams for example
![image](https://user-images.githubusercontent.com/8019511/80523779-e6471180-898e-11ea-8e0d-e13626653e86.png)

**Comment by isaacrlevin** [comment]
Ah ok, there is no Set Presence available for the Graph Api

**Comment by Shrekmachine** [comment]
ok, thanks
