### ISSUE TITLE
Is it still necessary to Enable Side Loading?

### ISSUE THREAD

**Issue by MatthewMcD** [isaacrlevin/PresenceLight#120]
Trying to get this running and it doesn't complete the Authentication, but it does control my Hue light. I installed from the MS Store. Do I still need to enable side loading?

**Comment by isaacrlevin** [comment]
Nope, side loading is only needed when you don't have a cert. All the available downloads use a signed version

**Comment by MatthewMcD** [comment]
Great. If I get a sec I'll try and update the doc.

**Comment by Xyolyp** [comment]
@MatthewMcD try completely closing the application after logging in (right click the tray icon and select exit) and restarting it right away. That worked for me.

**Comment by isaacrlevin** [comment]
I updated the doc here, thanks!
