### ISSUE TITLE
Login required with every start

### ISSUE THREAD

**Issue by Shrekmachine** [isaacrlevin/PresenceLight#13]
Hi Isaac, is this "by design"?
I need to authenticate every time I start PresenceLight.
Cheers
Fred

**Comment by isaacrlevin** [comment]
It is, I would rather not store your data in any capacity. There are ways I could cache the token so you don't need to login, and I may add in the future

**Comment by Shrekmachine** [comment]
Azure Key Vault?

**Comment by isaacrlevin** [comment]
Ehhh I really don't to get in the habit of storing stuff for users. I can look into local caching
