### ISSUE TITLE
Suggestion: SmartThings Integration

### ISSUE THREAD

**Issue by BhaskinsWR** [isaacrlevin/PresenceLight#131]
Add SmartThings OAuth, surface available Devices and Scenes in PL, add workflow to map individual presence states to Scenes. User can then create 'Video Meeting' scene to adjust lighting, blinds, door locks, and call scene on presence = Activity InAMeeting / InACall etc. Also gets PL out of the 'please integrate with vendor X' game. SmartThings community is pretty committed - good group to engage, might recruit some extra devs for this project - also plenty of porting between ST and Hubitat projects.

Apologies is this is the wrong channel for suggestions (newb), and great job on this project. Fwiw ST integration would qualify as 'premium' app imo, no-brainer purchase if price is reasonable.

**Comment by isaacrlevin** [comment]
I don't have SmartThings, so it would be hard to build, welcome any PRs here though!
