### ISSUE TITLE
Setting color = reset login

### ISSUE THREAD

**Issue by Shrekmachine** [isaacrlevin/PresenceLight#14]
Whenever I set the color manually I'm kicked out the account and change get lost.

**Comment by isaacrlevin** [comment]
That is by design, it is a not great UI experience but since I am polling graph when logged in, I sign the user out when I change color manually or sync to theme. One alternative would be to have a but on the login screen that says "Sync Presence"

**Comment by Shrekmachine** [comment]
at least I would point this out in the guide :)

**Comment by isaacrlevin** [comment]
readme updated
