### ISSUE TITLE
Hue Bridge IP Address: Manual input

### ISSUE THREAD

**Issue by BoBiene** [isaacrlevin/PresenceLight#147]
Since the update I'm not able to configure the Hue Bridge IP Address.
I have a custom port and in previous version i could just input <IP>:<PORT> in the Text-Field.

But now the Text-Field is disabled and i can only use the "Find Bridge" button - but this is not finding my bridge.

**Comment by isaacrlevin** [comment]
Which version do you have?

**Comment by BoBiene** [comment]
Hi, 
the latest from the store. 
Received the update yesterday.
Regards,
Bo

**Comment by BoBiene** [comment]
The Version i use is 3.0.43.0

**Comment by isaacrlevin** [comment]
@BoBiene have you tried the latest nightly?

**Comment by BoBiene** [comment]
@isaacrlevin yes this is working now :) 👍
Thank you for that.

Btw. it is not possible to work with a dns-entry i have to enter a IP-Address.

**Comment by isaacrlevin** [comment]
@BoBiene that is a Phillips Hue limitation. Calling the api to get a bridge only returns ip address. Closing this now
