### ISSUE TITLE
Feature: Default setting after PresenceLight is switched off

### ISSUE THREAD

**Issue by Shrekmachine** [isaacrlevin/PresenceLight#15]
A color, a dimming and an on/off switch.
Currently, If I stop PL, the hue band switches to bright white
Dimming would be good as the light could be little less bright while PL is on.
Maybe I've overseen a setting?

**Comment by isaacrlevin** [comment]
I reset the light to white by design. When you say dim, are you referring to changing the brightness for the light always??

**Comment by Shrekmachine** [comment]
Yep, when I stop presencelight on my 2m Hue band, all of a sudden the room in front of my home office looks like a runway at the airport. 
a fixed dimming would be good

**Comment by isaacrlevin** [comment]
Latest nightly has brightness added

**Comment by Shrekmachine** [comment]
Awesome!
