### ISSUE TITLE
Custom API - State in JSON body

### ISSUE THREAD

**Issue by jaburges** [isaacrlevin/PresenceLight#150]
**Is your feature request related to a problem? Please describe.**
Firstly, thanks - this is super helpful! 
I'm looking at various ways to utilize this with Home Assistant.
Right now I can expose the REST API directly to send different commands to a bulb for example.

**Describe the solution you'd like**
However, I think an interesting option would be to use Node-Red.
Set up a REST target and have PresenceLight send the command to http://Node_red_ip:1880/LightPresence
What would be super helpful in this instance is for the availability to be send as the body of the payload
```
{ "availability": "busy" }
```

**Describe alternatives you've considered**
Alternatively an MQTT protocol option would also be cool, so someone could subscribe to the MQTT topic `LightPresence/availability` 
and the result would be 
`busy`

for example. This opens up a wealth of possibilities beyond just lights too :) 

**Additional context**
Happy to provide more info if needed. Thanks again for building this!

**Comment by isaacrlevin** [comment]
Seems interesting, I don't have Home Assistant so it would be hard to test. Happy to accept a PR

**Comment by jaburges** [comment]
Hey - thanks for the note - you probably wouldnt want me poking around, i'm not smart enough to be useful :(
the main ask is to send the state in the JSON body to a single POST/GET request (rather than various individual POST requests - 1 per state)

**Comment by onpaj** [comment]
Hey, I'm also looking for a HA integration. I think most reusable way is to allow passing custom headers and payload to this custom API (for POST and GET). I'll take a look at it

**Comment by isaacrlevin** [comment]
Closing this as it seems @Xyolyp is working on #159 for this

**Comment by fierland** [comment]
Quick question: @jaburges can you post an example of your URI's im trying but getting only 404's

**Comment by FreekBos** [comment]
> Seems interesting, I don't have Home Assistant so it would be hard to test. Happy to accept a PR

I think this would be SUPER useful. Is there or can we have some traction on this? Is MQTT supported and how?
