### ISSUE TITLE
WorkingHours

### ISSUE THREAD

**Issue by ross-p-smith** [isaacrlevin/presencelight#151]
When running the application as the executable and using CustomAPI endpoints, it does not respect Working Hours.

I would like the service to only call my automations in the work hours that I define in the configuration. If it is outside the working hours, I would like to call my "Off" automation.

**Comment by isaacrlevin** [comment]
When you say "Run as executable", what do you mean?

**Comment by ross-p-smith** [comment]
Sorry - I meant, I am running the Presence.Worker.exe not the Store App

**Comment by isaacrlevin** [comment]
Ah ok, the Blazor app has not been setup to use Working hours. I see you opened a PR
