### ISSUE TITLE
Additional Custom API Activities

### ISSUE THREAD

**Issue by mattstein111** [isaacrlevin/PresenceLight#154]
There are more Activities in Teams now that are not listed in the presence state list on the Configure Custom API tab. 

Seemingly missing:
- InAConferenceCall
- Inactive
- OffWork
- OutOfOffice
- PresenceUnknown
- UrgentInterruptionsOnly

List of current states on [https://docs.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta](url)

If these could be added for the next release, that would be great.

**Comment by mattstein111** [comment]
If this should be a feature request, apologies in advance.

**Comment by isaacrlevin** [comment]
Two different things here Availability vs Activity. PresenceLight at this time does not change lights based on Activities. I would welcome a PR to add such functionality, but would need to ensure that users had the option of using one or the other and can control light color accordingly.

**Comment by mattstein111** [comment]
Ah, got it. Thanks.
