### ISSUE TITLE
Presence app process unexpectedly terminates

### ISSUE THREAD

**Issue by sborg-ms** [isaacrlevin/presencelight#157]
At a infrequent period the Presence app process is now longer running!

**To Reproduce**
hard to define - just start it and leave running for a day or two or more... then it just terminates unannounced and unexpectedly. 

**Expected behaviour**
To remain running all the time and only exit /end when asked to or rebooted.
 

## Further details
- OS: [e.g. Win10 20H2]
- PresenceLight App Type (Desktop)
- PresenceLight Build (Nightly)
- PresenceLight Version (3.0.53.0)
 
thoughts/ideas on how to help troubleshoot.

**Comment by isaacrlevin** [comment]
I have wired up additional diagnostic logging, please let me know next time this occurs

**Comment by isaacrlevin** [comment]
@sborg-ms is this still happening?

**Comment by isaacrlevin** [comment]
hey @sborg-ms can you give the latest nightly a shot and let me know if you still have this issue?

**Comment by sborg-ms** [comment]
still having the random terminations and still cannot see a new nightly build when trying to install...

**Comment by isaacrlevin** [comment]
Closing as this is now resolved
