### ISSUE TITLE
Standalone Desktop Version

### ISSUE THREAD

**Issue by ajobbins** [isaacrlevin/PresenceLight#160]
Is it possible to get a standalone version to run on W10 that doesn't require the App Store or admin privileges to install? My org blocks essentially store apps and sideloading, and I'd need to get the app security reviewed to install separately as no one has local admin for security reasons. Ideally an exe that I could run manually would be ideal. Is this possible?

**Comment by isaacrlevin** [comment]
It would be yes, you would just need to configure the settings storage to be in a particular place

**Comment by isaacrlevin** [comment]
Going forward, GitHub releases and Choco installs will be Standalone (non-store) apps

https://github.com/isaacrlevin/PresenceLight/releases/tag/v3.5.30
