### ISSUE TITLE
LIFX integration working only on initial setup

### ISSUE THREAD

**Issue by cakeinmilk** [isaacrlevin/PresenceLight#166]
**Describe the bug**
I've tried this with a couple of versions on a couple of different machines, ensuring it's uninstalled properly

I've also removed PresenceLight from authorised apps on cloud.lifx.com each time. I get a nice bright green light initially, but nothing can change that. When I uninstall the application, the light turns off (I can turn it back on via the Lifx iOS app).

**To Reproduce**
Install PresenceLight
Sign in
Configure LIFX
Get token
Get Lights
Save default colour scheme
Configured Light changes to current Teams status

**Expected behavior**
Subsequent status changes are reflected in the Sign in tab, but not via actual lights

## Further details
- OS: Win10
- PresenceLight App Type (Desktop, Blazor): Desktop/ 
- PresenceLight Build (Nightly, Store, etc): Store and Nightly
- PresenceLight Version (The # in About) v3.0.43 and 3.0.53
- Did you clear settings.json?  Yes

**Comment by isaacrlevin** [comment]
There should be a fix in the current nightly v3.5.5

**Comment by isaacrlevin** [comment]
Closed in 3.5.15

**Comment by nutterguy** [comment]
Tested on 3.5.15.0 and all seems to be working really well now. Thanks @isaacrlevin! :)
