### ISSUE TITLE
Not finding Yeelight

### ISSUE THREAD

**Issue by lbbeurmann** [isaacrlevin/presencelight#168]
Hello, I have the app set up on a Windows 10 machine using the Microsoft Store app.  The app is seeing my Teams presence just fine, but I am not able to find my light when I configure a Yeelight and click the "Find Yeelights" button.  When I click the button, the brightness slider disappears briefly, but lower pulldown stays blank. 

I can see and manage my light just fine in the Yeelight and Mi Home apps on my iOS devices.  Lan control is turned on.  My Yeelight is a Mi Bedside Lamp and the model is yeelink.light.bslamp1

**Comment by isaacrlevin** [comment]
Can you provide a video of this? I don't have Yeelight so I cannot test well

**Comment by isaacrlevin** [comment]
@lbbeurmann still having issues?

**Comment by isaacrlevin** [comment]
Closing as no user response
