### ISSUE TITLE
Setting custom Hue colors breaks ability to set color or exit app (kill process required)

### ISSUE THREAD

**Issue by jdshkolnik** [isaacrlevin/PresenceLight#170]
**Describe the bug**
Setting custom Hue colors breaks PresenceLight. I'm able to repair by either uninstalling/reinstalling or killing from task manager and changing the json colors back to default. Here are some values that break it (seem to be any though):

```
"Hue": {
      "HueApiKey": "blahBlah",
      "SelectedHueLightId": "1",
      "HueBrightness": 100,
      "HueIpAddress": "blah.blah.blah.blah",
      "IsPhillipsHueEnabled": true,
      "AvailableStatus": {
        "Disabled": false,
        "Colour": "#FFAEEA73"
      },
      "BusyStatus": {
        "Disabled": false,
        "Colour": "#FFE87C61"
      },
```

**To Reproduce**
1. I sign in without issue.
2. I find and register the Hue bridge. Everything works as expected.
3. I modify the available and busy colors and now it's fubar. Attempting to set any color only sets the brightness (from the Set Light Colors tab). Furthermore, attempting to exit the app doesn't work and it has to be killed from task manager.

1. Right-click on PresenceLight in notification tray.
2. Choose Exit.
3. Nothing happens.

**Expected behavior**
I'd expect it to use the colors as set and allow the app to exit when attempted.

**Screenshots**
![image](https://user-images.githubusercontent.com/2047520/97932235-823a4700-1d3d-11eb-9ab1-31a762777531.png)

## Further details
- OS: Windows 10 (1909)
- PresenceLight App Type: Desktop
- PresenceLight Build: Store
- PresenceLight Version: 3.0.43.0
- ASP.NET Core version

**Comment by jdshkolnik** [comment]
I just realized the problem is that PresenceLight is setting invalid color values.

**Comment by BartRoels** [comment]
Correct, if you change the value to the default value in the Settings.json and restart the app, everything is working fine again. I also noticed that when you set a custom color in the settings.json without a running app and then start the app the particular status will not been picked up by the application.

**Comment by pierlag** [comment]
Yes, fix this issue for me also. Thanks

**Comment by isaacrlevin** [comment]
There is a fix in the latest nightly. v3.5.5

**Comment by jdshkolnik** [comment]
> There is a fix in the latest nightly. v3.5.5

When does this propagate to the Microsoft Store?

**Comment by isaacrlevin** [comment]
Was hoping to get people to test the nightly before I do that, can you test the nightly?

**Comment by isaacrlevin** [comment]
The newest version in the store has been updated. @jdshkolnik can you test?

**Comment by jdshkolnik** [comment]
The version I'm seeing from the store is 3.5.15.0 and it still has the same problem with the prepended "FF"..

**Comment by isaacrlevin** [comment]
Are your lights updating? The reason I ask is because I strip out the leading FF driving in the service after the save, the reason for doing this is to ensure that the Color Picker still work

**Comment by jdshkolnik** [comment]
The light updates. As a minor observation, I noticed in settings.json that the colour values began as 6-digits until I make a change and then they're saved with the preceding "FF".

**Comment by isaacrlevin** [comment]
I will look to clean up the color saving. Closing this issue
