### ISSUE TITLE
Loosing API settings on reboot 

### ISSUE THREAD

**Issue by SHHA24** [isaacrlevin/PresenceLight#171]
On some but not all reboots of PC, the Presence Light app runs but the API integration is not active, when you then tick box select the API none of the POST commands are stored or remembered. 

Version 3.0.43.0 

thanks great product works really well, just this one small bug.

**Comment by isaacrlevin** [comment]
Please try the latest nightly and let me know if this issue still persists.

**Comment by isaacrlevin** [comment]
Closed in 3.5.15
