### ISSUE TITLE
Improvement: Clustering on the UI

### ISSUE THREAD

**Issue by Shrekmachine** [isaacrlevin/PresenceLight#18]
Hi Isaac, only last night I understood some of the behaviors and how this is organized in the UI.
I have to choose either (!) 
- Set Graph presence
- Set Color OR
- Sync Windows Theme 
and PL will immediately use the setting, including logging out in case Graph Presence is deactivated.
 Assuming my understanding is correct, wouldn't it be a nice move forward to structure the UI in the same way as the logic?
![image](https://user-images.githubusercontent.com/8019511/81142037-b9869180-8f6e-11ea-81bf-7c1b582c0278.png)

**Comment by isaacrlevin** [comment]
This seems reasonable. Fancy doing a PR?

**Comment by Shrekmachine** [comment]
my pleasure... What is PR? :D

**Comment by isaacrlevin** [comment]
I was able to "fix" this in a way. You will stay logged into graph the entire time, but can change the source of color with no issue
