### ISSUE TITLE
Upgrade Fails - PresenceLight 3.0.47 - chocolatey /  Windows store  etc

### ISSUE THREAD

**Issue by stephenjg24-git** [isaacrlevin/PresenceLight#188]
I have PresenceLight currently installed, I have version 2.0.68.0

sysinfo:
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.17134 N/A Build 17134

WinVer:
Version 1803 (OS Build 17134.1845)

0) When in CMD window for chocolatey   I am as Admin, I am local admin

1) I get errors when I try to Upgrade - "No signature was present in the subject"
I have tried Nightly Build, chocolatey, Windows Store all fail

2) tried to Uninstall, the uninstall button if disabled

How can I uninstall?

How can I upgrade?

For Developers is set to Sideload.   Tried Developer mode same Issue.

Please advise

Stephen 

[presencelight.txt](https://github.com/isaacrlevin/PresenceLight/files/5637460/presencelight.txt)

**Comment by isaacrlevin** [comment]
You should not need sideload at all, all the apps are signed. My recommendation is to uninstall ALL versions of the app on your machine, restart, and install the nightly. Please report back what your experience is after that.

**Comment by stephenjg24-git** [comment]
Hello,   When I try to uninstall, the uninstall button is disabled.  

I think I originally installed via chocolatey.

I can see files in the \windowsapps\. Folder structure however this are locked and I can not delete 

Do you have any manual uninstall methods. 

Stephen

**Comment by isaacrlevin** [comment]
does this work?
choco uninstall presencelight

**Comment by stephenjg24-git** [comment]
No this did not work, 

C:\WINDOWS\system32>choco uninstall presencelight
Chocolatey v0.10.11
Uninstalling the following packages:
presencelight
presencelight is not installed. Cannot uninstall a non-existent package.

Chocolatey uninstalled 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - presencelight - presencelight is not installed. Cannot uninstall a non-existent package.

If a package uninstall is failing and/or you've already uninstalled the
 software outside of Chocolatey, you can attempt to run the command
 with `-n` to skip running a chocolateyUninstall script, additionally
 adding `--skip-autouninstaller` to skip an attempt to automatically
 remove system-installed software. This will only remove the packaging
 files and not things like software installed to Programs and Features.

If a package is failing because it is a dependency of another package
 or packages, then you may first need to consider if it needs removed
 as it is typically installed as a dependency for a reason. If you
 decide that you still want to remove it, head into
 `$env:ChocolateyInstall\lib` and find the package folder you want
 removed. Then delete the folder for the package. This option should
 only be used as a last resort.

**Comment by isaacrlevin** [comment]
Going forward, GitHub releases and Choco installs will be Standalone (non-store) apps, so you shouldn't have such an issue uninstalling. 

https://github.com/isaacrlevin/PresenceLight/releases/tag/v3.5.30

**Comment by stephenjg24-git** [comment]
Ok

Any idea on the manual removal steps?

**Comment by isaacrlevin** [comment]
Are you able to install a version from the MSFT store?

**Comment by stephenjg24-git** [comment]
All installs fail. And the option to uninstall is not enabled.    It looks like it was installed via the store but I can not delete.

**Comment by isaacrlevin** [comment]
Maybe try something like this

https://www.windowsboy.com/2020/02/18/force-uninstall-apps-windows-10-powershell/#:~:text=%202%20Ways%20to%20Force%20Uninstall%20Apps%20from,Uninstall%20Apps%20from%20Windows%2010%20PowerShell%3F%20More%20

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by stephenjg24-git** [comment]
used this to remove the app from windowsapp folder 

Get-AppxPackage -AllUsers | ft
Get-AppxPackage -AllUsers | where-object {$_.name -like "*NameOfApp*"} | Remove-AppxPackage
 

found: 37828IsaacLevin.197278F15330A

Get-AppxPackage -AllUsers | where-object {$_.name -like "*37828IsaacLevin.197278F15330A*"} | Remove-AppxPackage

**Comment by stephenjg24-git** [comment]
this is a closed issue
