### ISSUE TITLE
Include support for auth using personal Microsoft accounts

### ISSUE THREAD

**Issue by rwttm001** [isaacrlevin/PresenceLight#193]
**Is your feature request related to a problem? Please describe.**
As I don't have a works/student Microsoft account, I'm unable to authenticate into either the nightly WPF install or the latest Blazor worker build, although I can still navigate to the other tabs of the WPF app without auth.

**Describe the solution you'd like**
The ability to authenticate into either app using my personal Microsoft account. Any mention of Teams Presence could be either disabled (maybe with an explanation as to why unavailable) or removed from the UI completely.

**Describe alternatives you've considered**
NA - I'm unable to obtain neither a work or student Microsoft account.

**Additional context**
I believe that this is a property in the Azure AAD App Registration Manifest being used, which needs to be set to AzureADandPersonalMicrosoftAccount:

![image](https://user-images.githubusercontent.com/2026197/101486300-57eb3300-3954-11eb-8c4b-c9ddfe161a5c.png)

[https://docs.microsoft.com/en-us/azure/active-directory/develop/supported-accounts-validation](url)

Running the Blazor App locally against an App Registered in my personal Azure Subscription configured to use personal accounts, I'm able to authenticate successfully, although the App then logs expected exceptions when attempting to poll the MS Graph for my Presence data.

**Comment by isaacrlevin** [comment]
So you want to use Presencelight for non-Teams things?

**Comment by rwttm001** [comment]
Yes, the functionality for non-Teams light settings by selecting a custom color or desktop on the WPF client is already there so a shame to exclude personal users,

**Comment by isaacrlevin** [comment]
Maybe take a look at OktowakeLight

https://github.com/isaacrlevin/OkToWakeLight

**Comment by isaacrlevin** [comment]
Closing this as there is another solution more pointed at MSAs instead of AAD accounts. Happy to chat more on it though. Maybe in [Discussions](https://github.com/isaacrlevin/PresenceLight/discussions)
