### ISSUE TITLE
updating build number per update

### ISSUE THREAD

**Issue by Shrekmachine** [isaacrlevin/PresenceLight#20]
it easier to see if there is a new build. Currently version 1.0.157.0 is available. Information marks 1.0.136.0. And on the wish list is a small version history :)
![image](https://user-images.githubusercontent.com/8019511/81898552-29bd9480-95b9-11ea-9842-95d8af09bbe3.png)

**Comment by isaacrlevin** [comment]
I think this is a caching issue on the GH side, I will look into this. What do you mean by version history?

**Comment by Shrekmachine** [comment]
change log

**Comment by isaacrlevin** [comment]
What if you could DL and see via GitHub releases?

**Comment by isaacrlevin** [comment]
like this? https://github.com/isaacrlevin/PresenceLight/releases

**Comment by Shrekmachine** [comment]
almost ;) Would be enough in such case to write something like
- updated libraries

**Comment by isaacrlevin** [comment]
well that would involve me adding better commit messages, soooooooo

**Comment by isaacrlevin** [comment]
Closing as release notes are included in GitHub Release
