### ISSUE TITLE
Add Homebridge support

### ISSUE THREAD

**Issue by Spanishu** [isaacrlevin/PresenceLight#203]
I have come across this project on the weekend 
https://github.com/estruyf/homebridge-presence-switch-msgraph/

It is very interesting to me since it allows integration into Homebridge / Homekit which would make it more versatile for me and probably others. 

I have tried to run it but I cannot get the Graph Access authorized? 
--> Any suggestion on how to get this authorized?

Would it be possible to merge the two projects?

**Comment by isaacrlevin** [comment]
If @estruyf wanted to add this functionality to PresenceLight I would love a PR! Closing this as I do not have HomeKit to test

**Comment by estruyf** [comment]
Also HomeKit wouldn't make sense here as it needs to run as a plugin. 

@isaacrlevin could you tell @Spanishu what is the process inside Microsoft to get an Azure AD App approved? As I expect you did the same thing for your app. That is the only solution.
