### ISSUE TITLE
3.5.30  worker version not listening on port 5001

### ISSUE THREAD

**Issue by rscott1010101** [isaacrlevin/PresenceLight#207]
Fresh download of the worker application. Unzip and run, but it only starts the http listener on port 5000 and not the https listener, so it's not possible to sign in to O365.

Startup messages:-
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[63]
      User profile is available. Using 'C:\Users\Richard\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\Richard\Downloads\3.5.30_Windows_x64_x86

**Comment by isaacrlevin** [comment]
Hmmm odd, this is what I get if I download latest. Do you have the dotnet core dev cert installed?

https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&tabs=visual-studio#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos

![image](https://user-images.githubusercontent.com/8878502/102822802-963e1480-438e-11eb-9496-8b77f0a475cb.png)

**Comment by rscott1010101** [comment]
That was it - didn't have the dev cert installed.. Thanks! Might be worth mentioning that in the documentation - I'd assumed I could just download and run this version.. Or maybe have it throw an error that it can't find the dev cert? At the moment, it doesn't do anything other than not listen on 5001.

Are there any plans to update this version to have the custom API options? I've used those on the other version to successfully integrate with HomeAssistant.

Or to add MQTT support, which would also be incredibly useful.

**Comment by isaacrlevin** [comment]
My goal is to add feature parity between the 2. I will also add a note in the README.

**Comment by isaacrlevin** [comment]
Closing and creating feature request #213
