### ISSUE TITLE
hashes do not match - PresenceLight v3.5.30.0 - Chocolatey install

### ISSUE THREAD

**Issue by stephenjg24-git** [isaacrlevin/presencelight#211]
Here is the info from Powershell

Chocolatey v0.10.11
Installing the following packages:
presencelight
By installing you accept licenses for the packages.
PresenceLight v3.5.30.0 already installed. Forcing reinstall of version '3.5.30.0'.
 Please use upgrade if you meant to upgrade to a new version.
Progress: Downloading PresenceLight 3.5.30.0... 100%

PresenceLight v3.5.30.0 (forced) [Approved]
presencelight package files install completed. Performing other installation steps.
The package PresenceLight wants to run 'ChocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[N]o/[P]rint): y

Downloading presencelight
  from 'https://github.com/isaacrlevin/PresenceLight/releases/download/v3.5.30/PresenceLight.3.5.30-x86.zip'
Progress: 100% - Completed download of C:\Users\stephen.lichtenberg\AppData\Local\Temp\chocolatey\PresenceLight\3.5.30.0\PresenceLight.3.5.30-x86.zip (82.78 MB).
Download of PresenceLight.3.5.30-x86.zip (82.78 MB) completed.
Error - hashes do not match. Actual value was '488C49BB26E211139BEF74C57C7A7D053407077D63707176A8F9BA18B5325C11BBD62DC4A21627B6D7B6A5C662D7EC9656A2F8858A43A4AE3961D20CF9C40A7B'.
ERROR: Checksum for 'C:\Users\stephen.lichtenberg\AppData\Local\Temp\chocolatey\PresenceLight\3.5.30.0\PresenceLight.3.5.30-x86.zip' did not meet '287B1298DF426434B429A40DCDAA78769CFCE25B0B2F180F41A70E5A33ED40A7' for checksum type 'SHA512'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of presencelight was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\PresenceLight\tools\ChocolateyInstall.ps1'.
 See log for details.

**Comment by isaacrlevin** [comment]
You still having this issue with the latest version from chocolatey

**Comment by isaacrlevin** [comment]
This is now resolved. There is still an issue with Start Menu and Start at Login, but PL will now install
