### ISSUE TITLE
Invalid reply URL for hard-coded Application ID

### ISSUE THREAD

**Issue by Eegras** [isaacrlevin/presencelight#217]
**Describe the bug**
Invalid reply URL when trying to log in through the Docker container.  The "Running In Docker" steps do mention needing to map a data directory for a SQLite database but they don't note what that directory in the container is.  Is it `/app`?

**To Reproduce**
As far as I can tell, it's as simple as "create a Docker container following https://github.com/isaacrlevin/PresenceLight/blob/main/worker-README.md#running-in-docker.  Whatever Reply URLs are configured in the default Application likely won't match my domain.

**Expected behavior**
I would expect to be able to log in and start configuring PresenceLight.

**Screenshots**
![image](https://user-images.githubusercontent.com/6810622/104061421-2b7a3f00-51be-11eb-8716-0da9b33a706a.png)

## Further details
- PresenceLight App Type (Desktop, Blazor) Docker
- PresenceLight Build (Nightly, Store, etc) Latest
- PresenceLight Version (The # in About) Unable to access application.
- Did you clear settings.json? (C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json  It's a Docker container, settings clear on startup.
- ASP.NET Core version Development

**Comment by isaacrlevin** [comment]
That is a known issue with AAD, you can't have wildcard or dynamic redirect uris. The IP for my instance is 192.168.86.27. There is no db in this project so I'm guessing I copy pasted the wrong thing.

I will update the Readme to account for those 2 points. If you use the above IP it will work.

**Comment by Eegras** [comment]
Would it be possible to expose a directory that I can mount to persistent storage in which I can configure AAD using my own application registration?

**Comment by Eegras** [comment]
After plugging away at this, you can totally map specific files from persistent storage to a location inside the Docker container, and this works well enough.

In Unraid it looks like this:
![image](https://user-images.githubusercontent.com/6810622/104777758-db612680-5741-11eb-8bee-8276df8e1eb6.png)

This allowed me to define my own Application in Azure to use my own reply URL.

**Comment by isaacrlevin** [comment]
Cool, I was going to mention you can mount the appsettings.json directly. Glad you got it working :)
