### ISSUE TITLE
Option to run WPF App at startup is not visible

### ISSUE THREAD

**Issue by DavidDeSloovere** [isaacrlevin/presencelight#230]
See #219 

WPF version, both winget install and store install.

**Comment by isaacrlevin** [comment]
Can you validate this works on the nightly version?

https://presencelight.blob.core.windows.net/nightly/index.html

**Comment by DavidDeSloovere** [comment]
I still don't see the option.
Reinstalling is no fun for me, because my Philips Hue hub is downstairs and my office is 2 floors up 🙂

Adding my Windows Version at the bottom.

![image](https://user-images.githubusercontent.com/352626/105457057-80ba5400-5c86-11eb-9e7c-e00c6d81c051.png)


![image](https://user-images.githubusercontent.com/352626/105457137-992a6e80-5c86-11eb-9d36-3b447bf512eb.png)

**Comment by isaacrlevin** [comment]
My bad, get the latest nightly. 3.7.19

**Comment by DavidDeSloovere** [comment]
🎉
Thanks @isaacrlevin 

I'll let you close this issue, maybe you want to wait until it's in the main release (not nightly).

![image](https://user-images.githubusercontent.com/352626/105624861-2e636980-5e25-11eb-8175-f082336ea664.png)

**Comment by isaacrlevin** [comment]
Party on!
