### ISSUE TITLE
Allow interval for Webhook refreshes

### ISSUE THREAD

**Issue by ThisBytes5** [isaacrlevin/presencelight#236]
I just installed the app this week and so far going great, but I'm seeing an issue where the app shows a status change but due to a reboot or hick up on my network the web hook isn't showing the correct status.

I would like to see an update where I can set a X number of minutes and have it call the web hook with the current status on the interval regardless if it has changed or not.

I just looked through the settings.json, but didn't see anything that fit this request.

**Comment by isaacrlevin** [comment]
Not 100% following, are you saying that the polling isn't working right? Also would be super helpful if you filled out the bug or feature request form :)

**Comment by ThisBytes5** [comment]
Sorry, I read the form and removed it then typed up what I thought would satisfy the questions, and doing so while in a meeting probably wasn't a good idea either:

**Is your feature request related to a problem? Please describe.**
Yes, issue appears that at times my Home Assistant isn't available, and as such isn't getting the updates from PresenceLight. Not sure if PL only calls the webhooks once, but if so and HA isn't available then I miss the status change.

**Describe the solution you'd like**
Allow for a timer that the web hooks would be called with what ever the current status is, regardless if the status has changed. Maybe a setting on the webhooks tab to allow me to enter the number of minutes to force a refresh to the web hooks.

**Describe alternatives you've considered**
Currently none

**Additional context**
I have an issue with one of the pieces of smart hardware tied to my HA, as such I have to reboot it at times, and I think the last couple times my status in Teams changed HA was rebooting, so assuming that PL wasn't able to successfully send the status update.

Hope this clears things up. I'm very interested in checking out the code this weekend. So far it seems to work great if not for my hardware issue.

**Comment by isaacrlevin** [comment]
Are you running the Desktop App? What version?

**Comment by ThisBytes5** [comment]
yes, and version 3.5.15.0

**Comment by isaacrlevin** [comment]
Can you try the latest nightly install?

https://presencelight.blob.core.windows.net/nightly/index.html

**Comment by ThisBytes5** [comment]
Installed, I copied the settings.json from the stable version over to the
nightly, didn't want to have to re-enter all the custom API's again. Let me
know if I shouldn't have done that and I'll delete it and restart the
nightly app

**Comment by isaacrlevin** [comment]
What I would do is just enable one endpoint to test. Basically how PresenceLight works is that if you configured your light (in your case Custom Api), PresenceLight polls Graph to get your presence than hits your light. It polls based on this setting. You can poll between 1-5 seconds. I am thinking of making this a larger range for folks who don't need a constant sync. Unless PL crashes, it will keep looping here, so if you keep it running, it should work. If that is not your experience (what it seems to me is that Homekit may queue the request?) We can look at a "Quick Sync option" which would be kindof an on-demand option for PL (so no polling). Does this make sense?

![image](https://user-images.githubusercontent.com/8878502/105520277-55883280-5c8f-11eb-9317-69517874dfca.png)

**Comment by ThisBytes5** [comment]
I think it makes sense, but I don't see the need to hit Teams/Graph again,
which means that maybe I still haven't done a great job of explaining my
issue.

So if you look below, PL has the correct value, but because I rebooted Home
Assistant it doesn't know the current value, so the issue isn't PL polling
Teams/Graph. It's more when Home Assistant flakes out and I have to wait
for a status change.
If there is any way you could just make it so PL calls the custom API with
the latest status updates every X number of seconds rather than hitting
Graph every X seconds that would solve my problem, and not draw attention
to me using PL on Teams as I'm not sure if policy allows me to do so :)

[image: image.png]

**Comment by isaacrlevin** [comment]
Not seeing the image, can you do this via GH not email?

**Comment by isaacrlevin** [comment]
The things go hand in hand. Take a look at the code here.

https://github.com/isaacrlevin/presencelight/blob/main/src/DesktopClient/PresenceLight/MainWindow.xaml.cs#L327

So every polling interval, it hits graph, THAN your light. Maybe I am not grasping, but in your case, I imagine your app gets presence, than sends to custom endoint, it fails (or doesn't set the light) and than does it again next interval.

Seems like you are asking to cache presence. If that is the case, it may be possible

**Comment by ThisBytes5** [comment]
The issue is if I reboot the app that is getting called via PL then the status starts as Available Available, and isn't updated with the current PL status. In fact it's not updated till my status actually changes, or I restart PL.

That said, it's easy enough for me to restart PL to force the update and most of the day Friday it worked fine and all day today it worked fine without needing to restart. As such let's pretend I didn't mention anything and let it go for now. If you can't I'll still assist, but at this point I'm happy.

**Comment by isaacrlevin** [comment]
Good to know you're happy. I am curious, it doesn't figure itself out after a couple of cycles?

**Comment by ThisBytes5** [comment]
Doesn't seem too, and like this morning I had been up and running in Teams for a good 20 mins before I restarted PL, that time PL didn't update. It had been running all weekend and seem to stay stuck in away away, but once I restarted it worked flawlessly the rest of the day. 

Finally got an automation set up to turn down Alexa music while I'm on a call, and turn it back up when I hang up.

**Comment by isaacrlevin** [comment]
Nice on the automation. I am currently working on extending the logging for PL so I can better triage issues like this. I am going to close this ticket, but there should be a new nightly version soon that we can triage better
