### ISSUE TITLE
Set Light Color based on Activity besides Availability on the Configure Philips Hue tab

### ISSUE THREAD

**Issue by BartRoels** [isaacrlevin/presencelight#238]
**Describe the solution you'd like**
Set Light Color based on Activity besides Availability on the Configure Philips Hue tab. 
Let give me a real-life example:
When I'm working in my Home Office my status is almost always busy, because my calendar is filled with things, I need to do besides having calls. During Busy time where I'm not in a call so it is okay to have the light on green as familiy members certainly can come in. If I'm really in a call,l then the light needs to be red as I don't want family coming into my room.

**Comment by isaacrlevin** [comment]
Thanks for the feature request. This is something folks have been asking for, I just need to figure out the UI

**Comment by isaacrlevin** [comment]
One quick work around is manually setting yourself to Do Not Disturb as that is another light color

**Comment by BartRoels** [comment]
Correct, I was aware of the workaround, only thing is that I need to do it manually and always forget to... and besides that others cannot communicate via IM

**Comment by fabian-we** [comment]
I would really appreciate this feature, too. I only want to have a red light, when I'm in a call.

**Comment by isaacrlevin** [comment]
FYI work will be done in this branch
https://github.com/isaacrlevin/presencelight/tree/custom-activity

**Comment by managerxxx** [comment]
Another up-vote from me. Thanks

**Comment by isaacrlevin** [comment]
Here is a tease of what the UI will look like in the Worker Project

![activity](https://user-images.githubusercontent.com/8878502/106817116-4314de00-662b-11eb-955c-f3cbae6dd980.gif)

**Comment by managerxxx** [comment]
Looking great  Thanks Isaac.

**Comment by isaacrlevin** [comment]
FYI PR is up if anyone wants to build from source

**Comment by isaacrlevin** [comment]
Latest nightly has completed activity work. I would like some folks to confirm, everything works before I deploy to the store

3.7.39

**Comment by BartRoels** [comment]
Will have a test later today...

**Comment by managerxxx** [comment]
Working so far for me - thanks Isaac. There's a small layout issue in full screen:

![image](https://user-images.githubusercontent.com/34621601/107847515-21161b00-6de4-11eb-8933-9c5ea5dd09be.png)

But so far so good. Thanks again,

**Comment by BartRoels** [comment]
> Working so far for me - thanks Isaac. There's a small layout issue in full screen:
> 
> ![image](https://user-images.githubusercontent.com/34621601/107847515-21161b00-6de4-11eb-8933-9c5ea5dd09be.png)
> 
> But so far so good. Thanks again,

Correct, functionality seems to work! Great Job! Concerning the layout issue, on smaller screens not all Activities are shown:
![image](https://user-images.githubusercontent.com/15818583/107847697-f3ce6a80-6ded-11eb-943d-4cc82387bfdc.png)

**Comment by BartRoels** [comment]
Not sure If I'm the only one, but I only can close the application by killing the running process.

**Comment by managerxxx** [comment]
Yes I thought it was just me but I experienced the same - ie quitting from system tray doesn't appear to work and you have to resort to killing the task.

**Comment by isaacrlevin** [comment]
can someone open a new issue for the tray issue?

**Comment by isaacrlevin** [comment]
I am also going to close this issue and create a new one where people can report issues with the specific feature

**Comment by isaacrlevin** [comment]
Closing this issue, go to #262 for feedback
