### ISSUE TITLE
Mute detection

### ISSUE THREAD

**Issue by ftepegit** [isaacrlevin/presencelight#244]
Hi,

this is more a feature request:

Is it possible to get the mute/unmute state whe in a call?

My idea: Light turns red when in a call and is red blinking when in a call and you are muted (often forget to unmute before starting to talk). Would be a very nice feature at least for me :)

Thanks for your work!

**Comment by isaacrlevin** [comment]
I am pretty sure that is a local setting in Teams that is not exposed via Graph. Closing as this is not possible
