### ISSUE TITLE
Docker Tag

### ISSUE THREAD

**Issue by andrewstech** [isaacrlevin/presencelight#246]
Hi not sure if this is deliberate but Your docker image for arm-64 is showing as linux/amd64 under the Arch. 

https://hub.docker.com/layers/isaaclevin/presencelight/debian-arm64/images/sha256-9a9a884ec3370348a6041a6a5e7589c7e2f91e86716287ab53a295ef190b2567?context=explore

**Comment by isaacrlevin** [comment]
This is now resolved
