### ISSUE TITLE
Lights status post working hours

### ISSUE THREAD

**Issue by sborg-ms** [isaacrlevin/presencelight#251]
new version 3.7.34.0

with settings per
![image](https://user-images.githubusercontent.com/67351620/107002491-71d3b580-67df-11eb-91bd-bfefee4f0b6b.png)

Did **NOT** turn off the light after the configured End of Working hour had passed.  Left it on at the last status colour.

Noted the last entry in the log file was
2021-02-05 17:45:25.1834|Info|PresenceLight Running in Teams Mode - MainWindow.xaml:InteractWithLights Line: 765 | 
2021-02-05 17:45:25.5698|Info|Setting LIFX Light id:d073d540948e to 009933 - LifxService:SetColor Line: 267 |

**Comment by isaacrlevin** [comment]
This should be fixed in latest Nightly

**Comment by sborg-ms** [comment]
ok somehow 3.7.36.0 has installed (could/should this be automatic?)  [as i also noticed app was not running this morning!)

Will test...

**Comment by sborg-ms** [comment]
seems fixed with 3.7.36.0 as today it turned off per work setttings!

**Comment by isaacrlevin** [comment]
closing per @sborg-ms
