### ISSUE TITLE
Lifx syncing stopped

### ISSUE THREAD

**Issue by sborg-ms** [isaacrlevin/presencelight#265]
since auto update to version 3.7.40.0 the  lifx configuration was removed and it will no longer connect with error 
![image](https://user-images.githubusercontent.com/67351620/107999131-d5a97a00-703a-11eb-9f68-0e9dc342536c.png)

logs around that time

{"Timestamp":"2021-02-16T09:50:14.7473338+11:00","Level":"Error","MessageTemplate":"**Error Getting LIFX Lights - MainWindow.Lifx:CheckLIFX_Click Line: 211","Exception":"System.InvalidCastException: Unable to cast object of type 'PresenceLight.Controls.LIFX'** to type 'System.Windows.Controls.Button'.\r\n   at PresenceLight.MainWindow.CheckLIFX_Click(Object sender, RoutedEventArgs e) in D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.Lifx.cs:line 179","Properties":{"SourceContext":"PresenceLight.MainWindow","LineNumber":211,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.Lifx.cs","MemberName":"CheckLIFX_Click","Application":"PresenceLight"}}
{"Timestamp":"2021-02-16T09:50:19.7457678+11:00","Level":"Information","MessageTemplate":"PresenceLight Running in Teams Mode - MainWindow.xaml:InteractWithLights Line: 821","Properties":{"SourceContext":"PresenceLight.MainWindow","LineNumber":821,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"InteractWithLights","Application":"PresenceLight"}}
{"Timestamp":"2021-02-16T09:50:20.2222122+11:00","Level":"Error","MessageTemplate":"Error Occurred - MainWindow.xaml:SetColor Line: 366","Exception":"System.ArgumentNullException: Selected LIFX Light Not Specified (Parameter 'lightId')\r\n   at PresenceLight.Core.LIFXService.SetColor(String availability, String activity, String lightId, String apiKey) in D:\\a\\presencelight\\presencelight\\src\\PresenceLight.Core\\Lights\\LifxServices\\LifxService.cs:line 302\r\n   at PresenceLight.Core.LifxServices.SetColorHandler.Handle(SetColorCommand command, CancellationToken cancellationToken) in D:\\a\\presencelight\\presencelight\\src\\PresenceLight.Core\\Lights\\LifxServices\\SetColor\\SetColorHandler.cs:line 26\r\n   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at PresenceLight.MainWindow.SetColor(String color, String activity) in D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs:line 370","Properties":{"SourceContext":"PresenceLight.MainWindow","LineNumber":366,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"SetColor","Application":"PresenceLight"}}

**Comment by sborg-ms** [comment]
With latest nightly I can now successfully retrieve the lifx lights and groups - but syncing still not working.

**Comment by isaacrlevin** [comment]
closing and moving work to #273
