### ISSUE TITLE
Custom Api Calling no longer working

### ISSUE THREAD

**Issue by isaacrlevin** [isaacrlevin/presencelight#270]
@gizmohd can you take a look at the Custom Api logic in the WPF version? It looks like when the user controls were added something happened, as now there is a InvalidOperationException when trying to update the label on the UI

**Comment by gizmohd** [comment]
Yes.. will look at that this evening.

**Comment by isaacrlevin** [comment]
great thanks!

**Comment by gizmohd** [comment]
Issue was a simple fix... 
![image](https://user-images.githubusercontent.com/1664013/108281235-5f496c80-714d-11eb-8530-959dc34f55d5.png)

**Comment by gizmohd** [comment]
So not sure why the error is occurring... It works fine for me...  But I did sync the AzureAd section names so that they matched on both Worker and Desktop configs to make things a bit more uniform.

**Comment by gizmohd** [comment]
Ok.. I think I saw what you were talking about.. 'Dropdown not populating'

But.. Ive got it working locally.. calling my Home Assistant Api's.. Working like a champ...

**Comment by isaacrlevin** [comment]
closing as fixed in latest nightly
