### ISSUE TITLE
Sync to Philips Hues Rooms

### ISSUE THREAD

**Issue by jdpkeeper** [isaacrlevin/presencelight#272]
**Describe the solution you'd like**
To be able to select a room from within the list of available lights

**Describe alternatives you've considered**
I sync to just one of the two lights in the fixture.

**Additional context**
I have a light fixture outside my office I sync to, but it has two bulbs, and I can only select one in the PresenceLight app

**Comment by isaacrlevin** [comment]
Hue Groups support is now in the latest nightly build
![image](https://user-images.githubusercontent.com/8878502/108547396-44870d00-729f-11eb-8a70-93a04ca8fb70.png)

![image](https://user-images.githubusercontent.com/8878502/108547421-4cdf4800-729f-11eb-8f4d-3924fa694999.png)

**Comment by jdpkeeper** [comment]
Thanks man!, 
If I want to solely use the 'config custom api section', do i still need to configure the philips hue section? Because now it just sits at "if you are adding new lights, this may take up to a minute" screen after logging in. and never sync my Teams status.
I ask, because I have a yealink phone that allows me to send post methods to IFTT, to detect when i'm on a physical phone call, which then updates the color of my hue's light, but when I configure the Hue's section within PrescenceLight, the Teams status always overrides the IFTTT Post because it's syncing directly from PrescenceLight.

**Comment by isaacrlevin** [comment]
If you hit a custom endpoint, whatever is behind that endpoint hits Hue right? If that is the case you don't need to wireup the Hue tab at all.

**Comment by isaacrlevin** [comment]
Closing. @jdpkeeper if you have issues, please go ahead and open a new issue
