### ISSUE TITLE
Exit context menu not exiting

### ISSUE THREAD

**Issue by sborg-ms** [isaacrlevin/presencelight#274]
latest nightly - 3.7.43.0

The exit menu does not exit the app any longer.

![image](https://user-images.githubusercontent.com/67351620/108427992-09321180-7292-11eb-820f-b75d5437b292.png)

**Comment by isaacrlevin** [comment]
Just downloaded latest nightly on  clean machine, was able to exit via the context menu. Did you try uninstalling, restarting and reinstalling?

**Comment by sborg-ms** [comment]
Uninstalled. Rebooted. Reinstalled latest nightly 3.7.45.0 and Exit menu now works again.

**Comment by isaacrlevin** [comment]
closing
