### ISSUE TITLE
UX to handle lower res/smaller screens to see all settings

### ISSUE THREAD

**Issue by sborg-ms** [isaacrlevin/presencelight#279]
Using latest nightly (3.7.45.0) and noticed that the settings screen now with so many settings may not fit fully on screen and attempts to resize leave it hard to use.. see sample

eg
![image](https://user-images.githubusercontent.com/67351620/108611110-5ac3d300-742f-11eb-91f9-e07520740e15.png)

**Comment by Shrekmachine** [comment]
on my Monitor (1.440px) even resizing is unfortunately not helping.
![image](https://user-images.githubusercontent.com/8019511/113671333-808ef980-96b6-11eb-938b-8f7aba8ad97e.png)

**Comment by isaacrlevin** [comment]
Hey there, just wanted to update you. I am not going to fix this issue. Rather I am going to migrate the Desktop client to use .NET MAUI which will change the UI completely.

**Comment by Spraggle** [comment]
> Hey there, just wanted to update you. I am not going to fix this issue. Rather I am going to migrate the Desktop client to use .NET MAUI which will change the UI completely.

This is great news, as I'm having this problem too - do you know what your projected timeframe is for this move? Understand it's not an overnight process!

**Comment by isaacrlevin** [comment]
@Spraggle @Shrekmachine have you had a chance to test out the latest nightly version?

**Comment by Shrekmachine** [comment]
I'm on 4.4.23.0. still same issue on 1.440 px

**Comment by isaacrlevin** [comment]
Yep the store is still the old version, I am trying to get feedback on the nightly version before I update the store version

**Comment by sborg-ms** [comment]
@isaacrlevin  always running nightly (as you may recall) - relying on the auto update...  Just checked today and if I open the app from the tray icon i see No UX anymore - (the settings screen is completely blank)

<img width="996" alt="image" src="https://user-images.githubusercontent.com/67351620/151446705-4a761937-dba9-4a60-9991-866fe29f6c67.png">

Is there another quick way to check the version i have now?

**Comment by isaacrlevin** [comment]
Hmmm... Any chance you can install and install from here? Backup your settings first
https://presencelight.blob.core.windows.net/nightly/index.html

**Comment by sborg-ms** [comment]
Seems from app&features - its v5.0.0.0 and installed 20/Jan/2022

Copying settings.json and uninstalling and reinstall.  will advise.

**Comment by sborg-ms** [comment]
ok - after reinstall and re-auth the new UX is showing  (v5.0.0.0)
<img width="253" alt="image" src="https://user-images.githubusercontent.com/67351620/151451718-fedd04d3-31f5-43eb-960d-c2d61694ce39.png">

However after copying settings.json back in the root package dir, it still has not restored all my settings. Are they different now with new UX?

**Comment by isaacrlevin** [comment]
Just copy your light settings.

**Comment by sborg-ms** [comment]
{"Timestamp":"2022-01-28T09:19:32.8115139+11:00","Level":"Information","MessageTemplate":"Error occured Loading Settings","Properties":{"SourceContext":"PresenceLight.Razor.Pages.Index","Application":"PresenceLight"}}
{"Timestamp":"2022-01-28T09:19:34.4901077+11:00","Level":"Information","MessageTemplate":"PresenceLight Running in Teams Mode - MainWindow.xaml:InteractWithLights Line: 580","Properties":{"SourceContext":"PresenceLight.MainWindow","LineNumber":580,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"InteractWithLights","Application":"PresenceLight"}}
{"Timestamp":"2022-01-28T09:19:35.6916633+11:00","Level":"Information","MessageTemplate":"Setting LIFX Light id:d073d540948e to ffff00 - LifxService:SetColor Line: 171","Properties":{"SourceContext":"PresenceLight.Core.LIFXService","LineNumber":171,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\PresenceLight.Core\\Lights\\LifxServices\\LifxService.cs","MemberName":"SetColor","Application":"PresenceLight"}}

**Comment by isaacrlevin** [comment]
No copy the lightsettings section from your appsettings.json

**Comment by sborg-ms** [comment]
thanks - just extracted the key lightsettings and lifx settings and copied into a blank generated json.  
All good and its start up and connected to lifx as before.

Some UX finesse to go but looking ok!

**Comment by isaacrlevin** [comment]
Cool, closing this issue

**Comment by sborg-ms** [comment]
some ex for UX  - spacing and layout

<img width="620" alt="image" src="https://user-images.githubusercontent.com/67351620/151462793-bd79ae50-c5b5-42a8-8ded-f8b6e4227f9c.png">
