### ISSUE TITLE
set color for "on call"

### ISSUE THREAD

**Issue by beber-msft** [isaacrlevin/presencelight#281]
Hello,

I do really like your program, can you please implement a color setting for when I am on a call in teams? teams doesn't activate dnd  status automatically when on call, so would be great to reflect it at least in presencelight.

thank you!

**Comment by isaacrlevin** [comment]
Have you looked at #238? 
https://github.com/isaacrlevin/presencelight/issues/238

I added this feature but it is only available in Nightly, I am waiting to publish to Windows and Choco till end of this week.

**Comment by beber-msft** [comment]
that's perfect, this is fantastic!
