### ISSUE TITLE
New option: Custom API should only be triggered when the activity/availability is changed

### ISSUE THREAD

**Issue by dinoinyourhead** [isaacrlevin/presencelight#288]
For example, I configure a webhook in the Custom API for the Presence State Busy.
If my presence state changes from Available to Busy, the webhook is triggered successfully. However, this repeats every few seconds until the presence state changes again to not equal to Busy.
Depending on which target system/architecture/program is used this is very uncomfortable if the webhook is triggered permanently.

A solution for this would be a simple option with which you can specify that the Custom API is only triggered when the presence state changes.

The behavior is very well visible in the log:
![image](https://user-images.githubusercontent.com/62758238/109347644-c369e000-7873-11eb-823b-277d6b4ec2f6.png)

**Comment by gizmohd** [comment]
I've pushed an update that should resolve this.. WIll only call custom API when it's changed.

**Comment by dinoinyourhead** [comment]
Unfortunately, there are still problems with the function.
The API is no longer permanently triggered. But when changing to a new state and back again, the API is not triggered anymore.
Example:

Available API URI: https://testwebhook
Busy API URI: https://testwebhook2

Current Status: Busy
1. change to available -> API URI called
2. change to Busy -> API URI called > correct
3. change to Available -> API URI call is skipped -> not correct
4. change to Busy -> API URI call is skipped -> not correct
