### ISSUE TITLE
Auto Update while running doesn't restart app

### ISSUE THREAD

**Issue by sborg-ms** [isaacrlevin/presencelight#294]
It seems that when the AppVersion auto updates and it does not restart the Presence app by itself... (so it needs to be manually restarted)
 
 I am aware that the update check also occurs at the initial launch but its also doing a auto check while running and auto updating after terminating the app.
 
 Can we have it auto-restart?

**Comment by isaacrlevin** [comment]
There isn't a graceful way for me to restart the application on update , I can inform the user that an update is available and restart it. Would that be good solution?

**Comment by sborg-ms** [comment]
Ah - that is a pain , i know i have seen other apps be able to restart themselves somehow!

Maybe in the meantime - 2 options based on user config/setting preference
1. AutoUpdate OFF - but do a windows toast notification when there is a new one available and click to update
2. AutoUpdate ON - and do a windows toast notification that it was auto updated (and click to restart?)

thoughts?

**Comment by isaacrlevin** [comment]
I don't have a ton of control regarding updates. Sorry I have to close this. If you find something (or a similar app experience) I will circle back. I recommend a hotkey or something to close/start PL
