### ISSUE TITLE
Version 4 deinstall, reinstall to get it to work.

### ISSUE THREAD

**Issue by Shrekmachine** [isaacrlevin/presencelight#301]
**Describe the bug**
app did not control Hue Light even that everything was looking ok

**To Reproduce**

**Expected behavior**
continuation after update

**Screenshots**
...

## Further details
- 21H1
- PresenceLight App Type Desktop
- PresenceLight Build Store
- PresenceLight Version 4.0.1.0
- Did you clear settings.json? (C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json
by deinstalling
- ASP.NET Core version ?

**Comment by isaacrlevin** [comment]
To be clear, v4 does not work for your Hue lights at all?

**Comment by Shrekmachine** [comment]
It works after reinstalling and without using Working hours

**Comment by isaacrlevin** [comment]
4.0.26 has a fix for this

**Comment by Shrekmachine** [comment]
sounds good
