### ISSUE TITLE
error each second in log

### ISSUE THREAD

**Issue by Shrekmachine** [isaacrlevin/presencelight#302]
**Describe the bug**
app is throwing an error every few second in the log file

{"Timestamp":"2021-03-10T18:20:31.8667898+01:00","Level":"Error","MessageTemplate":"Error Occurred - MainWindow.xaml:SetColor Line: 372","Exception":"System.InvalidOperationException: Der aufrufende Thread kann nicht auf dieses Objekt zugreifen, da sich das Objekt im Besitz eines anderen Threads befindet.\r\n   at System.Windows.Threading.Dispatcher.VerifyAccess()\r\n   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)\r\n   at PresenceLight.MainWindow.SetColor(String color, String activity)","Properties":{"SourceContext":"PresenceLight.MainWindow","LineNumber":372,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"SetColor","Application":"PresenceLight"}}

**To Reproduce**
run app

**Expected behavior**
no repeated errors

**Screenshots**
![image](https://user-images.githubusercontent.com/8019511/110672178-a0262580-81cf-11eb-8a37-90f1fc1597c7.png)

## Further details
- 21H1
- PresenceLight App Type Desktop
- PresenceLight Build Store
- PresenceLight Version 4.0.1.0
- Did you clear settings.json? (C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json
by deinstalling reinstalling
- ASP.NET Core version ?

**Comment by isaacrlevin** [comment]
@Shrekmachine what lights are you connecting to?

**Comment by Shrekmachine** [comment]
only 1 Hue Light

**Comment by JonathanImanami** [comment]
Seems Hue light is broken in latest build

**Comment by denglishbi** [comment]
Doesn't seem to be working with Lifx light now either in latest build that I just received from the Windows Store 4.0.1.0  I was able to set the colors in the app, but keep seeing error messages now in the Live Log feed and this just keeps repeating in the log over and over.


3/12/2021 3:30:56 PM -06:00 | Information | PresenceLight Running in Teams Mode - MainWindow.xaml:InteractWithLights Line: 732
-- | -- | --
3/12/2021 3:30:56 PM -06:00 | Error | Error Occured Setting Color - LifxService:SetColor Line: 299
3/12/2021 3:30:56 PM -06:00 | Error | Error Occurred - MainWindow.xaml:SetColor Line: 372
