### ISSUE TITLE
Configure Working hours not working

### ISSUE THREAD

**Issue by Shrekmachine** [isaacrlevin/presencelight#303]
**Describe the bug**
HueLight did not switch off at expected time. 
Time set is 18:30
now it is 18:40 cet

**To Reproduce**
wait another day

**Expected behavior**
HueLight to switch off at end of working hours

**Screenshots**
...
![image](https://user-images.githubusercontent.com/8019511/110672500-fabf8180-81cf-11eb-8e1c-117092367a83.png)

## Further details
- 21H1
- PresenceLight App Type Desktop
- PresenceLight Build Store
- PresenceLight Version 4.0.1.0
- Did you clear settings.json? (C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json
by deinstalling
- ASP.NET Core version ?

**Comment by isaacrlevin** [comment]
Take a look at the latest nightly, this should be fixed
4.0.26

**Comment by Shrekmachine** [comment]
I may wait until release :)

**Comment by isaacrlevin** [comment]
In store now

![image](https://user-images.githubusercontent.com/8878502/111195827-e5ed4000-8579-11eb-95a9-4f92cdea4624.png)

**Comment by Shrekmachine** [comment]
do I need to reset settings?

**Comment by isaacrlevin** [comment]
You probably will need to

**Comment by Shrekmachine** [comment]
Looks better now. PresenceLight is switching off the Hue, when Working hours are configured. I'll check with the hour specific feature separately

**Comment by Shrekmachine** [comment]
don't ask me why, but issue with working hours not working is back. Still on 4.0.26.0

**Comment by Shrekmachine** [comment]
thank you :) I installed the version 4.0.36.0
When exiting Hue Light switches off again, when Working hours is activated 👍 
Working hours switches off and the given time. Nice job! 👍

**Comment by isaacrlevin** [comment]
Closing... again ;0
