### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by isaacrlevin** [isaacrlevin/presencelight#306]
Getting this exception in logs when I hit the LightController like so

https://localhost:5001/api/Light?command=Custom

> Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
today at 12:39 PM  Object name: 'IServiceProvider'.
today at 12:39 PM     at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
today at 12:39 PM     at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
today at 12:39 PM     at MediatR.ServiceFactoryExtensions.GetInstances[T](ServiceFactory factory)
today at 12:39 PM     at MediatR.Internal.RequestHandlerWrapperImpl`2.Handle(IRequest`1 request, CancellationToken cancellationToken, ServiceFactory serviceFactory)
today at 12:39 PM     at MediatR.Mediator.Send[TResponse](IRequest`1 request, CancellationToken cancellationToken)
today at 12:39 PM     at PresenceLight.Worker.Controllers.LightController.UpdateLight(String command) in /source/PresenceLight.Worker/Controllers/LightController.cs:line 81
today at 12:39 PM     at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
today at 12:39 PM     at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
today at 12:39 PM     at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
today at 12:39 PM     at System.Threading.QueueUserWorkItemCallback.Execute()
today at 12:39 PM     at System.Threading.ThreadPoolWorkQueue.Dispatch()
today at 12:39 PM     at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
today at 12:39 PM     at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Looks like Mediator does not like being injected into the controller.

**Comment by isaacrlevin** [comment]
mind taking a look @gizmohd ?

**Comment by gizmohd** [comment]
Created PR
