### ISSUE TITLE
Configuration for Custom API lost after upgrade to 4.0.24.0

### ISSUE THREAD

**Issue by thomastitze** [isaacrlevin/presencelight#308]
After automatic upgrade to latest Windows Store version the existing configuration for the custom API is lost. The settings.json file contains only the default values.

Configuration should move forward with new updates.
Windows 10 19042.867, US English Version, German Keyboard Settings
Current Presence Light Version after the upgrade: 4.0.24.0

**Comment by pwrutter** [comment]
Hi
Also noticed I cant update and save new entries for the custom API either.

**Comment by thomastitze** [comment]
Same here, can't also not update and save custom API settings. Checked config file and entries for Custom API always null:
 "CustomApi": {
      "CustomApiTimeout": 0.0,
      "CustomApiAvailable": null,
      "CustomApiBusy": null,

Only IsEnabled is udated

**Comment by isaacrlevin** [comment]
Can all of you delete your settings file and have the app create one. There was a bit of churn with settings in V4. I was just able to fresh install the store version and save Custom Api settings.

Sorry for the inconvenience.

**Comment by pwrutter** [comment]
Awesome, that's now persisting the changes! I have noticed though that now it seems to be saying "skipped" quite a lot when the status changes - Is this related or something else?

![image](https://user-images.githubusercontent.com/6960931/111289892-82c4e180-863d-11eb-863b-2112281b358e.png)

**Comment by isaacrlevin** [comment]
Can you email me a copy of your logs? isaac@isaaclevin.com?

Closing this issue, feel free to open another if you see fit
