### ISSUE TITLE
Presence question

### ISSUE THREAD

**Issue by vovanb** [isaacrlevin/PresenceLight#31]
Hello
Nice project - I am interesting in Teams graph API... 
I set .net CORE to  3.1.201, after that change project compiled but on login it opened browser and after SSO I have waiting indicator only.
1.What can be issue?
2. I am looking for developing application for presence sync in windows service - is it possible to accomplish or it will always open new browser for login into Teams account?

**Comment by isaacrlevin** [comment]
You have to get a token interactively, no way to just get a token without login
