### ISSUE TITLE
Unable to connect with teams

### ISSUE THREAD

**Issue by koenvzeijl** [isaacrlevin/presencelight#311]
**Describe the bug**
In advance, I'm sorry if this is a duplicate, I didn't see any other issue with this problem, I would like to use this application and write a blog about it.

After downloading and installing the latest version from the windows store it seems like I'm unable to authenticate myself. I start the application and log in on the portal that opens. This shows me the following message: "Authentication complete. You can return to the application. Feel free to close this browser tab.". After coming back to the app it keeps hanging on the loading icon, when I look at the logs it reads the following: 

`{"Timestamp":"2021-03-15T18:33:55.3301936+01:00","Level":"Error","MessageTemplate":"Error occured Checking Wiz - MainWindow.Wiz:CheckWiz Line: 109","Exception":"System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.......}`

**To Reproduce**
1. Download the latest version from the windows store
2. Open the app
3. Login with outlook
4. Go back to the app

**Expected behavior**
I expect to be able to use the application after authentication.

**Screenshots**
![image](https://user-images.githubusercontent.com/15815407/111196586-bd873500-85bd-11eb-81d0-edeacae45255.png)
![image](https://user-images.githubusercontent.com/15815407/111197002-3ab2aa00-85be-11eb-861b-5a98afe7d00b.png)

## Further details
- OS: Windows
- PresenceLight App Type: (Desktop, Blazor)
- PresenceLight Build: (Store)
- PresenceLight Version: 4.0.26.0
- Did you clear settings.json? No
- ASP.NET Core version: 5.0.4

**Comment by isaacrlevin** [comment]
Please update to the latest version 4.0.26

**Comment by isaacrlevin** [comment]
Also, are you looking into a O365 account or a Microsoft Personal account?

**Comment by koenvzeijl** [comment]
Hi there, excuse me I'm on 4.0.26. My bad :(.

I'm using a O365 account as it doen't allow me to login with my Microsoft Personal account

**Comment by isaacrlevin** [comment]
Are you trying to use Wiz lights? I was able to get a fresh install from the store to work just now.

**Comment by koenvzeijl** [comment]
Hi, No I'm not that was just the first error I saw in the logs, I want to use them with my Hue. Unfortunately, it fails after logging in successfully on the web. Can I deliver some more information about logs or something?

**Comment by Shrekmachine** [comment]
Did you delete settings? I observed that behaviour with prev version. reinstall helped me solve my problems.

**Comment by gizmohd** [comment]
Teams is undergoing a Global Outage right now...

https://downdetector.com/status/teams/

May be affecting this

**Comment by koenvzeijl** [comment]
After deleting the settings file in `\37828IsaacLevin.197278F15330A_zfcjmmeb3zeaa\LocalState\settings.json` it doesn't ask me to login again. Although it does recreate the settings file and the logs. Btw it seems like that a `\` is missing between LocalState and settings.json
![image](https://user-images.githubusercontent.com/15815407/111336685-c0456100-8675-11eb-9d69-efda6937545b.png)

**Comment by isaacrlevin** [comment]
@koenvzeijl yep that will be fixed in the latest nightly and store today. Closing this issue now

**Comment by koenvzeijl** [comment]
@isaacrlevin  Thanks, I'll let you know if it fixed the issue
