### ISSUE TITLE
How to get PL started minimized?

### ISSUE THREAD

**Issue by Shrekmachine** [isaacrlevin/presencelight#323]
**Is your feature request related to a problem? Please describe.**
PL is starting with every start of windows with config window visible

**Describe the solution you'd like**
Decide if to start minimized

**Describe alternatives you've considered**
I tried to set the app to start minimized, but the option is not available

**Additional context**
No need to configure PL every time. I prefer it to work silently in the background

**Comment by isaacrlevin** [comment]
Can you? Yes you can
How should it work? This is the problem, I imagine I can add a setting to "start minimized"

Will think about this.

**Comment by isaacrlevin** [comment]
This is now deployed to latest nightly. There is now an option to "Start Minimized"
![image](https://user-images.githubusercontent.com/8878502/112218781-61d23280-8be1-11eb-8317-71ee0b20243f.png)

**Comment by Shrekmachine** [comment]
thank you, will test it with next store release :)

**Comment by Shrekmachine** [comment]
Configure screen shortly pops up and then minimizes itself. Very well :) 👍 
Version 4.1.41.0
