### ISSUE TITLE
Custom API format

### ISSUE THREAD

**Issue by andye2801** [isaacrlevin/presencelight#324]
Hi,

Firstly great app!

I am trying to integrate the app with Home Assistant by using the API Home Assistant has, however the API needs to be JSON formatted. https://developers.home-assistant.io/docs/api/rest/#post-apistatesltentity_id

Basically I need to be able to send the below, would this be possible to develop?

curl --location --request POST 'https://homeassistant.domain/api/states/sensor.user_teams' \
--header 'Authorization: Bearer -----API-KEY--------' \
--header 'Content-Type: application/json' \
--data-raw '{
"state": "Busy"
}'

**Comment by isaacrlevin** [comment]
I don't have Home Assistant to test. Happy to accept a PR

**Comment by andye2801** [comment]
For anyone else that comes across this you can use POST to send a Webhook to HA.

You'll need a script to set state of entities, call this script with a Webhook automation to set the state as required.

You'll need a webhook for each API call.

**Comment by isaacrlevin** [comment]
Thanks for the followup @andye2801. If you are interested, I would love to document HA integration. Can you do a quick writeup and I can put it in the README?

**Comment by andye2801** [comment]
I'll write something up yes, I am noticing that on the Configure Custom API page I'm seeing "Last Response: SkippedSkipped" a lot and it's not updating the status on HA. I know the webhooks work as they have been tested via postman. Any idea where I can look into this?

![image](https://user-images.githubusercontent.com/19046762/112021195-eb71f980-8b28-11eb-9687-f15de7253165.png)

![image](https://user-images.githubusercontent.com/19046762/112021336-19efd480-8b29-11eb-85e6-ec055e424bf8.png)

**Comment by isaacrlevin** [comment]
Is it on certain calls, or is it kindof random? Have you tried looking at the traffic in Fiddler yet?

**Comment by andye2801** [comment]
It seems like it sends the first change after the PresenceLight app is opened and then no more Webhooks are sent. If I quit the app and reopen it the status in HA is updated then if I change Teams status a Webhook is sent but then further Teams status updates do not result in a Webhook being sent.

**Comment by isaacrlevin** [comment]
I feel like this was a bug before. Can you email me your settings file?

***@***.***

**Comment by andye2801** [comment]
Github has blanked your email out, but I found it on your profile so an email should be on its way

**Comment by loganjohnlong** [comment]
@andye2801 I have a temporary (and not super secure) method of using HA [here](https://github.com/loganjohnlong/presence-light-ha-api). I will eventually work on a PR to add HA as a dedicated service, but it isn't currently high on my priority list. Under no circumstances should the bridge I wrote be used where it can be accessed by the public internet.

**Comment by andye2801** [comment]
@loganjohnlong That's useful for some but I feel I've hit a bug that only calls the API once until an app reboot.

Also your bridge changes a light colour, my webhooks change the state of my "Andy_Teams" sensor so I can use the state of that entity to automate a light etc.

**Comment by rstrrt** [comment]
Hi, I've hit the same bug using the custom api for POSTING to nodered. I'd love to use the app to drive a light in my home via bTicino MyOpenWebNet integration.
When app starts, the status is updated and posted. First teams status change is detected and posted, then nothing more.
Happy to help debugging: let's get this working :)

**Comment by andye2801** [comment]
@rstrrt download the latest nightly build, @isaacrlevin has resolved this yesterday.

**Comment by rstrrt** [comment]
Yep, seems to be working fine now! Thanks a lot!

**Comment by isaacrlevin** [comment]
Closing this now, will go to all channels end of week
