### ISSUE TITLE
Can't sign in after update

### ISSUE THREAD

**Issue by tomknevitt** [isaacrlevin/presencelight#326]
**Describe the bug**
After app updated through microsoft store all settings was lost. I reinstalled the app from the store, logged into microsoft account but i am left with this 
![image](https://user-images.githubusercontent.com/57263205/111761780-2f020480-8898-11eb-95cc-daca6ec5af48.png)
Tried removing the settings and trying again but no luck. Uninstalled store version and installed versin from GitHub but same issue. Tried running as administrator but same issue. I have even tried on another computer with no luck. Starting to think there is an issue with my microsoft account.

I can see in azure that it has connected the app sucessfully to my account. I removed the app from azure and tried again but no difference. 

## Further details
- OS: Windows 10 Ver 1909
- PresenceLight App Type: Desktop
- PresenceLight Build: Tried Store & GitHub
- PresenceLight Version: 4.1.32
- Did you clear settings.json? (C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json, YES
- ASP.NET Core version

**Comment by isaacrlevin** [comment]
Are there any logs that show anything?

**Comment by tomknevitt** [comment]
{"Timestamp":"2021-03-19T09:52:43.0211732+00:00","Level":"Information","MessageTemplate":"Getting Graph Data: Profle, Image, Presence - GraphWrapper:GetBatchContent Line: 69","Properties":{"SourceContext":"PresenceLight.Core.GraphWrapper","Application":"PresenceLight","LineNumber":69,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\PresenceLight.Core\\GraphServices\\GraphWrapper.cs","MemberName":"GetBatchContent"}}
{"Timestamp":"2021-03-19T09:52:49.8097339+00:00","Level":"Error","MessageTemplate":"Error Occurred - MainWindow.xaml:GetPhoto Line: 587","Exception":"System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)\r\n   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)\r\n   at Microsoft.Graph.BaseRequest.SendStreamRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)\r\n   at PresenceLight.Core.GraphWrapper.<>c__DisplayClass10_0.<<GetPhoto>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)\r\n   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)\r\n   at PresenceLight.Core.GraphWrapper.GetPhoto(CancellationToken token)\r\n   at PresenceLight.Core.GraphServices.GetPhotoHandler.Handle(GetPhotoCommand command, CancellationToken cancellationToken)\r\n   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at PresenceLight.MainWindow.GetPhoto()","Properties":{"SourceContext":"PresenceLight.MainWindow","Application":"PresenceLight","LineNumber":587,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"GetPhoto"}}
{"Timestamp":"2021-03-19T09:52:49.8139652+00:00","Level":"Error","MessageTemplate":"Error occured - MainWindow.xaml:CallGraph Line: 340","Exception":"System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)\r\n   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)\r\n   at Microsoft.Graph.BaseRequest.SendStreamRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)\r\n   at PresenceLight.Core.GraphWrapper.<>c__DisplayClass10_0.<<GetPhoto>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)\r\n   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)\r\n   at PresenceLight.Core.GraphWrapper.GetPhoto(CancellationToken token)\r\n   at PresenceLight.Core.GraphServices.GetPhotoHandler.Handle(GetPhotoCommand command, CancellationToken cancellationToken)\r\n   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at PresenceLight.MainWindow.GetPhoto()\r\n   at PresenceLight.MainWindow.CallGraph()","Properties":{"SourceContext":"PresenceLight.MainWindow","Application":"PresenceLight","LineNumber":340,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"CallGraph"}}
{"Timestamp":"2021-03-19T09:52:54.4844561+00:00","Level":"Information","MessageTemplate":"PresenceLight Exiting - MainWindow.xaml:OnExitClick Line: 691","Properties":{"SourceContext":"PresenceLight.MainWindow","Application":"PresenceLight","LineNumber":691,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"OnExitClick"}}

**Comment by isaacrlevin** [comment]
Are you logging into an M365 account? That error looks like it is failing getting your graph data

**Comment by tomknevitt** [comment]
Yes, window launches to sign in. No issues and tells me to close the window.
I have tried removing the app from azure and reinstalling from scratch but did not fix the issue.

**Comment by isaacrlevin** [comment]
Have your tried nightly by chance?

**Comment by jdpkeeper** [comment]
Same issue as @tomknevitt

**Comment by jdpkeeper** [comment]
just tried the nightly build, and same result.

**Comment by isaacrlevin** [comment]
Can I get your settings file? emailed to me?

**Comment by jdpkeeper** [comment]
sent

**Comment by isaacrlevin** [comment]
Try out the latest nightly

**Comment by jdpkeeper** [comment]
That worked, v4.2.3.0 fixed it.
Thanks so much for the support, your app is super helpful working from home.

cheers,
Josh

**Comment by isaacrlevin** [comment]
closing

**Comment by tomknevitt** [comment]
Also worked for me on nightly version v4.2.3.0. 
thanks for the fantastic support.
How do I buy you a beer?

**Comment by isaacrlevin** [comment]
I have GitHub sponsors ;)

**Comment by Shrekmachine** [comment]
Reinstallation solved the issue, while I do see this more as a workaround than a solution
