### ISSUE TITLE
x64 version from chocolatey doesn't load login prompt

### ISSUE THREAD

**Issue by loganjohnlong** [isaacrlevin/presencelight#330]
**Describe the bug**
x64 version of PresenceLight doesn't open the login prompt when starting for the first time.

**To Reproduce**
1. Download the x64 build of PresenceLight (chocolatey version)
2. Quit any currently running versions of PresenceLight
3. Run the x64 build from the downloaded folder (so it uses the default settings)
4. See that the "Sign In" tab is blank and does not prompt for login.

**Expected behavior**
Application behaves as it does in the x86 version and prompts for log in when application is first started.

**Logs**
`{"Timestamp":"2021-03-22T13:42:59.7459025-05:00","Level":"Error","MessageTemplate":"Error saving Settings - StandaloneSettingsService:SaveSettings Line: 84","Exception":"System.UnauthorizedAccessException: Access to the path 'C:\\WINDOWS\\system32\\settings.json' is denied.\r\n   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)\r\n   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)\r\n   at System.IO.File.AsyncStreamWriter(String path, Encoding encoding, Boolean append)\r\n   at System.IO.File.WriteAllTextAsync(String path, String contents, Encoding encoding, CancellationToken cancellationToken)\r\n   at PresenceLight.Services.StandaloneSettingsService.SaveSettings(BaseConfig data)","Properties":{"SourceContext":"PresenceLight.Services.StandaloneSettingsService","Application":"PresenceLight","LineNumber":84,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\Services\\StandaloneSettingsService.cs","MemberName":"SaveSettings"}}`

`{"Timestamp":"2021-03-22T13:42:59.7649247-05:00","Level":"Error","MessageTemplate":"Error Loading Settings - StandaloneSettingsService:LoadSettings Line: 68","Exception":"System.IO.FileNotFoundException: Could not find file 'C:\\WINDOWS\\system32\\settings.json'.\r\nFile name: 'C:\\WINDOWS\\system32\\settings.json'\r\n   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)\r\n   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)\r\n   at System.IO.File.AsyncStreamReader(String path, Encoding encoding)\r\n   at System.IO.File.InternalReadAllTextAsync(String path, Encoding encoding, CancellationToken cancellationToken)\r\n   at PresenceLight.Services.StandaloneSettingsService.LoadSettings()","Properties":{"SourceContext":"PresenceLight.Services.StandaloneSettingsService","Application":"PresenceLight","LineNumber":68,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\Services\\StandaloneSettingsService.cs","MemberName":"LoadSettings"}}`

`{"Timestamp":"2021-03-22T13:42:59.7658666-05:00","Level":"Error","MessageTemplate":"Error occured Loading Settings - MainWindow.Settings:LoadSettings Line: 99","Exception":"System.NullReferenceException: Settings Load Service Returned null\r\n   at PresenceLight.MainWindow.LoadSettings()","Properties":{"SourceContext":"PresenceLight.MainWindow","Application":"PresenceLight","LineNumber":99,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.Settings.cs","MemberName":"LoadSettings"}}
{"Timestamp":"2021-03-22T13:43:00.0700571-05:00","Level":"Error","MessageTemplate":"Error occured Checking LIFX - MainWindow.Lifx:CheckLIFX Line: 138","Exception":"System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at PresenceLight.MainWindow.CheckLIFX()","Properties":{"SourceContext":"PresenceLight.MainWindow","Application":"PresenceLight","LineNumber":138,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.Lifx.cs","MemberName":"CheckLIFX"}}`

`{"Timestamp":"2021-03-22T13:43:00.0721429-05:00","Level":"Error","MessageTemplate":"Error occured Checking Azure Active Directory - MainWindow.Settings:CheckAAD Line: 216","Exception":"System.Reflection.TargetException: Non-static method requires a target.\r\n   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)\r\n   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)\r\n   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)\r\n   at System.Reflection.PropertyInfo.GetValue(Object obj)\r\n   at PresenceLight.MainWindow.SyncOptions()\r\n   at PresenceLight.MainWindow.CheckAAD()","Properties":{"SourceContext":"PresenceLight.MainWindow","Application":"PresenceLight","LineNumber":216,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.Settings.cs","MemberName":"CheckAAD"}}`

`{"Timestamp":"2021-03-22T13:43:00.0734466-05:00","Level":"Error","MessageTemplate":"Error occured - Object reference not set to an instance of an object. - MainWindow.xaml:LoadApp Line: 202","Exception":"System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at PresenceLight.MainWindow.LoadApp()","Properties":{"SourceContext":"PresenceLight.MainWindow","Application":"PresenceLight","LineNumber":202,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"LoadApp"}}`

## Further details
- OS: Windows 10 Enterprise 20H2
- PresenceLight App Type: Desktop
- PresenceLight Build: 4.1.36 (chocolatey)
- PresenceLight Version: "Not Packaged"
- Did you clear settings.json? (C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json): Yes
- ASP.NET Core version: 5.0.4

**Comment by loganjohnlong** [comment]
Not entirely sure why it is referencing a `D:` drive, as I don't have one mounted on the machine I use PresenceLight on.

**Comment by isaacrlevin** [comment]
Do you have the same issue if you try the x64 version in GitHub releases?

**Comment by loganjohnlong** [comment]
@isaacrlevin Doesn't look like it. GitHub release seems to work fine.

**Comment by isaacrlevin** [comment]
Well that is interesting. Let me take a look at the Choco install

**Comment by isaacrlevin** [comment]
Try this, go to this dir, C:\ProgramData\chocolatey\lib\PresenceLight\tools

and copy appsettings.json and save it as settings.json at the same directory. Than start PL

**Comment by steviecoaster** [comment]
I've put up a PR for this: #333

**Comment by isaacrlevin** [comment]
4.1.41 has the fix
