### ISSUE TITLE
Docker Image config issue

### ISSUE THREAD

**Issue by andye2801** [isaacrlevin/presencelight#338]
I'm trying to get the worker running on my docker environment, but getting this error:

Unhandled exception. System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.

I use a nginx reverse proxy (Swag container) and therefore would like to not add a certificate to the presencelight container as swag handles all my SSL termination.

Any advice would be great?

**Comment by isaacrlevin** [comment]
You need one to call Graph, so you need a cert

**Comment by andye2801** [comment]
I understand I need a cert, and I have one that is set up for presencelight.mydomain.com as your readme.

How can I add this to the docker container so it looks for that instead of the 3 you list below?

In order for PresenceLight to work, you need to have a redirect url to AAD that is https. In order to make it easy for folks, I provided a self-signed cert that will allow PresenceLight to do Https redirection out of the box. Isaac is this secure? Weeeeeeelllll not the best, but since PresenceLight runs locally you should be fine. If you want to expose PresenceLight over the internet, it more than likely won't work as I have to register EACH redirect uri with Azure AD. Here is a list of registered Uris that you can use.

https://localhost:5001 (if you are running pure local)
https://192.168.86.27:4433 (this is how I run docker)
https://127.0.0.1:5001 (if for some reason you want to use loopback)
For my particular use-case I do not need SSL. WHAT?!?! Actually it is pretty cool. My personal setup is that PresenceLight runs in a docker container on a Raspberry Pi. I have Traefik, which is a well-known reverse proxy that allows me to forward applications through my domain, so I can access the application from anywhere by going to

presencelight.mydomain.com

**Comment by andye2801** [comment]
I'm also confused as to what port the app will be running on, the readme implies port 443 but the screenshot & docker details seem to show 5001?

![image](https://user-images.githubusercontent.com/19046762/112468242-eb0f7380-8d5f-11eb-8cf1-16cba29e6b68.png)

**Comment by andye2801** [comment]
After further thinking from me it is clear that I need the cert on the container for the outbound connection to AAD, is that correct?

My cert is in a volume that I am also mounting read only on the presencelight container, but I think I'm struggling to reference this extra volume for the container to see the certificate.

**Comment by isaacrlevin** [comment]
Take a look at my docker-compose from #325 

https://github.com/isaacrlevin/presencelight/issues/325#issuecomment-802313010

**Comment by andye2801** [comment]
Thanks, I got this working with help from the linked docker-compose file.
