### ISSUE TITLE
Custom API doesn't trigger activity

### ISSUE THREAD

**Issue by mkrijtenberg** [isaacrlevin/presencelight#341]
Hi Isaac,

I'm using the worker version and have it installed on docker. Works like a charm!

However: I'm using the custom API to send information to my home dashboard, which displays if I'm in a call or not. When I was using the windows app a few versions back, it was sending activity information like InACall or InAMeeting. And now it just sends my status Busy or Available. 

I have set an endpoint for every status/activity, but am I doing something wrong, or is it not sending activity updates?

**Comment by isaacrlevin** [comment]
What is the docker image you are using?

**Comment by mkrijtenberg** [comment]
The latest one from: https://registry.hub.docker.com/r/isaaclevin/presencelight/
updated 4 days ago

Info from the About page:
Application Version: 1.0.0.0
Runtime Version: 5.0.4+f27d33729518f5aa478aa818b7b4f54a4d50bef1

**Comment by mkrijtenberg** [comment]
I think I have found the issue:

https://github.com/isaacrlevin/presencelight/blob/80ff69cd85cbdcaff093f39ea87688f9f39e5f11/src/PresenceLight.Core/Lights/CustomApiService/CustomApiService.cs#L52-L53

The activity gets overridden by the availability. I guess that should only happen outside working hours, as the comment suggests.

**Comment by isaacrlevin** [comment]
funny I was just looking at this little bit. I will try to push a fix to docker today

**Comment by isaacrlevin** [comment]
Ok, give the newest image a test

**Comment by mkrijtenberg** [comment]
Thanks! I'll test it tomorrow! :)

**Comment by mkrijtenberg** [comment]
It works!!! Thanks!!
