### ISSUE TITLE
LIFX no longer turns off

### ISSUE THREAD

**Issue by sborg-ms** [isaacrlevin/presencelight#346]
LIFX lights wont turn off at all (even after end of business hours) now after latest build - v4.2.9.0.  Even when manually turning light off with the app running it will turn back on to the last status colour.

**Comment by isaacrlevin** [comment]
This is fixed in latest nightly

**Comment by isaacrlevin** [comment]
Fixed in store version, please test

**Comment by sborg-ms** [comment]
So in Nightly as well?  v**4.2.13.0** nightly seems now it does not turn off after business hrs ends in settings....

**Comment by isaacrlevin** [comment]
4.2.14 this is fixed :)

**Comment by sborg-ms** [comment]
tested today in v4.2.14 and its working as expected again! :)
