### ISSUE TITLE
Custom API URIs and config not saving in 4.1.41.0 Desktop

### ISSUE THREAD

**Issue by jason3fc** [isaacrlevin/presencelight#347]
**Describe the bug**
Custom API Entries not saving when application is closed and restarted. I have enabled Custom API calls Entered in Several API URIs and Methods, Clicked Save at bottom and when PresenceLight is restarted, all of that config is gone and Custom API page is all blank fields.

**To Reproduce**
Go into Configure Custom API - check Enable Custom API Calls. Enter URIs and API Methods (in my case POST) Click Save. 

**Expected behavior**
API URIs, Methods and Enabledness should persist through restarting the app.

## Further details
- OS:Windows 10 Desktop
- PresenceLight App Type Desktop
- PresenceLight Build Store
- PresenceLight Version 4.1.41.0
- Did you clear settings.json? YES - I completely deleted the file and restarted.
- ASP.NET Core version ASP.NET 5

**Comment by cjhearn** [comment]
I'm using v4.2.9.0 from Microsoft Store, and this is also an issue. Opening the settings.json file shows `"CustomApi": null,`

**Comment by isaacrlevin** [comment]
This should be fixed in latest nightly, be sure to delete your settings file

**Comment by isaacrlevin** [comment]
@cjhearn @jason3fc this issue is fixed in the store version, can you confirm?

**Comment by cjhearn** [comment]
Hi @isaacrlevin - can confirm fixed in 4.2.12.0 from the store. Thanks!

**Comment by jason3fc** [comment]
I can also confirm its fixed in store version. Thanks!
