### ISSUE TITLE
Setting "GET" or "POST" on "Off" state with Custom API sets "Activity Presenting" to the same API method

### ISSUE THREAD

**Issue by loganjohnlong** [isaacrlevin/presencelight#356]
**Describe the bug**
Setting the API method to "GET" or "POST" on the "Off" state with Custom API enabled sets "Activity Presenting" to the same API method. This works in both directions

**To Reproduce**
1. Go to "Configure Custom API"
2. Click on "Enable Custom API calls"
3. Click on the API method dropdown to the right of the "Off" Presence State and select either "GET" or "POST"

**Expected behavior**
Setting the API method should only affect a single Presence State.

## Further details
- OS: Windows 10 Enterprise
- PresenceLight App Type: Desktop
- PresenceLight Build: Chocolatey
- PresenceLight Version: 4.2.13
- Did you clear settings.json? Yes (C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json
- ASP.NET Core version: 5.0.4

**Comment by isaacrlevin** [comment]
Fixed in Nightly Build v4.2.20

**Comment by isaacrlevin** [comment]
Fixed in Choco version
