### ISSUE TITLE
Enhancement: Hue cloud API

### ISSUE THREAD

**Issue by mzac** [isaacrlevin/PresenceLight#36]
Would there be any way to configure the application to use the Hue cloud API?  A lot of users these days use VPN so their hue bridge on their LAN would not be accessible as all traffic is routed through the VPN.

**Comment by isaacrlevin** [comment]
Can you point me to the hue cloud API documentation? All I can find is bridge based docs

**Comment by mzac** [comment]
Here we go:

https://developers.meethue.com/develop/hue-api/remote-api-quick-start-guide/

**Comment by mzac** [comment]
Hmm.. I think you need to register an APP ID to get it to work.  Not sure this is going to work the way I thought.

https://developers.meethue.com/add-new-hue-remote-api-app/

**Comment by isaacrlevin** [comment]
This is something I would need to do. I am doing something similar with LIFX

**Comment by isaacrlevin** [comment]
Sadly I cannot test this, as I have an older bridge. I may write the code and need you to test

**Comment by mzac** [comment]
> Sadly I cannot test this, as I have an older bridge. I may write the code and need you to test

For sure I can test!  I do have one of the newer bridges.

**Comment by isaacrlevin** [comment]
Can you build the code yourself? If so, this branch has the changes in there

https://github.com/isaacrlevin/PresenceLight/tree/hue-cloud

**Comment by mzac** [comment]
I'll give it a go and let you know if I have any issues!  Can you point me in the right direction to compile it though?  I've never compiled a windows application (hardcore linux user here)

**Comment by isaacrlevin** [comment]
FYI the latest Nightly has Hue Cloud Support, let me know if you have any issue

v3.5.35

**Comment by isaacrlevin** [comment]
@mzac can you test?

**Comment by isaacrlevin** [comment]
Closing as this is in the nightly build now, will go to store next week

**Comment by mzac** [comment]
@isaacrlevin I just had the chance to test this morning and it works!! Awesome!
