### ISSUE TITLE
Home scenario: Possible status situations

### ISSUE THREAD

**Issue by LagaV** [isaacrlevin/PresenceLight#37]
Thanks, for your app. Works as expected.

While currently working from home I'm coming to the conclusion, that the Online status (Graph API: availability) isn't as helpful to indicate my family what's "needed".

In general I see two dimensions: 
a) I don't want to be distracted: (Important) presentation I'm giving, (intense) 1on1, anything that shouldn't be disturbed.
b) Avoiding awkward moments broadcasted into my call/meeting, mostly with camera and/or mic on.

So the distinction is more around the following parameters:
- Being in a call / meeting?
- Presenting / not presenting?
- Mic on / Muted
- Camera on/off

Regarding status this leads to the following states to signal:

Red flashing: really don't disturb - don't even tell me anything or ask anything
Red: In a call / meeting -- Mic / Video on -- I might be able to react
Yellow: In a call / meeting -- Mic / Video are on, be aware, but's it's ok for me to disturb
Green: Might be in a call or not -- but: Mic/video off  -- Let's talk
Off: Bulb turned off.

So in general, the Graph API: activity status might be a better indicator, combined  with the not available "Muted/Unmuted" & "Video On/Off" status. plus potentially some calendar flagging / interpretation and the unknown fact of "number of participants in the call/meeting".

For a faster implementation a kind of category selection to select a light status from the above list combined with the API-activity value might be a starter.

Just my 2c!

**Comment by isaacrlevin** [comment]
If you are presenting or in do not disturb, PresenceLight changes to a purplish color, here is the page that has available statuses
https://docs.microsoft.com/en-us/microsoftteams/presence-admins

**Comment by LagaV** [comment]
> 
> If you are presenting or in do not disturb, PresenceLight changes to a purplish color, here is the page that has available statuses
> 

Manual "Do not disturb" for me is mostly: Don't disturb me towards my online colleagues, but would be something else for my family. 

In this regard: How is "Focus time" handled?

**Comment by isaacrlevin** [comment]
What you want is customizable control of colors. Why dont you do that manually? I only have access to the statuses available on that docs page. Anything more than that is manual

**Comment by isaacrlevin** [comment]
Sounds like you want to do custom colors. All I can do is change based on the statuses in that doc.

**Comment by LagaV** [comment]
Probably my initial approach was too complicated. So let's simplify:

RED = Really don*t disturb
YELLOW = Be aware - call is ongoing - camera/mic might be on
OFF = I*m approachable without worries.

Based on a combination of “availability” and “activity” my suggestion would be:

IF availability = DoNotDisturb OR activity = Presenting THEN light=Red
ELSE IF activity = InACall OR activity = InAConferenceCall OR activity THEN light=Yellow
ELSE light=OFF (or Green)

This would allow to manually set within Teams the status as overwrite to "Do not disturb", all other settings would be set automatically.

**Comment by isaacrlevin** [comment]
Again, this is custom color configuration that does not map to Teams or Presence in general. There may be some things I can do to "control" what color gets sent based on certain scenarios, but then you need a management screen for those custom configurations. Will think on it.

**Comment by jdshkolnik** [comment]
I came here for this same topic. @isaacrlevin, when you say you only have access to the presence states on that page, can't you use the "app configured" value? Activity is clearly available in [this example](https://docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-beta&tabs=http):

```
HTTP/1.1 200 OK

{
    "value": [
        {
            "id": "dc74d9bb-6afe-433d-8eaa-e39d80d3a647",
            "availability": "Away",
            "activity": "BeRightBack"
        }
    ]
}
```

**Comment by isaacrlevin** [comment]
@jdshkolnik that is correct, there would need to be another management screen for Activity as well as Availability, and I am unsure how that would luck. If you want to start a PR, I am more than happy to work with you on it!

**Comment by jdshkolnik** [comment]
Fair enough. Let me think about what I'd want to see.
