### ISSUE TITLE
Activity: InAConferenceCall not available on custom API configuration

### ISSUE THREAD

**Issue by jeroenterheerdt** [isaacrlevin/presencelight#384]
**Describe the bug**
When I am in a call, my Activity state is not 'InACall', but instead it is 'InAConferenceCall' depending on if this is a 1:1 call or a call with more than 2 persons. I don't see a way to map that status on the 'Configure Custom API' tab of PresenceLight so I can have the correct API called for it.

**To Reproduce**
1. Start a call with at least one other party
2. See Activity is set to 'InAConferenceCall' in PresenceLight
3. Open 'Configure Custom API' tab in PresenceLight and see there is no option for 'InAConferenceCall'.

**Expected behavior**
I want to be able to map 'InAConferenceCall' to a custom API using the 'Configure Custom API' tab.

**Screenshots**

## Further details
- OS: Windows 10.
- PresenceLight App Type: Destop
- PresenceLight Build: Store
- PresenceLight Version" 4.2.12.0
- Did you clear settings.json?  No
- ASP.NET Core version N/A

**Comment by isaacrlevin** [comment]
Fixed in Nightly Build v4.2.20

**Comment by isaacrlevin** [comment]
Fixed in Store version
