### ISSUE TITLE
Unable to add Lifx Light

### ISSUE THREAD

**Issue by cconrado** [isaacrlevin/presencelight#394]
**Describe the bug**
on fresh install getting error when trying to link lifx light after getting token.

**To Reproduce**
Click get token under lifx tab then click get lights. It fails to get the light in the lifx account.

**Expected behavior**
Show my lifx light so I can configure settings

**Screenshots**
![image](https://user-images.githubusercontent.com/9168464/119891394-85c23500-befe-11eb-964a-e0d476e866e0.png)

## Further details
- OS: [Windows 10 21H1]
- PresenceLight App Type (Desktop)
- PresenceLight Build (Store)
- PresenceLight Version (4.2.12.0)
- Did you clear settings.json? yes, and reinstalled

**Comment by isaacrlevin** [comment]
Fixed in Nightly Build v4.2.20

**Comment by isaacrlevin** [comment]
Fixed in store version
