### ISSUE TITLE
Regular error being logged

### ISSUE THREAD

**Issue by sborg-ms** [isaacrlevin/presencelight#397]
I am seeing the following errors being logged a few times a minute

{"Timestamp":"2021-05-31T12:33:49.4923997+10:00","Level":"Information","MessageTemplate":"PresenceLight Running in Teams Mode - MainWindow.xaml:InteractWithLights Line: 788","Properties":{"SourceContext":"PresenceLight.MainWindow","LineNumber":788,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"InteractWithLights","Application":"PresenceLight"}}
{"Timestamp":"2021-05-31T12:33:50.9462100+10:00","Level":"Information","MessageTemplate":"Setting LIFX Light id:d073d540948e to 00FF00 - LifxService:SetColor Line: 171","Properties":{"SourceContext":"PresenceLight.Core.LIFXService","LineNumber":171,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\PresenceLight.Core\\Lights\\LifxServices\\LifxService.cs","MemberName":"SetColor","Application":"PresenceLight"}}
{"Timestamp":"2021-05-31T12:33:50.9480034+10:00","Level":"Error","MessageTemplate":"Error Occurred - MainWindow.xaml:SetColor Line: 418","Exception":"System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at PresenceLight.MainWindow.SetColor(String color, String activity) in D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs:line 422","Properties":{"SourceContext":"PresenceLight.MainWindow","LineNumber":418,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"SetColor","Application":"PresenceLight"}}

Any insights on this or how i can help get you more information on why etc?

**Comment by isaacrlevin** [comment]
Fixed in Nightly Build v4.2.20

**Comment by isaacrlevin** [comment]
Fixed in store version
