### ISSUE TITLE
After configuration the Hue API is never called

### ISSUE THREAD

**Issue by jasonjoh** [isaacrlevin/PresenceLight#4]
After configuring the app, it checks my presence from Graph as expected, but never calls the Hue API to set the color of my selected lamp. The `ddlLights.SelectedItem` is always null here:

```
if (!string.IsNullOrEmpty(Config.HueApiKey) && !string.IsNullOrEmpty(Config.HueIpAddress) && ddlLights.SelectedItem != null)
{
    await _hueService.SetColor(presence.Availability, ((Light)ddlLights.SelectedItem).Id);
}
```

Whenever I select a lamp in the dropdown, after clicking **Save** the dropdown goes back to being empty. The selected lamp never goes into the settings.json either.

I think it would be better to write the ID of the lamp into settings.json and use that value instead of relying on the SelectedItem dropdown.

**Comment by isaacrlevin** [comment]
Yea I need to fix the logic that populates that DL. will update when it is updated
