### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by RoelZ** [isaacrlevin/PresenceLight#40]
I'm sorry this is not a direct issue in your application, but rather a question concerning the authorization.

We really love the work you've done here and would like to use it now we work from home more often. As we work from an Active Directory Domain where we (as an client) have to submit the authorization request to the IT of our organization, the authorization is (sadly) a breaking issue for us. 

We understand the need of some of these requests and although the request for accessing certain data is explained, I was wondering what the need is for **Read presence information of all users in your organization**. Could you perhaps elaborate on this?

Also, is it possible to connect it in some other way? As we read that it could be done with **Windows 10 Theme**, but we are unsure how the application or usage should be done. 

Thank you so much.

**Comment by Shrekmachine** [comment]
> have to submit the authorization request to the IT of our organization
Wow!

**Comment by isaacrlevin** [comment]
I have removed the need for Presence.Read.All since I was not using it
