### ISSUE TITLE
Add single URI custom API variant to the Desktop app (as done for Worker app)

### ISSUE THREAD

**Issue by gooman-uk** [isaacrlevin/presencelight#450]
As for https://github.com/isaacrlevin/presencelight/pull/159 but in the Desktop app

Provides a one-stop interface with common home automation tools such as OpenHab, Home Assistant, NodeRed and others.

**Comment by isaacrlevin** [comment]
@gooman-uk maybe I am not following. Is this not sufficient?

![image](https://user-images.githubusercontent.com/8878502/134212145-e28c1407-03df-4e47-87b4-555161e052f3.png)

**Comment by isaacrlevin** [comment]
Won't fix as the MAUI version will be same as Worker
