### ISSUE TITLE
Can't find or register Hue Bridge

### ISSUE THREAD

**Issue by gooman-uk** [isaacrlevin/presencelight#455]
**Describe the bug**
Can't find or register Hue bridge

**To Reproduce**
1. On "Configure Philips Hue" tab, select "Connect to Philips Hue"
2. Start Wireshark capture
3. Enter address of Hue Bridge or any local IP address in "Hue Bridge IP Address"
4. "Register Bridge" becomes greyed out as soon as start typing in IP address
5. Click "Find Bridge"
6. "Hue Bridge IP Address" field is blanked
7. If clear and reselect "Connect to Philips Hue", and then "Register Bridge" without entering IP, after clicking "OK" on the sync popup, shows spinner permanently

**Expected behavior**
Not totally clear - existing Desktop app help docs don't match UI. I would expect that "Find Bridge" enabled the "Register Bridge" button which then registers successfullu.

## Further details
Windows 10
- PresenceLight App Type - Desktop
- PresenceLight Build - Store
- PresenceLight Version - 4.2.24.0
- Did you clear settings.json?  - yes
- ASP.NET Core version

**Comment by gooman-uk** [comment]
Solved. 

I'm using OpenHab's Hue emulation mode as my Hue Bridge. Turns out that OpenHab is picky about the API url, and won't respond to http://host/api - only to http://host/api/ (note the trailing slash). See https://www.openhab.org/addons/integrations/hueemulation/ for reference.

**Comment by matzeeg3** [comment]
how did you soleved it?
