### ISSUE TITLE
Weird sync behavior on 4.2.27.0 (nightly)

### ISSUE THREAD

**Issue by patrimal** [isaacrlevin/presencelight#467]
Two things happening after getting the new version today (9/22/2021 @ 13:13 - maybe it was the "unlucky" time?):
1. In the sign-in tab, I get a big question mark next to my status color (see below), instead of my photo, I think - it's been a while since I opened the app, since it worked flawlessly ;)
2. The app seems to be retrieving my status correctly when it first loads or after I sign-out and back in, but it won't stay in sync (I change my status in Teams and it's not reflected in the app).
![image](https://user-images.githubusercontent.com/8904973/134447294-7478709c-22e7-479e-9ef9-2da243117224.png)

**Comment by isaacrlevin** [comment]
Looks like there is a weird thing with the beta version of the Graph SDK. I ported to the release version and it is working now. New nightly by EOD should be fixed
