### ISSUE TITLE
Wiz Config Missing in one Computer

### ISSUE THREAD

**Issue by jackwhyin** [isaacrlevin/presencelight#469]
I had successfully set up the app on my desktop and connect it to a Philips Wiz light bulb, it worked immediately.

when I was trying to set this up on my laptop, thinking of making this the running environment. But strangely enough, there is no option to select a Wiz, it looks like the whole configure page is missing, clicking "Find Wiz Light" has no response.  Though I can see the options under other tabs, i.e. Philips Hue, Yeelight. 

Not sure if this is a hardware or software issue (FYI, my desktop is Windows 10 Enterprise, my laptop is Windows 10 Pro, same build/version though.)

![image](https://user-images.githubusercontent.com/75647404/134968546-3fa51f8e-8c0d-424f-ad0d-90c41c3190d6.png)

**Comment by isaacrlevin** [comment]
What version are you using? Just tried latest nightly and it worked for me

**Comment by jackwhyin** [comment]
just updated it to the said latest version, still no luck. 

I also tried it on a third laptop, another desktop, the same issue. Looking at the screenshot, it seems like the setting page is not fully loaded as it should where I can select an available light and adjust the color (again, settings for other tabs work)  And confusing enough, the bottom continues to say "Settings Updated".

**Comment by isaacrlevin** [comment]
Hrm. What version are you on? The "it works on this machine and not that one" is odd to say the least.

**Comment by jackwhyin** [comment]
I have tried both 4.2.240 installed from MS Store, and the Nightly version 4.2.31.0, no luck on the said computer.

I managed to get three other computers working, so this is specific to this laptop. The only difference I can think of is this laptop runs MS Teams, but I don't think it matters, just wanted to bring it up.

I will close this issue as it's machine specific
