### ISSUE TITLE
Idea: At least for Hue lights, do not disturb color is to close to busy color

### ISSUE THREAD

**Issue by maikelson** [isaacrlevin/PresenceLight#47]
Have you thought about using the approach [Embrava](https://cdn.shopify.com/s/files/1/0244/8061/files/busy_light_colors.png) uses for their status light (using purple-sh #B03CDE instead of a darker red #800000 like it is today?

Speaking from experience, the kids do not care 😀

**Comment by isaacrlevin** [comment]
Good call!
Fixed [here](https://github.com/isaacrlevin/PresenceLight/commit/c6774ab520131a8ea85e67a9867bd196cbd9dd1a)

**Comment by maikelson** [comment]
Dude you're fast!
