### ISSUE TITLE
Colorless Function For Hue Lights with no Color

### ISSUE THREAD

**Issue by weberr90** [isaacrlevin/presencelight#471]
Great piece of software! I've been trying to automate the process of turning on an extra set of Hue basic bulbs (no color options) in my office whenever I start a meeting in Teams. I currently have teams set to switch to "busy" whenever I start a call, and your application is registering the busy status correctly. However, when the light should just switch to "white" as I have it set to do, the logs show a continuous error:

<TABLE><TR><TD>09/29/2021 9:25:31 AM -05:00</TD><TD>Error</TD><TD>Error Occured Setting Color - RemoteHueService:SetColor Line: 273</TD></TR></TABLE>

I'm assuming this is because the lights I'm attempting to turn on can't register a specific color option, so I'm wondering if there is a way to make your software work with my lights, or if there is a functionality that could be added to allow for just basic On/Off functions based on status without a light color being required? 

Thanks!

**Comment by isaacrlevin** [comment]
You can change the status to "Off?" which turns the light off if that status is met.

![image](https://user-images.githubusercontent.com/8878502/135513595-54d28293-ab26-423c-a0fa-0c03e77411d4.png)

Please close if that gets you what you want

**Comment by weberr90** [comment]
That would definitely take care of the off function I'd want after the
meeting was over, but what I'm looking to do is have the light also go on
as soon as the meeting starts. Basically here is the desired flow:

Teams meeting starts > Teams updates my status to busy > PresenceLight
recognizes change to busy > Busy Status triggers light to turn on (no color
needed) > Meeting ends > Teams switches back to Available status >
Presencelight switches status to available > Light turns off (existing
functionality as you showed in your message).

Essentially I had bad lighting for video calls but I don't want that light
on all the time, so I wanted automation to turn it on during calls, and
then off again once the call was done.

Thanks for the quick response! Let me know if this is do-able and if so,
I'm happy to sponsor the additional development required to make it happen
:)

**Comment by isaacrlevin** [comment]
If you set Available to "Off" and Busy to "White", what happens?

**Comment by weberr90** [comment]
The light fails to turn on, and I get the error message in the log that I
provided on GitHub. It seems like that happened because I don't have a
colored bulb so the command for "white" fails to register correctly. Just
my guess though.

**Comment by isaacrlevin** [comment]
I don't have non-color lights, but this configuration works for me. 

- If my status is Available, lights turn off
- If I set my status to Busy, lights turn on and are white
- If I set my status back to Available, lights turn off


![image](https://user-images.githubusercontent.com/8878502/135525183-99cdcb78-413c-409e-992e-d33f58a282d9.png)

**Comment by weberr90** [comment]
That's how I've tried setting it up as well, and I tried ivory for the
color this time thinking that maybe white wasn't registered, so now I got
this log line repeating:
{"Timestamp":"2021-09-30T16:33:57.6767514-05:00","Level":"Information","MessageTemplate":"Setting
Hue Light 001788fffe658fcc to FFFFF0 - RemoteHueService:SetColor Line:
269","Properties":{"SourceContext":"PresenceLight.Core.RemoteHueService","LineNumber":269,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\PresenceLight.Core\\Lights\\RemoteHueServices\\RemoteHueService.cs","MemberName":"SetColor","Application":"PresenceLight"}}
{"Timestamp":"2021-09-30T16:33:58.6902062-05:00","Level":"Information","MessageTemplate":"PresenceLight
Running in Teams Mode - MainWindow.xaml:InteractWithLights Line:
774","Properties":{"SourceContext":"PresenceLight.MainWindow","LineNumber":774,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"InteractWithLights","Application":"PresenceLight"}}

Here is the configuration I used:
[image: image.png]

Unfortunately, the light doesn't come on at all, but it's fully functional
through the bridge since I have a chrome extension that allows me to
control the lights and that works well. So I guess the issue must just be
something to do with my lights not being able to register the color code
being sent, and instead it's just cycling over and over in an attempt to
get it to turn on.

**Comment by weberr90** [comment]
Nevermind, I JUST got it to work. So I unselected the "use remote API" and
just used the manual bridge IP. Now it's working great! Go figure... I
blame Philips Hue :)

**Comment by isaacrlevin** [comment]
Or my code could be better :)

**Comment by weberr90** [comment]
I think that is definitely the reason :) Thanks for your help!
