### ISSUE TITLE
Early timeout in authentication

### ISSUE THREAD

**Issue by Shrekmachine** [isaacrlevin/PresenceLight#48]
If I take like 1 min before signing in PL is accepting it but acts like there is no connection to Hue/Teams
Can the timeout be increased?

**Comment by isaacrlevin** [comment]
This is an issue on the MS Graph side. I could try to do a retry but it may cause other issues.

**Comment by isaacrlevin** [comment]
Sadly this is something I cannot resolve. Closing for now
