### ISSUE TITLE
Hue: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by beber-msft** [isaacrlevin/presencelight#481]
{"Timestamp":"2021-10-06T12:48:24.2108380+02:00","Level":"Information","MessageTemplate":"PresenceLight Running in Teams Mode - MainWindow.xaml:InteractWithLights Line: 774","Properties":{"SourceContext":"PresenceLight.MainWindow","LineNumber":774,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"InteractWithLights","Application":"PresenceLight"}}
{"Timestamp":"2021-10-06T12:48:24.2558384+02:00","Level":"Error","MessageTemplate":"Error Occurred Setting Color - HueService:SetColor Line: 144","Exception":"System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at System.Object.GetType()\r\n   at PresenceLight.Core.HueService.Handle(String presence, String lightId)\r\n   at PresenceLight.Core.HueService.SetColor(String availa

**Comment by isaacrlevin** [comment]
Is this the whole error? Also what does your settings file look like?

**Comment by beber-msft** [comment]
Hey Isaac, thanks for your support. this is the rest, sorry for the cutoff. Happy to share my settings file, is there a secure way todo so?

"String activity, String lightId)","Properties":{"SourceContext":"PresenceLight.Core.HueService","LineNumber":144,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\PresenceLight.Core\\Lights\\HueServices\\HueService.cs","MemberName":"SetColor","Application":"PresenceLight"}}"

**Comment by isaacrlevin** [comment]
Email it to isaac@isaaclevin.com

**Comment by isaacrlevin** [comment]
@beber-msft did you mail it?

**Comment by isaacrlevin** [comment]
@beber-msft going to close this. Reopen if you have the info
