### ISSUE TITLE
Wiz lights Brightness

### ISSUE THREAD

**Issue by jacyin** [isaacrlevin/presencelight#488]
I have the app running perfectly with a Wiz light, but the only issue is the brightness. The setting is working, I can change it to different % and and the brightness adjusts. But at a setting 50% or below, it is so dim and appears off completely; at 100%, it's still dim and is hard to see). I am not sure if there is a setting that I missed or any way to adjust it.

**Comment by UselessMnemonic** [comment]
> I have the app running perfectly with a Wiz light, but the only issue is the brightness. The setting is working, I can change it to different % and and the brightness adjusts. But at a setting 50% or below, it is so dim and appears off completely; at 100%, it's still dim and is hard to see). I am not sure if there is a setting that I missed or any way to adjust it.

Hello, friend! Could you kindly let me know which Wiz bulb (Model #) you're having troubles with?

**Comment by isaacrlevin** [comment]
@UselessMnemonic I can't speak for @jacyin but I have A19 bulb (the one you can get at Home Depot) and see this issue. Not sure if the connection mechanism is different

**Comment by jacyin** [comment]
> > I have the app running perfectly with a Wiz light, but the only issue is the brightness. The setting is working, I can change it to different % and and the brightness adjusts. But at a setting 50% or below, it is so dim and appears off completely; at 100%, it's still dim and is hard to see). I am not sure if there is a setting that I missed or any way to adjust it.
> 
> Hello, friend! Could you kindly let me know which Wiz bulb (Model #) you're having troubles with?

A19, the multi color one

**Comment by UselessMnemonic** [comment]
I tried to get my hands on one, but no luck. I did review my implementation with some different bulbs, to see if I could reproduce the issue, but I can't. When did you purchase the A19 bulbs? Might you have the box, or user manual still?

**Comment by UselessMnemonic** [comment]
Small update: I can reproduce the issue with some A19 bulbs by setting the bulb RGB/warm/cool values low, causing dimming to have little effect. Dimming on its own seems to work fine regardless.

**Comment by jacyin** [comment]
sorry for the late reply, and not sure if the information is still needed. I bought it a couple months ago, I didn't keep the box, but this is the one

![image](https://user-images.githubusercontent.com/92815688/140968985-2391ed95-b964-43dd-8c85-a99a31cdcb86.png)

**Comment by Tungsten66** [comment]
I just bought the same bulb and experiencing the dimming issue.  Any luck on resolving this?  Or any workaround?

**Comment by isaacrlevin** [comment]
It is an issue with the repo I call sadly
