### ISSUE TITLE
Sync with Accent Color: Brightness

### ISSUE THREAD

**Issue by hmrc87** [isaacrlevin/PresenceLight#49]
Hi, whenever I sync with my Accent Color and HueBridge the lamp never goes over around 30% brightness, although in the PresenceLight Settings the brightness is set to 100.

Brightness is 100 for Teams and manual Color settings.

When I override the brightness in my Hue-Control it is automatically resettent by PresenceLight to around 30-40%

Expected behaviour: PresenceLight Brightness control also effects brightness when set to "Sync with Windows Accent Color"

**Comment by cconrado** [comment]
I have lifx and its different. If I don't set it to 100 the brightness goes to 0%.

**Comment by isaacrlevin** [comment]
This is a bug, I just pushed a fix
https://github.com/isaacrlevin/PresenceLight/commit/b6857447fa308b30966a817b69c706b5b4fe8650
