### ISSUE TITLE
Configure Yeelight to work with Presencelight

### ISSUE THREAD

**Issue by beastmaster30** [isaacrlevin/presencelight#498]
Hi, I just bought the Yeelight smart Led Bulb 1S color(Model: YLDP13YL), i'm trying to configure with the app on windows and nothing appear in the box when i press <Find Yeelight's>. So how do i configure it?

**Comment by isaacrlevin** [comment]
I have that same model. Can you provide more information about your setup using the template?

**Comment by beastmaster30** [comment]
First i 
- have downloaded the app.
-  Sign in with my microsoft account and accept the authentication.
- Configure the Yeelight(reset method) so i can see it in my WiFi list 
- Go to the windows "Configure Yeelight" ; Press _Find Yeelight_ and nothing appear.

Is it the right Method?


![yeelightWindowsConfig](https://user-images.githubusercontent.com/90350597/140568475-d53b0005-055a-4434-b729-822c840dfcff.png)

**Comment by isaacrlevin** [comment]
This is fixed in the latest nightly 4.2.41
