### ISSUE TITLE
Enhancement: Only update Lifx color based on status change difference

### ISSUE THREAD

**Issue by andybcom** [isaacrlevin/PresenceLight#50]
I noticed that after every Graph poll you update the Lifx API even if the status hasnt changed. Was that intentional ?

I tried a quick code change that only updates the Lifx APi if the status has changed. If it has, update the  Lifx API and store the status in readiness for the next poll.

Less hits on the API ;-)

**Comment by isaacrlevin** [comment]
PRs are welcome ;)
