### ISSUE TITLE
Invalid RedirectURI for Docker Container

### ISSUE THREAD

**Issue by Xyolyp** [isaacrlevin/presencelight#502]
**Describe the bug**
Sadly currently the state of the documentation of how to deploy the docker container is quite the mess with a bunch of dead links (i.e. here https://hub.docker.com/r/isaaclevin/presencelight the link for "Cross Platform Blazor/Docker Version" points to a non-existing endpoint) and conflicting information. I was able to figure out that the ports should be 5001 for https (not 443) and 5000 for http (not 80) after digging around for a while. Sadly both 443 and 80 are mentioned somewhere as the ports inside the container.
It would be very nice if there was a dedicated step by step guide on how to get the container up and running without detours on how to handle ssl outside of docker and whatnot.
Finally I was able to get it somewhat running but when I try to get to my containers endpoint at https://<docker_hosts_hostname>:5001/ I get a message stating that the reply URL specified in the request does not match the reply URLs configured for the application: 'f8119f58-4523-44c1-ab72-b2e0c815bd6a'.

**To Reproduce**
1. deploy a container
2. configure the parameters as shown below and trust the certificate on the host level
3. configure for example https://localhost:5001 as the "AzureAd_RedirectHost" Env variable
4. visit https://<docker_hosts_hostname>:5001
5. See error

**Expected behavior**
I would like to be able to sign in to the application

**Screenshots**
referenced in "To Reproduce":
![image](https://user-images.githubusercontent.com/13995942/142276422-d816e291-ae00-45d5-bb95-03975cf5892b.png)

## Further details
- PresenceLight App Type Docker
- PresenceLight Build Latest
- PresenceLight Version Unable to reach application
- Did you clear settings.json? (C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json) blank docker deployment
- ASP.NET Core version 5.0.11

**Comment by isaacrlevin** [comment]
I agree the docs are confusing, apologies for that. For the redirect URI, it needs to be one of the below, as that are the ones that are registered in Azure AD
![image](https://user-images.githubusercontent.com/8878502/144298117-0b27be42-2e4c-4a7e-b823-d613cc914127.png)

If you can configure your container to run under one of those urls, let me know. I do have plans to update the docs as well.

**Comment by Xyolyp** [comment]
I now tried the following three values for the env var `AzureAd_RedirectHost`: `https://192.168.86.27:4433`, `http://192.168.86.27:4433` and `192.168.86.27:4433` but for all I get the message `AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'f8119f58-4523-44c1-ab72-b2e0c815bd6a'.` Am I even changing the correct setting?

**Comment by isaacrlevin** [comment]
can you remote into the container and update the value in the appsettings.json? I wonder if the mapping in the container is not happening

**Comment by Xyolyp** [comment]
The value inside the appsettings.json was "https://localhost:5001/" even though I configured "https://192.168.86.27:4433" as the value in the env var. I changed it to "https://192.168.86.27:4433" in the appsettings.json and tried it with and without restarting the container but I still get the same message.

**Comment by Xyolyp** [comment]
@isaacrlevin is there any further information I could provide you to solve this?

**Comment by isaacrlevin** [comment]
I have a version of this working, but it is in this branch
https://github.com/isaacrlevin/presencelight/tree/blazor-wpf

I have made a ton of changes to consolidate PresenceLight to run one app and I took the opportunity to fix the docker setup as well. If you want to test it for me, that would help.

if you checkout that branch, and docker build the default docker file and then run


```
 docker run --rm -it -p 5000:80 -p 5001:443 -e ASPNETCORE_URLS="https://+;http://+" -e ASPNETCORE_HTTPS_PORT=5001 -e ASPNETCORE_Kestrel__Certificates__Default__Password="presencelight" -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/presencelight.pfx -v $env:USERPROFILE\.aspnet\https:/https/ presencelightweb
```

You should have localhost:5001 work (you may have to go to 5000 and have the https redirect kick in initially)

Let me know

**Comment by isaacrlevin** [comment]
@Xyolyp get a chance to look at this?

**Comment by Xyolyp** [comment]
@isaacrlevin thank you for continously investing time and effort!
I just got around to it and sadly building the Dockerfile fails with the following output:
``` bash
jonathan@iobroker:~$ git clone https://github.com/isaacrlevin/presencelight.git
Cloning into 'presencelight'...
remote: Enumerating objects: 6698, done.
remote: Counting objects: 100% (527/527), done.
remote: Compressing objects: 100% (386/386), done.
remote: Total 6698 (delta 327), reused 238 (delta 138), pack-reused 6171
Receiving objects: 100% (6698/6698), 8.96 MiB | 6.66 MiB/s, done.
Resolving deltas: 100% (4816/4816), done.
jonathan@iobroker:~$ cd presencelight/
jonathan@iobroker:~/presencelight$ git checkout blazor-wpf
Branch 'blazor-wpf' set up to track remote branch 'blazor-wpf' from 'origin'.
Switched to a new branch 'blazor-wpf'
jonathan@iobroker:~/presencelight$ git pull
Already up to date.
jonathan@iobroker:~/presencelight$ docker build .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/jonathan/presencelight/Dockerfile: no such file or directory
jonathan@iobroker:~/presencelight$ sudo !!
sudo docker build .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/jonathan/presencelight/Dockerfile: no such file or directory
jonathan@iobroker:~/presencelight$ sudo docker build src/PresenceLight.Web/
Sending build context to Docker daemon  241.7kB
Step 1/18 : FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
 ---> 8d32e18b77a4
Step 2/18 : WORKDIR /app
 ---> Using cache
 ---> 7216957c8ac7
Step 3/18 : FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
 ---> e86d68dca8c7
Step 4/18 : WORKDIR /src
 ---> Using cache
 ---> 15aae41219b7
Step 5/18 : COPY ["PresenceLight.Web/PresenceLight.Web.csproj", "PresenceLight.Web/"]
COPY failed: file not found in build context or excluded by .dockerignore: stat PresenceLight.Web/PresenceLight.Web.csproj: file does not exist
```

**Comment by isaacrlevin** [comment]
sorry, should have been more clear, you need to point at the docker file

`
/presencelight/src/PresenceLight.Web/Dockerfile
`

**Comment by Xyolyp** [comment]
@isaacrlevin I recognized that you merged the branch and therefore decided to pull the latest docker image.
This sadly still fails with the same error as before when trying to login. But it was very easy to get it up and running with the command you posted in this thread. Now only the RedirectHost quirk has to be ironed out and I would like to assist you with writing the documentation once it's up and running. 
Maybe a sitenote worth mentioning as I'm unsure if it hinders the default config to work: my docker host is running headlessly and I'm using a different workstation to access the website hosted by the container.

**Comment by isaacrlevin** [comment]
Set an environment variable like this 

AzureAd__RedirectHost=some url

**Comment by isaacrlevin** [comment]
Notice 2 underscores

**Comment by isaacrlevin** [comment]
@Xyolyp this work for you?

**Comment by Xyolyp** [comment]
@isaacrlevin sorry for letting you wait. I didn't get it to work with any of the following values for the containers Env Var: `AzureAd__RedirectHost`:
`localhost:5001`, `https://localhost:5001`, `https://localhost:5001/`
I still get the same error message as I got at the beginning:
```
AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'f8119f58-4523-44c1-ab72-b2e0c815bd6a'.
```

**Comment by isaacrlevin** [comment]
Hold on, let me get a clear picture of what you are doing.

- You have PL running in a container on a remote device
- You are accessing it from some other machine
- You set the `AzureAd__RedirectHost` value to localhost and you get a failure
- Have you tried to set it to the IP of the remote machine? The IP HAS TO BE 192.168.86.27

**Comment by Xyolyp** [comment]
* I've deployed the PL container on a server in my local network with the hostname `iobroker` and the ip `192.168.55.33`.
* I'm accessing the webpage from my desktop workstation with the ip `192.168.55.51`
* I've set the `AzureAd__RedirectHost` to these exact values one after the other and tried accessing the page each time: `localhost:5001`, `https://localhost:5001`, `https://localhost:5001/`
* I didn't try to set any other values for the env var `AzureAd__RedirectHost`

**Comment by isaacrlevin** [comment]
That won't work. For PL to work, I have to register EVERY REDIRECTHOST in Azure AD, which is not feasible. I have one IP registered and it is 192.168.86.27. So if you want to run PL remotely, that has to be the IP of the machine it is running on, host or not.

I assume you can't update your IP address for that machine, but that is the only option at this point

**Comment by Xyolyp** [comment]
Thank you for the explaination. I'm unexperienced with custom docker networks: could the following setup work?

Create a custom docker network like this:
![image](https://user-images.githubusercontent.com/13995942/151453329-802e89e8-c928-40ba-b872-7d0cd53f7f2a.png)

Configure the container to use the custom network and set the ip to the value you specified:
![image](https://user-images.githubusercontent.com/13995942/151453513-d246b8aa-dfde-4f7b-8443-cdac6cd99dc6.png)

Set the env var like so:
![image](https://user-images.githubusercontent.com/13995942/151453443-9bef7e9f-cd10-4253-9d5f-dd34c233f76a.png)

**Comment by isaacrlevin** [comment]
You would need to update the host IP, aka the one on your network

**Comment by Xyolyp** [comment]
An idea just crossed my mind but I can't tell if it would be possible:
Could there be a tiny cloud service to which one get's redirected for authentication and this cloud service performs the request towards the azure api with it's own redirect uri. Once the user gets returned to the cloud service after successfully logging in he would need to be redirected from the cloud service to the local service again or something like this.
Would this comply with azure policies and requirements and could this be a feasable solution for the authentication issue?

**Comment by isaacrlevin** [comment]
I don't think so also who would build that service? I apologize that the current Docker configurations work for your environment but I am limited to how much support I can have for custom domain/IP for redirects. Are you not able to update the IP Address of the server on your local network to 192.168.86.27?

**Comment by isaacrlevin** [comment]
@Xyolyp is there anywhere to go with this issue? If not, can I close?

**Comment by anishsane** [comment]
I am also facing a similar issue.

I tried setting variables like AzureAd__RedirectHost and tried editing appsettings.json etc.
I want to be able to at least use a different host instead of just localhost. I am OK with port being 5001.

Is it possible to add a placeholder like
https://my-redirect-host:5001
And I can make my-redirect-host resolve to any local IP using /etc/hosts.

**Comment by isaacrlevin** [comment]
The Uri has to be localhost sadly
