### ISSUE TITLE
What is the bkp file in the Chocolatey package

### ISSUE THREAD

**Issue by gep13** [isaacrlevin/presencelight#525]
@isaacrlevin The following file is located within the Chocolatey package file:

https://github.com/isaacrlevin/presencelight/blob/main/.chocolatey/tools/ChocolateyUninstall.ps1.bkp

Is there a reason that this file is included?  Seems like that there is already a chocolateyInstall.ps1 file.

**Comment by isaacrlevin** [comment]
I think @steviecoaster created that when he did this

https://github.com/isaacrlevin/presencelight/commit/1dc5eb9e2bba813239ba8419d47e5d53f0363b1f

not sure if it was needed

**Comment by gep13** [comment]
Yip, don't think that is needed, and that file can be removed, or at the very least excluded from the nupkg.
