### ISSUE TITLE
Feature Request - Generic API calls

### ISSUE THREAD

**Issue by benlye** [isaacrlevin/PresenceLight#54]
Would it be possible to add a generic API option rather than using a specific vendor APIs?  That is, just a list of URI fields that the user can populate with specific URIs for each Teams status (or colour).

Background - I have a bunch of LED light strips with IR controllers.  I use an IR blaster device from [this project](https://github.com/mdhiggins/ESP8266-HTTP-IR-Blaster) to control them, and I can control that device locally with a REST API call.

E.g. to set the strip to red I GET this URI:
```
http://192.168.1.9:80/msg?code=FF9867:NEC:32&address=0xff&pass=blast&repeat=3&simple=1"
```

So if your PresenceLight app gave me a 'Custom API' page with set of fields where I can map each presence value to a URI, it could control my LED lights.

I imagine that this could be useful for a few people who want to use generic/custom hardware solutions (v2 of mine is to replace the IR strip controller with a customised ESP8266 and eliminate the IR).

PS. I did look at trying to implement this myself, but I haven't developed a modern Windows App before so I'm stuck at figuring out how to do that.  I've cloned your code but when I run it locally it doesn't behave properly - no login prompt and the UI doesn't work properly.

**Comment by benlye** [comment]
Had a thought - might be good to support the POST method as well as GET.

**Comment by isaacrlevin** [comment]
The issue here is that I don't have the HW to test. If you do, a PR would be very welcome

**Comment by benlye** [comment]
I don't think you would need the hardware.  Just have the app make the API call (probably wrapped in a try/catch so it didn't matter if there was no response) and leave it up to the user to do the rest.

I'll try and get the source to build and run properly here, but I'm not sure where to start - when I run the .exe I build the sign-in page is blank and the other pages have all the settings visible even though they are not enabled.  Any pointers?

**Comment by benlye** [comment]
Pretty much done and working well for me.  Will give you a PR over the weekend once I've been over it again.

![custom_api](https://user-images.githubusercontent.com/23322579/83928770-d2aa7a00-a788-11ea-8432-b9f11221322e.PNG)

**Comment by benlye** [comment]
I saw that you closed the PR without merging it. Not interested or something else?

**Comment by isaacrlevin** [comment]
Open a new PR against the main branch. I removed the master one

**Comment by benlye** [comment]
#56 opened.

**Comment by isaacrlevin** [comment]
merged
