### ISSUE TITLE
unable to install nightly build

### ISSUE THREAD

**Issue by tonyfitzs** [isaacrlevin/presencelight#554]
**Describe the bug**

when attempting to install the nightly build I keep getting the following error

App installation failed with error message: Deployment Add operation with target volume C: on Package 37828IsaacLevin.197278F15330A.Nightly_4.4.23.0_neutral_~_jvewcxq8vj8qt from:  (PresenceLight.Package_4.4.23.0_x64_arm64.appxbundle)  failed with error 0x80190193. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x80190193)

**To Reproduce**

uninstall curent version of presencalight
reboot pc
launch nightly build installer

**Expected behavior**
application installs succesfully
![2022-01-18_9-06-30](https://user-images.githubusercontent.com/34207637/149841922-24ff55fb-f42f-4bd4-ae7a-3cdccab5ed13.png)

**Screenshots**

## Further details
- PresenceLight App Type (Desktop, Blazor)
- PresenceLight Build (Nightly, Store, etc)
- PresenceLight Version (The # in About)
- Did you clear settings.json? (C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json
- ASP.NET Core version

**Comment by isaacrlevin** [comment]
Well I get a totally different error. You can download the previous version and install it here

https://presencelight.blob.core.windows.net/nightly/PresenceLight.Package_4.4.7.0_Test/PresenceLight.Package_4.4.7.0_x64.appxbundle

**Comment by isaacrlevin** [comment]
Also can you try this file?
https://presencelight.blob.core.windows.net/nightly/PresenceLight.Package_4.4.23.0_Test/PresenceLight.Package_4.4.23.0_x64_arm64.appxbundle

**Comment by isaacrlevin** [comment]
Try latest nightly @tonyfitzs

**Comment by isaacrlevin** [comment]
@tonyfitzs is this fixed?

**Comment by tonyfitzs** [comment]
Sorry, Isaac,

I have been busy with work. I will test it now

**Comment by tonyfitzs** [comment]
Hi Isaac,

The installer is now fixed, I don’t have time right now to test if there are any other issues with the API, which is what I use, but if there are, I will open another case
