### ISSUE TITLE
Would it be possible to add the 'Focusing' Activity Status?

### ISSUE THREAD

**Issue by RobSheppard1976** [isaacrlevin/presencelight#556]
**Is your feature request related to a problem? Please describe.**
The Activity Status of 'Focusing' isn't available as a custom API.

**Describe the solution you'd like**
Would it be possible to add the 'Focusing' Activity Status?

**Describe alternatives you've considered**
None, really. 

**Additional context**

"Focusing. Focus happens when the users schedule focus time in MyAnalytics/Insights in their calendars."

https://docs.microsoft.com/en-us/microsoftteams/presence-admins

Great work, by the way. I've tied this into my Home Assistant setup, to provide status to my family as I work from home. Fantastic application!

**Comment by isaacrlevin** [comment]
Sadly, I am limited by what granularity is available via the Graph API. There is no option for that....

https://docs.microsoft.com/en-us/graph/api/resources/presence
