### ISSUE TITLE
Yeelight are not shown

### ISSUE THREAD

**Issue by martin-asencio** [isaacrlevin/presencelight#570]
When trying to setup yeelight on the app the list shows empty. 
I can control the yeelight from yeelight mobile app and can see their IP on my router. 
it was working a couple of days back and suddenly it stopped working.

## Further details
- OS: windows 10
- PresenceLight App Type Desktop
- PresenceLight Build: Store
- PresenceLight Version 4.4.23.0
- Did you clear settings.json? Yes
![Screenshot 2022-02-04 173803](https://user-images.githubusercontent.com/92177792/152613114-6b997afe-cf87-48db-81f9-d9c149078979.png)

**Comment by isaacrlevin** [comment]
Do you have the same problem with the Nightly version?
https://presencelight.blob.core.windows.net/nightly/index.html

**Comment by isaacrlevin** [comment]
@martin-asencio 

Store version is updated.... please take a look

**Comment by isaacrlevin** [comment]
@martin-asencio closing issue, please reopen if problem persists

**Comment by martin-asencio** [comment]
Isaac, sorry I have been busy, but I installed the new version from the Microsoft store and still if cannot find the yeelights.

**Comment by isaacrlevin** [comment]
What model of lights do you have? Tested finr with the version I have

**Comment by martin-asencio** [comment]
YEELIGHT Alexa Light Bulb, Smart Light Bulbs, Smart Bulbs That Work with Alexa & Google Home, Razer Chroma, A19 RGBW LED WiFi Light Bulbs No Hub Required, 60W Equivalent 900LM CRI>80 https://smile.amazon.com/dp/B091F8MBC1/ref=cm_sw_r_apan_glt_i_V219GNADKWF9HX786N41?_encoding=UTF8&psc=1

Martin Asencio
________________________________

**Comment by isaacrlevin** [comment]
Can you please take a screenshot of the device info in the Yeelight app?

**Comment by martin-asencio** [comment]
Reinstalled and it is working

Martin Asencio
________________________________
