### ISSUE TITLE
CPU Usage often times 10-11 %

### ISSUE THREAD

**Issue by DevSecNinja** [isaacrlevin/presencelight#571]
**Describe the bug**
The CPU usage is often times around 10-12 % and 200 MB memory. Doesn't matter if the GUI is closed. After killing the app and reopening it, it stays around that. Is there a way to reduce the CPU usage?

**To Reproduce**
Steps to reproduce the behavior: open app with window or in tray only

**Expected behavior**
I would expect the CPU to be <1 % when the app is closed to tray.

**Screenshots**
![image](https://user-images.githubusercontent.com/14926452/153009199-d51c2575-0f3c-49c9-b936-e802f058f63b.png)

## Further details
- OS: [e.g. iOS] Windows 11
- PresenceLight App Type (Desktop, Blazor) Desktop
- PresenceLight Build (Nightly, Store, etc) Store
- PresenceLight Version (The # in About) 5.0.2
- Did you clear settings.json? (C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json
- ASP.NET Core version

Please let me know if this is as expected, but it seems to be a little high. Maybe there is a way to reduce the CPU usage when the app is minimized to tray.

Thanks for this great app! It was very easy to setup!

**Comment by isaacrlevin** [comment]
I see a similar thing so I guess this is expected for now. I wonder if it has to do with logging. I will take a look

**Comment by jeroenterheerdt** [comment]
I have seen 25% CPU usage during the day. I have the app configured to call webhooks (same setup as @DevSecNinja) and refresh setting is 5 sec. I played around with refresh settings a bit, even setting it to 50 sec, but usage was still around 25%. If it's indeed related to logging, can you please make a setting that would allow people to turn on logging and have it turned off by default? I don't think you need to collect logging once you have everything set up and working.

**Comment by jeroenterheerdt** [comment]
interesting - I don't know of any app that collects this level of detail logs unless the user takes so specific action. Anyway, we can agree to disagree :)

**Comment by isaacrlevin** [comment]
@jeroenterheerdt @DevSecNinja @QJJK42 @AndreasSemmelmann please see if this is resolved in the latest nightly

**Comment by jeroenterheerdt** [comment]
I tried the nightly, it's now at about 2% only when updating the status, otherwise it's < 0.5%. So, looks way better! Thanks!

**Comment by DevSecNinja** [comment]
Thank you @isaacrlevin! Seems to work fine here as well. Really appreciate your help!

**Comment by isaacrlevin** [comment]
Have you tried restarting the PC?

**Comment by AndreasSemmelmann** [comment]
Hi Isaac. I have removed the app and shutdown my device. After this restart I have installed the base package via the store again and then I have tried to update without success. What else could I try?
My OS language is EN but my keyboard layout is DE. But this should not be a problem.(?)
