### ISSUE TITLE
Mask the Basic Auth Password on the Custom API Setup page

### ISSUE THREAD

**Issue by denniswham** [isaacrlevin/presencelight#578]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Mask the password in the Basic Auth Password field on the Custom API Setup page. Now it is clearly visible.
(In short, make it a true password field)

**Describe alternatives you've considered**
Ensure not to display the page when others can see it

**Additional context**
This is what is could be like:
![image](https://user-images.githubusercontent.com/43110823/153247514-988bd739-e9e7-4eee-96de-e8e1314ab47c.png)

**Comment by isaacrlevin** [comment]
@denniswham this is fixed in the latest nightly

**Comment by isaacrlevin** [comment]
Store version updated
