### ISSUE TITLE
High CPU

### ISSUE THREAD

**Issue by QJJK42** [isaacrlevin/presencelight#579]
**Describe the bug**
High CPU usage for a background APP.  Using between 29-34% all of the time

**To Reproduce**
Happens all the time

**Expected behavior**
I would expect lower CPU use

**Screenshots**
![image](https://user-images.githubusercontent.com/99382437/153341776-c6f0d0d9-c6ff-4b04-9b6b-92cc89ba9917.png)

## Further details
- OS: Windows 11
- PresenceLight App Type (Desktop, Blazor)
- PresenceLight Build (Nightly, Store, etc)
- PresenceLight Version (The # in About) 5.0.4
- Did you clear settings.json?  Yes (C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json
- ASP.NET Core version

**Comment by AndreasSemmelmann** [comment]
Jump on this topic. I have the same issue. Same version of the app is installed. Probably related with the las Windows updates. not sure.
