### ISSUE TITLE
Enhancement: Stop/Pause updating my status

### ISSUE THREAD

**Issue by drhaas** [isaacrlevin/PresenceLight#58]
At some points in the day I would like to set my lamp free of the reigns of my Teams presence. Maybe we could add a right click action to pause updates? Even nicer if we could time the pause.

Thanks!

**Comment by bjeans** [comment]
Is there a way that you could specify "working hours" and only have the lights sync during that time?  Sometime I leave my laptop on and forget presenceLight is running and then the family changes the colour of the light and it changes right back immediately.  Perhaps pulling working hours from Graph - https://docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&tabs=http#example-3

**Comment by isaacrlevin** [comment]
This is fixed in version 2.0.67. It is deploying to everything now
