### ISSUE TITLE
Tuya

### ISSUE THREAD

**Issue by tboneco** [isaacrlevin/presencelight#581]
**Is your feature request related to a problem? Please describe.**
Not a problem

**Describe the solution you'd like**
I use lightbulbs that use Tuya for their app.  Was hoping you could look at adding that API to your application.
https://www.tuya.com/

**Describe alternatives you've considered**
Haven't looked at other options as all my bulbs use Tuya.

**Additional context**
Thanks for creating this app!

**Comment by isaacrlevin** [comment]
I don't have access to a Tuya light, would love to see a PR to add this functionality.

**Comment by anishsane** [comment]
I want this too.
I am not versed with C# and thus, even if I implement the change, I don't have a way to compile it.

I have a working python library - https://pypi.org/project/tinytuya/.
I will try if I can convert it to CPP or c# for someone to continue.

**Comment by isaacrlevin** [comment]
Closing this, @anishsane feel free to open a PR for the lights you are using.
