### ISSUE TITLE
App installation failed with error message: Merge failure for shared merged PRI file : error 0x80070490

### ISSUE THREAD

**Issue by AndreasSemmelmann** [isaacrlevin/presencelight#582]
I am not able to update my installation. I have uninstalled the base package and reinstalled it from the app store. Everytime I run the nightly app package I receive the following error:
App installation failed with error message: Merge failure for shared merged PRI file : error 0x80070490 : Cannot register the 37828IsaacLevin.197278F15330A.Nightly_5.0.6.0_x64__jvewcxq8vj8qt package because there was a merge failure with the following file: C:\Program Files\WindowsApps\37828IsaacLevin.197278F15330A.Nightly_5.0.6.0_neutral_split.language-de_jvewcxq8vj8qt\resources.pri (0x80070490)

0x80070490: E_ELEMENT_NOT_FOUND. Could it be that we have here a code page/language file missing? --> "language-de"?

**Comment by isaacrlevin** [comment]
Did you try a system restart?

**Comment by AndreasSemmelmann** [comment]
Yes. I have tried a restart. I have also removed the app and reinstalled the basic one from the store and tried to update. Same error so far.

**Comment by isaacrlevin** [comment]
What Processer architecture do you have? I am not an expert in App packaging but it was tested on x64, x86 and ARM.

**Comment by isaacrlevin** [comment]
@AndreasSemmelmann any updates?

**Comment by AndreasSemmelmann** [comment]
Hi @isaacrlevin 
Sorry. missed to reply. I have a x64 (Surface Book 2 with Windows 11).

**Comment by isaacrlevin** [comment]
Are you able to install the nightly version?

**Comment by AndreasSemmelmann** [comment]
Hi Isaac,

same issue with the nightly (5.0.19.0):
App installation failed with error message: Merge failure for shared merged PRI file : error 0x80070490 : Cannot register the 37828IsaacLevin.197278F15330A.Nightly_5.0.19.0_x64__jvewcxq8vj8qt package because there was a merge failure with the following file: C:\Program Files\WindowsApps\37828IsaacLevin.197278F15330A.Nightly_5.0.19.0_neutral_split.language-de_jvewcxq8vj8qt\resources.pri (0x80070490)

**Comment by isaacrlevin** [comment]
Does the standalone version work? You can get it from the Releases area of the repo

**Comment by AndreasSemmelmann** [comment]
I have successfully installed the desktop version from the GitHub source. It would be ok for me to close the issue.

**Comment by isaacrlevin** [comment]
Ok, apologies that the store version is not working.
