### ISSUE TITLE
Localhost Redirect after Teams Login not working

### ISSUE THREAD

**Issue by danielsiegl** [isaacrlevin/presencelight#583]
**Describe the bug**
I upgraded today - the old version worked - had to delete all settings to be able to run the application. Now I can't login to Teams.

![Capture](https://user-images.githubusercontent.com/41949368/153772471-9a627855-f945-441a-a592-8e6277660476.PNG)

I can't stop Kaspersky - could a virus scanner cause that problem?

**Comment by danielsiegl** [comment]
I was able to shutdown Kaspersky than the login seems to work!
But still I have a wheel of death on the Teams Screen.
![Capturewheelofdeath](https://user-images.githubusercontent.com/41949368/153823668-689592b5-5000-44f6-8cb6-8f691eb184f0.PNG)

**Comment by isaacrlevin** [comment]
Please provide your settings file

**Comment by isaacrlevin** [comment]
Can you add the following to your settings file? Add between `IconType` and `LightSettings`

```
"AADSettings":  {
   "ClientId":  "f8119f58-4523-44c1-ab72-b2e0c815bd6a",
   "Instance":  "https://login.microsoftonline.com/",
   "RedirectUri":  "http://localhost"
},
```

**Comment by isaacrlevin** [comment]
@danielsiegl 
Please try the latest nightly and tell me if you have any issues
https://presencelight.blob.core.windows.net/nightly/index.html

**Comment by isaacrlevin** [comment]
@danielsiegl any updates?

**Comment by danielsiegl** [comment]
Hi,
I was on ski trip - the nightly fails to install!

"App installation failed with error message: Merge failure for shared merged PRI file : error 0x80070490 : Cannot register the 37828IsaacLevin.197278F15330A.Nightly_5.0.17.0_x64__jvewcxq8vj8qt package because there was a merge failure with the following file: C:\Program Files\WindowsApps\37828IsaacLevin.197278F15330A.Nightly_5.0.17.0_neutral_split.language-de_jvewcxq8vj8qt\resources.pri (0x80070490)"

Cheers
Daniel
![Capture-Install Error](https://user-images.githubusercontent.com/41949368/154818699-9669ad56-9404-459f-af8f-a161705b43d4.PNG)

**Comment by isaacrlevin** [comment]
Try restarting your pc

**Comment by danielsiegl** [comment]
Same result:
"App installation failed with error message: Merge failure for shared merged PRI file: Fehler 0x80070490 : Das Paket "37828IsaacLevin.197278F15330A.Nightly_5.0.17.0_x64__jvewcxq8vj8qt" kann aufgrund eines Fehlers beim Zusammenführen bei der folgenden Datei nicht registriert werden: C:\Program Files\WindowsApps\37828IsaacLevin.197278F15330A.Nightly_5.0.17.0_neutral_split.language-de_jvewcxq8vj8qt\resources.pri. (0x80070490)"

**Comment by isaacrlevin** [comment]
If this is still happening, try the nightly. If the nightly doesn't work, try the version from the release page of this repo. If the the github version works, try doing a wsreset. These issues typically go away with reboots

**Comment by isaacrlevin** [comment]
@danielsiegl any update here?

**Comment by isaacrlevin** [comment]
Closing Issue
