### ISSUE TITLE
Error getting content

### ISSUE THREAD

**Issue by racarmichael** [isaacrlevin/presencelight#585]
### Discussed in https://github.com/isaacrlevin/presencelight/discussions/584

<div type='discussions-op-text'>

<sup>Originally posted by **racarmichael** February 14, 2022</sup>
Hello!
I'm getting the following error on the Windows Desktop App Live Logging:
**Error Occured Getting Batch Content from Graph Api - GraphWrapper:GetBatchContent Line: 106**
...which I guess means that PresenceLight is having trouble accessing the computers Teams Status; any idea how I can rectify this?
Sincere regards,
Ryan</div>

**Comment by racarmichael** [comment]
Please see my settings file at https://drive.google.com/file/d/1AeWqpl54d-wOcgnL0fHz-7IQC_aG6spG/view?usp=drivesdk

I am no longer getting the error, and the notification icon is changing correctly, but my POST request do not appear to send...

**Comment by isaacrlevin** [comment]
Can you add the following to your settings file? Add between `IconType` and `LightSettings`

```
"AADSettings":  {
   "ClientId":  "f8119f58-4523-44c1-ab72-b2e0c815bd6a",
   "Instance":  "https://login.microsoftonline.com/",
   "RedirectUri":  "http://localhost"
},
```

**Comment by racarmichael** [comment]
Unfortunately the issue remains... Any other ideas?

**Comment by isaacrlevin** [comment]
Have you tried latest nightly?

**Comment by racarmichael** [comment]
I just tried nightly now, and both with and without the line you told me to add the result was the safe

**Comment by isaacrlevin** [comment]
@racarmichael 
Please try the latest nightly and tell me if you still see this.

**Comment by isaacrlevin** [comment]
@racarmichael any update?

**Comment by racarmichael** [comment]
Sorry been busy.
Still not working with latest nightly, but do get the following errors in the log now:
![20220220_200715](https://user-images.githubusercontent.com/22497856/154835800-84dc0936-a3ce-4ed0-9f61-f3f93661750a.jpg)

**Comment by racarmichael** [comment]
> What about the standalone version from Releases page?
> 
> https://github.com/isaacrlevin/presencelight/releases/tag/Desktop-v5.0.9

I also tried the Standalone but result was the same...

**Comment by isaacrlevin** [comment]
Do you have a profile picture in O365?

Sent from Surface Duo
________________________________

**Comment by racarmichael** [comment]
No; is this required for the lights to function?

**Comment by isaacrlevin** [comment]
There may be a bug if you don't. If you set one does everything work?

**Comment by racarmichael** [comment]
Unfortunately this function is managed by my IT  department so I am unable to add a profile picture...

**Comment by isaacrlevin** [comment]
Please try the latest nightly

**Comment by isaacrlevin** [comment]
@racarmichael are you still having an issue with latest nightly?

**Comment by racarmichael** [comment]
That got it working! Great job, thanks mate.
