### ISSUE TITLE
Getting Graph Data: Profle, Image, Presence - GraphWrapper:GetBatchContent Line: 86

### ISSUE THREAD

**Issue by tomknevitt** [isaacrlevin/presencelight#586]
Previously working on version 4, updated to version 5.0.4 it will no load teams status. 

Tried reinstalling and removing appdata. It asks to login into account, reports sucessful. But the teams status just has a loading icon and the log shows Getting Graph Data: Profle, Image, Presence - GraphWrapper:GetBatchContent Line: 86

**Comment by isaacrlevin** [comment]
Please provide your settings file

**Comment by isaacrlevin** [comment]
Can you add the following to your settings file? Add between `IconType` and `LightSettings`

```
"AADSettings":  {
   "ClientId":  "f8119f58-4523-44c1-ab72-b2e0c815bd6a",
   "Instance":  "https://login.microsoftonline.com/",
   "RedirectUri":  "http://localhost"
},
```

**Comment by tomknevitt** [comment]
Tired adding the text to settings file, however each time the app was restarted it was removed. 
I have attached the settings file (removed LifX Secret
[C__Users_tomk_AppData_Local_Packages_37828IsaacLevin.197278F15330A_zfcjmmeb3zeaa_LocalState_settings (1).json.txt](https://github.com/isaacrlevin/presencelight/files/8067392/C__Users_tomk_AppData_Local_Packages_37828IsaacLevin.197278F15330A_zfcjmmeb3zeaa_LocalState_settings.1.json.txt)
)

**Comment by tomknevitt** [comment]
Also tried V5.0.9, same issue

**Comment by isaacrlevin** [comment]
What about the standalone version from Releases page?

https://github.com/isaacrlevin/presencelight/releases/tag/Desktop-v5.0.9

**Comment by isaacrlevin** [comment]
Or current Nightly
https://presencelight.blob.core.windows.net/nightly/index.html

**Comment by isaacrlevin** [comment]
@tomknevitt 
Please try the latest nightly and tell me if you have any issues
https://presencelight.blob.core.windows.net/nightly/index.html

**Comment by tomknevitt** [comment]
I have now tried V5.0.11 from app store, V5.0.11 from GitHub, V5.0.13.0 Nightly.

On latest versions it no longer asks me to sign in. Even when i delete settings file.

I also installed the latest V4 to ensure it was not another factor and this works perfectly.

**Comment by isaacrlevin** [comment]
Do you have access to the UI at all (like the Logs area) or is the screen just blank. Might be helpful to see the issue

**Comment by isaacrlevin** [comment]
Take a look at this issue
https://github.com/isaacrlevin/presencelight/issues/589

**Comment by isaacrlevin** [comment]
Can you take a screenshot of what you are seeing?

**Comment by isaacrlevin** [comment]
@tomknevitt any updates?

**Comment by tomknevitt** [comment]
Apologies, I was out the office. I have updated to V5.0.19 and happy to report the issue is now resolved. Thank you @isaacrlevin
