### ISSUE TITLE
Custom API setting screen reverts changes before they can be saved

### ISSUE THREAD

**Issue by CamSoper** [isaacrlevin/presencelight#588]
Custom API setting screen reverts changes before they can be saved. I was able to set my custom API URLs by editing the settings.json file directly.

Repro:

1. Go to Custom API settings screen
2. Attempt to enter a URL and save
3. Note the UI reverts changes before they can be saved. I suspect it's some kind of Blazor update thing.

![bad-custom-ui](https://user-images.githubusercontent.com/137648/153966090-26f6911c-11a2-438f-b1ab-03eafb97cbcf.gif)

**Comment by isaacrlevin** [comment]
Does the currently nightly version have this issue?

https://presencelight.blob.core.windows.net/nightly/index.html

**Comment by CamSoper** [comment]
I'll check tomorrow.

**Comment by joeljeffery** [comment]
Confirmed with both store build and nightly build :)

**Comment by CamSoper** [comment]
Yep, confirmed for both.

**Comment by joeljeffery** [comment]
I confirm the same behaviour as reported by @CamSoper in the ticket in both versions. 🙂

**Comment by isaacrlevin** [comment]
Just updated Nightly, test that please

@CamSoper @joeljeffery

**Comment by isaacrlevin** [comment]
Waiting on @CamSoper

**Comment by CamSoper** [comment]
Looks good to me too
