### ISSUE TITLE
Still not working after following #589

### ISSUE THREAD

**Issue by thor1466** [isaacrlevin/presencelight#594]
Please help. I'm following guide 589 but still got blank site. Here is my setting:

**Comment by isaacrlevin** [comment]
@thor1466 
I removed your settings file. 

Please try the latest nightly and tell me if you have any issues
https://presencelight.blob.core.windows.net/nightly/index.html

**Comment by mcaden** [comment]
Not sure if this is the same issue as OP but I'm having the issue and here's my error. It looks like it expects me to have a profile photo when I don't.

```
{"Timestamp":"2022-02-18T15:00:30.6482029-06:00","Level":"Information","MessageTemplate":"Getting Graph Data: Profle, Image, Presence - GraphWrapper:GetBatchContent Line: 86","Properties":{"SourceContext":"PresenceLight.Core.GraphWrapper","LineNumber":86,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\PresenceLight.Core\\GraphServices\\GraphWrapper.cs","MemberName":"GetBatchContent","Application":"PresenceLight"}}
{"Timestamp":"2022-02-18T15:00:36.9122182-06:00","Level":"Error","MessageTemplate":"Error occured Getting Photo - MainWindow.xaml:GetPhoto Line: 366","Exception":"Status Code: NotFound\r\nMicrosoft.Graph.ServiceException: Code: ImageNotFound\r\nMessage: Exception of type 'Microsoft.Fast.Profile.Core.Exception.ImageNotFoundException' was thrown.\r\nInner error:\r\n\tAdditionalData:\r\n\tdate: 2022-02-18T21:00:36\r\n\trequest-id: ...\r\n\tclient-request-id: ...\r\nClientRequestId: ...\r\n\r\n   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)\r\n   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)\r\n   at Microsoft.Graph.BaseRequest.SendStreamRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)\r\n   at PresenceLight.Core.GraphWrapper.<>c__DisplayClass10_0.<<GetPhoto>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)\r\n   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)\r\n   at PresenceLight.Core.GraphWrapper.GetPhoto(CancellationToken token)\r\n   at PresenceLight.Core.GraphServices.GetPhotoHandler.Handle(GetPhotoCommand command, CancellationToken cancellationToken)\r\n   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at PresenceLight.MainWindow.GetPhoto() in D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs:line 369","Properties":{"SourceContext":"PresenceLight.MainWindow","LineNumber":366,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"GetPhoto","Application":"PresenceLight"}}
{"Timestamp":"2022-02-18T15:00:36.9153214-06:00","Level":"Error","MessageTemplate":"Error occured interacting with lights - MainWindow.xaml:InteractWithLights Line: 599","Exception":"System.ArgumentNullException: Value cannot be null. (Parameter 'inArray')\r\n   at System.Convert.ToBase64String(Byte[] inArray)\r\n   at PresenceLight.MainWindow.InteractWithLights() in D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs:line 602","Properties":{"SourceContext":"PresenceLight.MainWindow","LineNumber":599,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"InteractWithLights","Application":"PresenceLight"}}
```

**Comment by thor1466** [comment]
> Not sure if this is the same issue as OP but I'm having the issue and here's my error. It looks like it expects me to have a profile photo when I don't.
> 
> ```
> {"Timestamp":"2022-02-18T15:00:30.6482029-06:00","Level":"Information","MessageTemplate":"Getting Graph Data: Profle, Image, Presence - GraphWrapper:GetBatchContent Line: 86","Properties":{"SourceContext":"PresenceLight.Core.GraphWrapper","LineNumber":86,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\PresenceLight.Core\\GraphServices\\GraphWrapper.cs","MemberName":"GetBatchContent","Application":"PresenceLight"}}
> {"Timestamp":"2022-02-18T15:00:36.9122182-06:00","Level":"Error","MessageTemplate":"Error occured Getting Photo - MainWindow.xaml:GetPhoto Line: 366","Exception":"Status Code: NotFound\r\nMicrosoft.Graph.ServiceException: Code: ImageNotFound\r\nMessage: Exception of type 'Microsoft.Fast.Profile.Core.Exception.ImageNotFoundException' was thrown.\r\nInner error:\r\n\tAdditionalData:\r\n\tdate: 2022-02-18T21:00:36\r\n\trequest-id: ...\r\n\tclient-request-id: ...\r\nClientRequestId: ...\r\n\r\n   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)\r\n   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)\r\n   at Microsoft.Graph.BaseRequest.SendStreamRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)\r\n   at PresenceLight.Core.GraphWrapper.<>c__DisplayClass10_0.<<GetPhoto>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)\r\n   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)\r\n   at PresenceLight.Core.GraphWrapper.GetPhoto(CancellationToken token)\r\n   at PresenceLight.Core.GraphServices.GetPhotoHandler.Handle(GetPhotoCommand command, CancellationToken cancellationToken)\r\n   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at PresenceLight.MainWindow.GetPhoto() in D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs:line 369","Properties":{"SourceContext":"PresenceLight.MainWindow","LineNumber":366,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"GetPhoto","Application":"PresenceLight"}}
> {"Timestamp":"2022-02-18T15:00:36.9153214-06:00","Level":"Error","MessageTemplate":"Error occured interacting with lights - MainWindow.xaml:InteractWithLights Line: 599","Exception":"System.ArgumentNullException: Value cannot be null. (Parameter 'inArray')\r\n   at System.Convert.ToBase64String(Byte[] inArray)\r\n   at PresenceLight.MainWindow.InteractWithLights() in D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs:line 602","Properties":{"SourceContext":"PresenceLight.MainWindow","LineNumber":599,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"InteractWithLights","Application":"PresenceLight"}}
> ```

Had the same problem, you need to make a profilepicture, then it worked out for me :-)
