### ISSUE TITLE
Can't connect to Hue bridge when not entering IP address (i.e. when relying on bridge discovery)

### ISSUE THREAD

**Issue by DamianEdwards** [isaacrlevin/presencelight#596]
**Describe the bug**
When attempting to configure Hue lights, am unable to setup the Hue bridge unless I explicitly enter the IP address.

**To Reproduce**
1. Go to Configure Philips Hue lights screen
2. Click on 'Register Bridge' button
3. When modal dialog is shown instructing to hit the "sync" button on Hue bridge, hit the sync button, then click the "Ok" button
4. See error saying API key couldn't be created

**Expected behavior**
That Hue bridge can be setup without having to enter the IP address.

**Screenshots**
<img width="889" alt="image" src="https://user-images.githubusercontent.com/249088/154332176-74d79a88-2265-4ed9-895f-ba5038279d52.png">

## Further details
- OS: Windows 11
- PresenceLight App Type: Desktop
- PresenceLight Build: Store
- PresenceLight Version: 5.0.11
- Did you clear settings.json?: Yes

**Comment by isaacrlevin** [comment]
@DamianEdwards this was actually a miss on my side. When I ported over to use the Razor Components, I didn't port over the "Find Bridge" functionality. I just added it to the Nightly build.

**Comment by isaacrlevin** [comment]
![image](https://user-images.githubusercontent.com/8878502/154357907-5f676161-65dc-4101-bd60-865ba47bd2ee.png)

**Comment by isaacrlevin** [comment]
This is now in the Windows Store
