### ISSUE TITLE
"Start Minimize" missing in 5.0.11.x

### ISSUE THREAD

**Issue by Shrekmachine** [isaacrlevin/presencelight#597]
![image](https://user-images.githubusercontent.com/8019511/154431713-6a42ed65-86ef-4c9c-a465-80690b53e723.png)
and in the settings unfortunately it is set like this:
```
  "SendDiagnosticData": true,
  "StartMinimized": false,
```

Sending data without allowance.
The good news. If you can handle notepad, it can be set without UI like you want.

**Comment by isaacrlevin** [comment]
This is fixed in Nightly

**Comment by isaacrlevin** [comment]
In Store Version
