### ISSUE TITLE
Status is showing offline even though i'm online

### ISSUE THREAD

**Issue by chrsmrtn-** [isaacrlevin/presencelight#609]
**Describe the bug**
The app is showing that i'm offline even thought i'm online.

**To Reproduce**
1. Setup app and login to get your status.
2. Set app to auto launch on boot up
3. Shutdown computer
4. Boot up computer

**Expected behavior**
After reboot of the app shows your correct online status

**Work Around**
Signing out and back in again resolves the issue

**Screenshots**
![image](https://user-images.githubusercontent.com/5657979/156401668-eecede36-433b-45b4-af8a-763f89e4f607.png)

## Further details
- OS: Windows 10
![image](https://user-images.githubusercontent.com/5657979/156401743-ab988b31-e4cc-4e40-b4cd-4cdc92044980.png)

- PresenceLight App Type: Desktop
- PresenceLight Build: Store
- PresenceLight Version: 5.0.19
- Did you clear settings.json: yes
- ASP.NET Core version: 5.0.405

Logs for today
[log-2022030209.zip](https://github.com/isaacrlevin/presencelight/files/8171118/log-2022030209.zip)

**Comment by chrsmrtn-** [comment]
signing out and back in again resolves the issue

**Comment by isaacrlevin** [comment]
This might be a UI refreshing issue. I am working on re-writing the UI and might ask you to try the latest nightly to see if you still have the issue. Stay tuned!

**Comment by isaacrlevin** [comment]
Give the latest nightly a try and see if the issue persists
https://presencelight.blob.core.windows.net/nightly/index.html

**Comment by chrsmrtn-** [comment]
issue is persisting with Nightly_5.0.29.0

**Comment by isaacrlevin** [comment]
So this is only when you start the app? Also the logs look incomplete., are there any more. If you navigate around the app does the UI eventually update?

**Comment by chrsmrtn-** [comment]
let me try the latest nightly and see

**Comment by chrsmrtn-** [comment]
waiting for nightly 5.0.31.0 so i can test this out and another ticket

**Comment by chrsmrtn-** [comment]
This has been resovled in 5.1.1 in the store. Thanks!
