### ISSUE TITLE
Yeelight not working in nightly build

### ISSUE THREAD

**Issue by Dmalmstrom** [isaacrlevin/presencelight#622]
**Describe the bug**
Can not set the colors for Yeelight
The ip-adress is not saved for Yeelight

**Screenshots**
![image](https://user-images.githubusercontent.com/101255758/157424781-23f250ff-fca8-4246-b24f-80910f21dc3b.png)
![image](https://user-images.githubusercontent.com/101255758/157425435-8ab6ac92-7c6e-4cdb-bacd-adb47945d8cb.png)

## Further details
- OS: Windows 10 Enterprise, 64-bit
- PresenceLight App Type: Desktop
- PresenceLight Build: Nightly
- PresenceLight Version: 6.0.2+839cdfb0ecca5e0be3dbccd926e7651ef50fdf10
- Did you clear settings.json? Yes

Thank you for supporting this program!

**Comment by isaacrlevin** [comment]
This is fixed in Nightly Version 5.0.31 and above

**Comment by isaacrlevin** [comment]
@Dmalmstrom can you confirm the issue is resolved in 5.1.1 Nightly?
https://presencelight.blob.core.windows.net/nightly/index.html

**Comment by Dmalmstrom** [comment]
Hi Isaak,

I’m sorry to say that the issue with the colors remain in 5.1.1.0. However, the connection to Yeelight is now working and saved.

 

Best regards,

David

**Comment by isaacrlevin** [comment]
Ok, give 5.1.3 a try (just pushed)

**Comment by Dmalmstrom** [comment]
The new version fixed the last issue - thank you!
