### ISSUE TITLE
LIFX lights not responding in both nightly and store versions

### ISSUE THREAD

**Issue by chrsmrtn-** [isaacrlevin/presencelight#624]
**Describe the bug**
Even when the status is showing up appropriately in the app, my lights are not responding to the change. I've reset my lights and am able to control them throughthe LIFX app and through Google Assistant.

**To Reproduce**
1. Launch app
2. Note the lights did not turn on to represent current status
3. Change status
4. Lights do not come on to reflect new status
5. Manually turn lights on
6. Change status
7. Lights do not change to reflect new status

**Expected behavior**
LIFX light to change to represent the status color for Teams

## Further details
- OS: Windows 10
- PresenceLight App Type: Desktop
- PresenceLight Build: Nightly and Store
- PresenceLight Version Nightly Nightly_5.0.29.0
- Did you clear settings.json? yes (C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json
- ASP.NET Core version: dotnet --version -> Nightly_5.0.29.0

**Comment by isaacrlevin** [comment]
This is fixed in Nightly Version 5.0.31 and above

**Comment by chrsmrtn-** [comment]
Nightly is still at 5.0.29.0. When will 5.0.31 be available?

**Comment by isaacrlevin** [comment]
5.1.1 Live test that out

**Comment by chrsmrtn-** [comment]
okay, we're working again in 5.1.1 in the store. Thanks!
