### ISSUE TITLE
The presence light application's about page doesn't show settings location

### ISSUE THREAD

**Issue by DenzelGeorge** [isaacrlevin/presencelight#628]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

## Further details
- PresenceLight App Type (Desktop, Blazor)
- PresenceLight Build (Nightly, Store, etc)
- PresenceLight Version (The # in About)
- Did you clear settings.json? (C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json
- ASP.NET Core version

**Comment by isaacrlevin** [comment]
Please populate issue template
