### ISSUE TITLE
Missing "Off Work" Activity in custom API

### ISSUE THREAD

**Issue by ykktrcb7** [isaacrlevin/presencelight#632]
**Describe the bug**
When I change status to Appear Offline, 
![image](https://user-images.githubusercontent.com/81748597/159671906-3fe9de6d-f2fe-4b3d-b986-4c6fdf6054d8.png)
PresenceLight sets activity to "Off Work", but only 2 options in the activity are available (Off and Offline).
![image](https://user-images.githubusercontent.com/81748597/159672142-792a1135-6328-4ad2-93ca-f826840e77ac.png)

**To Reproduce**
1. change status to Appear Offline, 
![image](https://user-images.githubusercontent.com/81748597/159671906-3fe9de6d-f2fe-4b3d-b986-4c6fdf6054d8.png)
2. Click on 'Teams Status' ![image](https://user-images.githubusercontent.com/81748597/159672142-792a1135-6328-4ad2-93ca-f826840e77ac.png)
3. "Off Work" is not an option in "Custom API Setup" 
![image](https://user-images.githubusercontent.com/81748597/159672492-fa6e6d01-0ec6-4c5a-b810-af5a58bbd6ba.png)

**Expected behavior**
Provide option for "Off Work" in API.

**Screenshots**
See above.

## Further details
- PresenceLight App Type (Desktop)
- PresenceLight Build (Store)
- PresenceLight Version (5.0.19)

**Comment by isaacrlevin** [comment]
There is an option in the Activity Section (you will need to check the "Use Activity Statuses" box
![image](https://user-images.githubusercontent.com/8878502/159956525-7404f75c-0d07-4eb4-845f-6c7e714d4b94.png)

If this is not in the store version, check the nightly
https://presencelight.blob.core.windows.net/nightly/index.html

**Comment by isaacrlevin** [comment]
@ykktrcb7 can you please test?

**Comment by ykktrcb7** [comment]
I got the following error, even after uninstalling the previous version:
`Merge failure for shared merged PRI file : error 0x80070490 : Cannot register the 37828IsaacLevin.197278F15330A.Nightly_5.2.3.0_x64__jvewcxq8vj8qt package because there was a merge failure with the following file: C:\Program Files\WindowsApps\37828IsaacLevin.197278F15330A.Nightly_5.2.3.0_neutral_split.language-pt_jvewcxq8vj8qt\resources.pri (0x80070490)`

**Comment by isaacrlevin** [comment]
If that error happens, a restart usually fixes it.

**Comment by ykktrcb7** [comment]
It happens even after restart. is there anything else i can try?

**Comment by isaacrlevin** [comment]
So you have ALL version of PL uninstalled? And you try to install the Nightly it gives you this error? What is your version of Windows? Also do you have the WebView2 runtime?

https://go.microsoft.com/fwlink/p/?LinkId=2124703

**Comment by ykktrcb7** [comment]
Yes, I have WebView2 and Windows 10. Everything was working before I tried the nightly build. I cleaned all directories and uninstalled PL completely.

**Comment by isaacrlevin** [comment]
Are you able to install the store version or you get the error as well?

**Comment by ykktrcb7** [comment]
The store version installs correctly.

**Comment by isaacrlevin** [comment]
Odd, well I will update this issue when the Store version gets updated

**Comment by isaacrlevin** [comment]
Please try latest version from the store
