### ISSUE TITLE
Yeelight not working

### ISSUE THREAD

**Issue by ad2012** [isaacrlevin/presencelight#634]
**Describe the bug**
Installed PresenceLight from scratch, after setting up Teams Connection and Yeelight integration, the bulb does not react. This error is logged:

{"Timestamp":"2022-03-24T10:03:46.7834547+01:00","Level":"Information","MessageTemplate":"Settings Saved from Yeelight Page","Properties":{"SourceContext":"PresenceLight.Razor.Pages.CustomApiSetup","Application":"PresenceLight"}}
{"Timestamp":"2022-03-24T10:03:46.8356639+01:00","Level":"Error","MessageTemplate":"Error occured Getting Photo - MainWindow.xaml:SetColor Line: 259","Exception":"System.ArgumentNullException: Value cannot be null. (Parameter 'collection')\r\n   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)\r\n   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)\r\n   at YeelightAPI.Device.GetProps(PROPERTIES props)\r\n   at YeelightAPI.Device.GetAllProps()\r\n   at YeelightAPI.Device.Connect()\r\n   at PresenceLight.Core.YeelightService.Handle(String presence, String lightId)\r\n   at PresenceLight.Core.YeelightService.SetColor(String availability, String activity, String lightId)\r\n   at PresenceLight.Core.YeelightServices.SetColorHandler.Handle(SetColorCommand command, CancellationToken cancellationToken)\r\n   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at PresenceLight.MainWindow.SetColor(String color, String activity) in D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs:line 248","Properties":{"SourceContext":"PresenceLight.MainWindow","LineNumber":259,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"SetColor","Application":"PresenceLight"}}
{"Timestamp":"2022-03-24T10:03:51.9353632+01:00","Level":"Information","MessageTemplate":"PresenceLight Running in Teams Mode - MainWindow.xaml:InteractWithLights Line: 566","Properties":{"SourceContext":"PresenceLight.MainWindow","LineNumber":566,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"InteractWithLights","Application":"PresenceLight"}}
{"Timestamp":"2022-03-24T10:03:57.5981601+01:00","Level":"Error","MessageTemplate":"Error occured Getting Photo - MainWindow.xaml:SetColor Line: 259","Exception":"System.ArgumentNullException: Value cannot be null. (Parameter 'collection')\r\n   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)\r\n   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)\r\n   at YeelightAPI.Device.GetProps(PROPERTIES props)\r\n   at YeelightAPI.Device.GetAllProps()\r\n   at YeelightAPI.Device.Connect()\r\n   at PresenceLight.Core.YeelightService.Handle(String presence, String lightId)\r\n   at PresenceLight.Core.YeelightService.SetColor(String availability, String activity, String lightId)\r\n   at PresenceLight.Core.YeelightServices.SetColorHandler.Handle(SetColorCommand command, CancellationToken cancellationToken)\r\n   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at PresenceLight.MainWindow.SetColor(String color, String activity) in D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs:line 248","Properties":{"SourceContext":"PresenceLight.MainWindow","LineNumber":259,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"SetColor","Application":"PresenceLight"}}

**To Reproduce**
1. Install PresenceLight
2. Log in to MS Teams
3. Set up and save Yeelight
4. See error message

**Expected behavior**
After setting up Yeelight, the bulb should change to set status color.

## Further details
- OS: Win11 21H2 22000.588
- PresenceLight App Type (Desktop, Blazor): Windows Store AppPackage
- PresenceLight Build (Nightly, Store, etc) Store
- PresenceLight Version (The # in About) 5.0.19
- Did you clear settings.json? Yes (C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json
- ASP.NET Core version

**Comment by isaacrlevin** [comment]
There is an issue with Store version, please test the latest nightly 
https://presencelight.blob.core.windows.net/nightly/index.html

**Comment by ad2012** [comment]
That one won't even install.
However I tried it with the chocolatey one, too. Same problem.

**Comment by isaacrlevin** [comment]
You get an error when you try to install the nightly?

**Comment by isaacrlevin** [comment]
@ad2012 any update?

**Comment by ad2012** [comment]
Installed nightly 5.2.3.0 via https://presencelight.blob.core.windows.net/nightly/index.html 
Failed:
![image](https://user-images.githubusercontent.com/2690733/162378419-6cf21e09-d7c0-4bcb-a566-fc71914b6ecf.png)

**Comment by isaacrlevin** [comment]
Please try latest version from the store
