### ISSUE TITLE
Status is flickering between "Busy/In A Call" and "Available/Available"

### ISSUE THREAD

**Issue by Xyolyp** [isaacrlevin/presencelight#664]
![image](https://user-images.githubusercontent.com/13995942/166685685-94a81f12-04f0-4ae1-99d0-286446f7c4e0.png)
Even though I was in a call the entire time the custom API (which is where I record the states and created the screenshot from) get's http messages very regularly that I would be Available and switches back to In A Call rapidly.

**Comment by Anto79-ops** [comment]
I was just about to post this. I have the same issue via custom API. I believe it started yesterday.

**Comment by churchs19** [comment]
I also started seeing this just yesterday. Also using a custom API as well.

**Comment by Anto79-ops** [comment]
seems to be doing it less today, although I thought it did it once this morning (6 hrs ago)...similar observations?

**Comment by isaacrlevin** [comment]
Can any of you show me some Fiddler logs when PresenceLight is running? That would help me determine if this is a bug or not.

**Comment by Anto79-ops** [comment]
I'd like to help you but I have no idea where to find such logs. If you can tell me, I'll look for them. However I must let you know that today was actually back to normal so whatever it was it was a short-lived glitch.

**Comment by isaacrlevin** [comment]
Have you used Fiddler before?
https://www.telerik.com/fiddler

**Comment by Anto79-ops** [comment]
Thanks for the suggestion. I have not used Fiddler before, but will use of the problem returns and report back.

**Comment by isaacrlevin** [comment]
@Xyolyp are you still seeing this issue in the latest version from store?

**Comment by Xyolyp** [comment]
@isaacrlevin I didn't observe this behavior over the last weeks any longer.
