### ISSUE TITLE
UI error with Wiz bulb

### ISSUE THREAD

**Issue by jbharold** [isaacrlevin/presencelight#671]
Fantastic app, but it seems to be hiccuping on my (new) Wiz light (8.8A19/Wi-Fi BLE Color/922-65). On a clean install everything is fine until I connect to the light and "Save". From then on it works (light changes color with my Teams status), but if I try to click into Configure Lights/Wiz, the UI freezes with "An unhandled error has occurred. Reload". If I click to another menu item and reload it's back, but it can't open the Wiz configuration page.  I've tried the PresenceLight store and nightly builds: currently on 5.5.16.0.  Log file is attached.  Thanks for building this app... getting it running was the highlight of my week.

[log-2022051306.zip](https://github.com/isaacrlevin/presencelight/files/8687221/log-2022051306.zip)

**Comment by isaacrlevin** [comment]
Hey there, try the latest nightly

**Comment by jbharold** [comment]
That's fixed it.  Thanks!
