### ISSUE TITLE
Data collection documentation 

### ISSUE THREAD

**Issue by robinkro** [isaacrlevin/presencelight#675]
My IT department is blocking the app due to data collection disclamer

> This app can
> Access all your files, peripheral devices, apps, programs and registry
> Access your Internet connection
> 

**Describe the solution you'd like**
My IT department is asking for more tecnical information about data collection, where its stored, where its transfered and who its shared with etc. 

It would be nice if this was documentet somewere (maby it is?) so i can get the ap white listed to our companys standards.

**Comment by isaacrlevin** [comment]
@robinkro 
Can you show me a screenshot of where this is said?

**Comment by robinkro** [comment]
![image](https://user-images.githubusercontent.com/60339921/172545856-051af8b6-3747-4921-ab50-aed2cb2d9c91.png)

This is what they react to, from the MS store

**Comment by isaacrlevin** [comment]
Got it, this is default messaging for Windows Apps that are deployed to the store. The app is vetted as part of the store certification process. You can read more about it here, but most apps that are built that are WPF or WinForms will have this message. If there are concerns, you can download the version the release section of GitHub

https://docs.google.com/document/d/1O7CZBIjGQU1WcOW28ysQlYOpUA3Ko-2bzbyFXxdlRN4/edit#

**Comment by robinkro** [comment]
cant access the google document, need permission

**Comment by isaacrlevin** [comment]
> cant access the google document, need permission 

I don't own that doc. I linked to the official MSFT documentation on it.
