### ISSUE TITLE
Failing to install via chocolatey

### ISSUE THREAD

**Issue by Absoblogginlutely** [isaacrlevin/PresenceLight#68]
Received the following when trying to update (and install after an uninstall/install)

ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Deployment failed with HRESULT: 0x80073CFF, To install this application you need either a Windows developer license or a sideloading-enabled system.

Deployment of package 37828IsaacLevin.197278F15330A_2.0.64.0_neutral_split.scale-100_jvewcxq8vj8qt with package origin Unknown failed because no valid license or sideloading policy could be applied. A developer license (http://go.microsoft.com/fwlink/?LinkId=233074) or enterprise sideloading configuration (http://go.microsoft.com/fwlink/?LinkId=231020) may be required.

NOTE: For additional information, look for [ActivityId] 6ad59df8-3fe8-0002-0a74-596be83fd601 in the Event Log or use the command line Get-AppPackageLog -ActivityID 6ad59df8-3fe8-0002-0a74-596be83fd601

The install of presencelight was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\PresenceLight\tools\ChocolateyInstall.ps1'.
 See log for details.

Fixed by creatng  HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Appx\AllowAllTrustedApps as DWord and setting value to  1

I had not seen this message show up before. I've not had a new group policy pushed to my domain joined machine that I'm aware of.

**Comment by isaacrlevin** [comment]
Have you installed it via Choco before?

**Comment by Absoblogginlutely** [comment]
Yes - that is how I originally installed it. I ran a cup all -y to upgrade the software on my machine and got the error message. 
Fixed with the registry (for other peoples benefit)

**Comment by isaacrlevin** [comment]
Can you do an install uninstall test for me with the latest version?

**Comment by Absoblogginlutely** [comment]
Same issue occurred with v2.0.64. With hklm\software\policies\microsoft\windows\appx\allowalltrusteddapps set to 0 I get the error. With it set to 1, everything is fine.
![Screenshot - 20200622-075637](https://user-images.githubusercontent.com/21364480/85284915-f98dcf00-b45d-11ea-8dd5-0c8df759b7b6.png)

I'm thinking the issues is that somehow my machine has been set so that only apps from the store can be loaded. I'm not sure how as it is not something I have configured and as I'm wfh there are no group policies being deployed! Setting the registry value fixes it but thats not something standard users should be doing.

 I  don't get this with any other chocolatey app.

**Comment by isaacrlevin** [comment]
Do you have developer mode enabled? Search Developer Settings with win+s
![image](https://user-images.githubusercontent.com/8878502/85342844-54e0b100-b4a0-11ea-9aae-df377b454b83.png)

**Comment by isaacrlevin** [comment]
Also, do you get any errors installing the GH version?
https://github.com/isaacrlevin/PresenceLight/releases/tag/v2.0.51

**Comment by Absoblogginlutely** [comment]
The original value of 0 in that registry field sets developer features to Microsoft Store Apps only and the rest of the options are greyed out.
When I set it to 1, the screen switches back to sideload apps.
With registry set to 1 I can install (as previously mentioned)
I get the same error when attempting to install the appxbundle using 
add-appxpackage -path c:\temp\PresenceLight.Package_2.0.51.0_x86.appxbundle

At this point I would say this is not an issue with your script, but more of a way the pc is setup. In order to install an appx bundle the machine needs to be set to allow sideloaded scripts.

Yours is the first chocolatey script (out of 81 currently installed) I've seen that uses appx to install rather than a zip or self extracting installer with silent mode.
Feel free to close this issue.

**Comment by isaacrlevin** [comment]
Thanks for the info!
