### ISSUE TITLE
Create a plugin interface to allow interfacing with more/new lights without having to integrate into the main project.

### ISSUE THREAD

**Issue by JMilthaler** [isaacrlevin/presencelight#692]
**Is your feature request related to a problem? Please describe.**

I find myself playing with a bunch of different solutions for updating various hardware / Smart Home systems that build off of the framework in PresenceLight but don't have HTTP endpoints to work with Custom API. Integrating into the full project can be a pain though as it's hard to remember all the places you have to make changes to support a new "Light". 

**Describe the solution you'd like**
A plugin interface that can be implemented and dynamically loaded that makes it easy to add a new light complete with configuration UI while not requiring the light to be built in PresenceLight.Core (and associated .Web .Desktop integrations).

**Additional context**
I'm actually working on this myself in my branch, just opening this feature request to loop you in and see what you think :-).
This started with the LocalSerialHost contribution I made a couple months ago and has grown from there to include Bluetooth Low Energy and ZWave devices. 

You can assign this to me if you like and I'll submit a few pulls over the next couple months as I have time. The end result will a class library with an interface that anyone can implement to hook into PresenceLight's polling and respond to changes.

**Comment by isaacrlevin** [comment]
Would love to see a PR when you are ready to share!

**Comment by isaacrlevin** [comment]
Closing this issues, @JMilthaler feel free to submit a PR for this functionality.
