### ISSUE TITLE
Hue Connection has a timeout?

### ISSUE THREAD

**Issue by hmrc87** [isaacrlevin/PresenceLight#70]
Hi,
after a few days (im not sure how many exactly) I have to fully reconfigure my Hue connection. Is this a limitation by my Hue Gateway (which is no original one, its a deconz-gateway that emulates the Hue Bridge?) I have other Software like the Hue Essentials App on iOS running with my Bridge without having the need to reconnect (ever).

Cheers
hmrc87

**Comment by isaacrlevin** [comment]
What do you see in fiddler when you have it running with presents like

**Comment by isaacrlevin** [comment]
@hmrc87 do you get any error at all?

**Comment by hmrc87** [comment]
Hi Isaac, sorry for the late reply. Unfortunately I cannot install fiddler on my work computer.I dont get an error but what is really odd is that when I now try to enter the Hue bridge IP again the Program wont let me. I am on version 2.0.51.0

![presencelight](https://user-images.githubusercontent.com/1226017/86435510-69267880-bd00-11ea-84df-d8b71e135db9.gif)

**Comment by isaacrlevin** [comment]
Can you install the latest nightly? version is 2.0.79

**Comment by hmrc87** [comment]
Hi Isaaac, I installed 2.0.85 and the problem still is there. Is there state saved in the registry or somewhere else? How do I really reset the app?

![presencelight2](https://user-images.githubusercontent.com/1226017/87003600-3c6cd800-c1bc-11ea-825d-8ab3d7ce22cb.gif)

**Comment by isaacrlevin** [comment]
Uninstall, restart machine and reinstall. Also you can run fiddler and see what happens when you click that button

**Comment by isaacrlevin** [comment]
Also try signing out from the first tab and try

**Comment by isaacrlevin** [comment]
Closing due to unanswered question. Feel free to reopen with info
