### ISSUE TITLE
Worked once but not since. Running on windows 10 desktop.

### ISSUE THREAD

**Issue by netsmith** [isaacrlevin/presencelight#703]
I got this all installed and configured and it called an Custom API when my status changed(to available)  just as expected which was great. Since then however it doesn't seem to make the call, although the app status changes to reflect that its picked up Im now available.

I've tested the API call by copy and pasting directly into a browser and that performs as expected.

Looking in the live logs, it doesn't show its even attempting to make the call. Just a steady flow of these messages (regardless of if I am changing status or not)

21/07/2022 14:47:21 +01:00 | Information | PresenceLight Running in Teams Mode - MainWindow.xaml:InteractWithLights Line: 571

Application Type
AppPackage
Application Version
5.5.18
Runtime Version
6.0.7+0ec02c8c96e2eda06dc5b5edfdbdba0f36415082

**Comment by netsmith** [comment]
UPDATE: If i quit the app and restart it, it detects the status and calls the custom API, again just the first time. Any change in status after that point and the custom API is not called again

**Comment by isaacrlevin** [comment]
I don't have a custom api to test. @camsoper have you ever seen this?

**Comment by netsmith** [comment]
Should it put something in the log when it calls the API?

**Comment by netsmith** [comment]
![image](https://user-images.githubusercontent.com/3663182/180263424-8d5d32fe-1955-4d63-90dc-588aa190e1f8.png)

Actually when I start the app it does log the call. After that it never calls it again.

**Comment by netsmith** [comment]
@isaacrlevin don't think you need an actual custom API to test this, as the first step is just to check the log and see if its getting called (as it looks like it shows the calls made). From what I can see it is called the once at start up and then not again on subsequent changes of your teams status.

**Comment by netsmith** [comment]
Also what is the difference between "Available" , "Available Idle" and "Activity Available" options. Im just looking on triggering my API when my status chances from anything to "available"

**Comment by isaacrlevin** [comment]
These docs should help
https://docs.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-1.0

https://docs.microsoft.com/en-us/microsoftteams/presence-admins

**Comment by isaacrlevin** [comment]
@netsmith Just looked at this and I was able to hit a custom endpoint consistently. Not sure your setup. But here is what I am seeing in Fiddler. The endpoint doesn't exist but I see the request going out. Are you able to see the same with Fiddler?

![image](https://user-images.githubusercontent.com/8878502/180891186-24bf3068-3a32-413c-8eea-fc40f89fe3ba.png)

![image](https://user-images.githubusercontent.com/8878502/180891231-3cfb4ebf-c918-4fbd-b07f-f3907b6270b9.png)

**Comment by netsmith** [comment]
Sorry been on leave - will look into this thanks

**Comment by netsmith** [comment]
Are you supposed to see the POST instruction in the applications logs? (Like the initial call shown above) Because Iike I said I see the first call, but then don't see any subsequent calls listed. Should it show errors or success or anything?

**Comment by netsmith** [comment]
Actually does the log file actually show when the team status is changed? or is it just that "Information" ping message and errors?

**Comment by netsmith** [comment]
Ive checked with fiddler and it looks like it is not making the call

The initial call to my API (Virtualbutton) is called on startup of the app. (see below) but never again. The "forceAvailability" lines relate to when I am changing states between busy and available.

![image](https://user-images.githubusercontent.com/3663182/182363188-b867fc2c-98b9-483f-bff4-d7ac0f49bf40.png)

**Comment by netsmith** [comment]
Here is my settings file if that helps.

﻿{
  "SendDiagnosticData": true,
  "StartMinimized": false,
  "IconType": "Transparent",
  "LightSettings": {
    "HoursPassedStatus": "Keep",
    "SyncLights": true,
    "WorkingDays": "Monday|Tuesday|Wednesday|Thursday|Friday",
    "UseWorkingHours": true,
    "UseAmPm": true,
    "WorkingHoursStartTime": "08:00:00",
    "WorkingHoursEndTime": "18:01:00",
    "PollingInterval": 5.0,
    "UseDefaultBrightness": true,
    "DefaultBrightness": 100,
    "CustomApi": {
      "CustomApiTimeout": 100.0,
      "IgnoreCertificateErrors": true,
      "UseBasicAuth": false,
      "BasicAuthUserName": "",
      "BasicAuthUserPassword": "",
      "CustomApiAvailable": {
        "Method": "POST",
        "Uri": "https://api.virtualbuttons.com/v1?virtualButton=1&accessCode=amzn1.ask.account[REMOVED]"
      },
      "CustomApiBusy": {
        "Method": "POST",
        "Uri": ""
      },
      "CustomApiBeRightBack": {
        "Method": "POST",
        "Uri": ""
      },
      "CustomApiAway": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiDoNotDisturb": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiAvailableIdle": {
        "Method": "POST",
        "Uri": "https://api.virtualbuttons.com/v1?virtualButton=1&accessCode=amzn1.ask.account.[REMOVED]"
      },
      "CustomApiOffline": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiOff": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityAvailable": {
        "Method": "POST",
        "Uri": "https://api.virtualbuttons.com/v1?virtualButton=1&accessCode=amzn1.ask.account.[REMOVED]"
      },
      "CustomApiActivityInACall": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityInAConferenceCall": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityInAMeeting": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityPresenting": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityBusy": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityAway": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityBeRightBack": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityDoNotDisturb": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityIdle": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityOffline": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityOff": {
        "Method": "",
        "Uri": ""
      },
      "IsEnabled": true,
      "SelectedItemId": "",
      "Brightness": 100,
      "Statuses": null,
      "UseActivityStatus": false
    },
    "LocalSerialHost": {
      "LocalSerialHostMainSetup": {
        "BaudRate": "",
        "LineEnding": "",
        "Port": "",
        "Message": null
      },
      "LocalSerialHostAvailable": "",
      "LocalSerialHostBusy": "",
      "LocalSerialHostBeRightBack": "",
      "LocalSerialHostAway": "",
      "LocalSerialHostDoNotDisturb": "",
      "LocalSerialHostAvailableIdle": "",
      "LocalSerialHostOffline": "",
      "LocalSerialHostOff": "",
      "LocalSerialHostActivityAvailable": "",
      "LocalSerialHostActivityInACall": "",
      "LocalSerialHostActivityInAConferenceCall": "",
      "LocalSerialHostActivityInAMeeting": "",
      "LocalSerialHostActivityPresenting": "",
      "LocalSerialHostActivityBusy": "",
      "LocalSerialHostActivityAway": "",
      "LocalSerialHostActivityBeRightBack": "",
      "LocalSerialHostActivityDoNotDisturb": "",
      "LocalSerialHostActivityIdle": "",
      "LocalSerialHostActivityOffline": "",
      "LocalSerialHostActivityOff": "",
      "IsEnabled": false,
      "SelectedItemId": "",
      "Brightness": 100,
      "Statuses": null,
      "UseActivityStatus": false
    },
    "LIFX": {
      "LIFXApiKey": "",
      "LIFXClientId": "[REMOVED - NOT USING LIFX]",
      "LIFXClientSecret": "[REMOVED - NOT USING LIFX]",
      "IsEnabled": false,
      "SelectedItemId": "",
      "Brightness": 100,
      "Statuses": {
        "AvailabilityAvailableStatus": {
          "Disabled": false,
          "Colour": "#00ff55"
        },
        "AvailabilityAvailableIdleStatus": {
          "Disabled": false,
          "Colour": "#FFFF00"
        },
        "AvailabilityAwayStatus": {
          "Disabled": false,
          "Colour": "#FFFF00"
        },
        "AvailabilityBeRightBackStatus": {
          "Disabled": false,
          "Colour": "#FFFF00"
        },
        "AvailabilityBusyStatus": {
          "Disabled": false,
          "Colour": "#FF3300"
        },
        "AvailabilityBusyIdleStatus": {
          "Disabled": false,
          "Colour": "#FFFF00"
        },
        "AvailabilityDoNotDisturbStatus": {
          "Disabled": false,
          "Colour": "#B03CDE"
        },
        "AvailabilityOfflineStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "AvailabilityPresenceUnknownStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "AvailabilityOffStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "ActivityAvailableStatus": {
          "Disabled": false,
          "Colour": "#4f824f"
        },
        "ActivityAwayStatus": {
          "Disabled": false,
          "Colour": "#ffff00"
        },
        "ActivityBeRightBackStatus": {
          "Disabled": false,
          "Colour": "#ffff00"
        },
        "ActivityBusyStatus": {
          "Disabled": false,
          "Colour": "#ff0000"
        },
        "ActivityDoNotDisturbStatus": {
          "Disabled": false,
          "Colour": "#960000"
        },
        "ActivityInACallStatus": {
          "Disabled": false,
          "Colour": "#ff0000"
        },
        "ActivityInAConferenceCallStatus": {
          "Disabled": false,
          "Colour": "#ff00d4"
        },
        "ActivityInactiveStatus": {
          "Disabled": false,
          "Colour": "#ffff00"
        },
        "ActivityInAMeetingStatus": {
          "Disabled": false,
          "Colour": "#ff0000"
        },
        "ActivityOfflineStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "ActivityOffStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "ActivityOffWorkStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "ActivityOutOfOfficeStatus": {
          "Disabled": false,
          "Colour": "#ae00ff"
        },
        "ActivityPresenceUnknownStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "ActivityPresentingStatus": {
          "Disabled": false,
          "Colour": "#960000"
        },
        "ActivityUrgentInterruptionsOnlyStatus": {
          "Disabled": false,
          "Colour": "#560061"
        }
      },
      "UseActivityStatus": false
    },
    "Hue": {
      "RemoteHueClientId": "[REMOVED - NOT USING HUE]",
      "RemoteHueClientAppName": "presencelight",
      "RemoteHueClientSecret": "[REMOVED - NOT USING HUE]",
      "HueApiKey": "",
      "HueIpAddress": "",
      "UseRemoteApi": false,
      "RemoteBridgeId": "",
      "IsEnabled": false,
      "SelectedItemId": "",
      "Brightness": 100,
      "Statuses": {
        "AvailabilityAvailableStatus": {
          "Disabled": false,
          "Colour": "#00ff55"
        },
        "AvailabilityAvailableIdleStatus": {
          "Disabled": false,
          "Colour": "#FFFF00"
        },
        "AvailabilityAwayStatus": {
          "Disabled": false,
          "Colour": "#FFFF00"
        },
        "AvailabilityBeRightBackStatus": {
          "Disabled": false,
          "Colour": "#FFFF00"
        },
        "AvailabilityBusyStatus": {
          "Disabled": false,
          "Colour": "#FF3300"
        },
        "AvailabilityBusyIdleStatus": {
          "Disabled": false,
          "Colour": "#FFFF00"
        },
        "AvailabilityDoNotDisturbStatus": {
          "Disabled": false,
          "Colour": "#B03CDE"
        },
        "AvailabilityOfflineStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "AvailabilityPresenceUnknownStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "AvailabilityOffStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "ActivityAvailableStatus": {
          "Disabled": false,
          "Colour": "#4f824f"
        },
        "ActivityAwayStatus": {
          "Disabled": false,
          "Colour": "#ffff00"
        },
        "ActivityBeRightBackStatus": {
          "Disabled": false,
          "Colour": "#ffff00"
        },
        "ActivityBusyStatus": {
          "Disabled": false,
          "Colour": "#ff0000"
        },
        "ActivityDoNotDisturbStatus": {
          "Disabled": false,
          "Colour": "#960000"
        },
        "ActivityInACallStatus": {
          "Disabled": false,
          "Colour": "#ff0000"
        },
        "ActivityInAConferenceCallStatus": {
          "Disabled": false,
          "Colour": "#ff00d4"
        },
        "ActivityInactiveStatus": {
          "Disabled": false,
          "Colour": "#ffff00"
        },
        "ActivityInAMeetingStatus": {
          "Disabled": false,
          "Colour": "#ff0000"
        },
        "ActivityOfflineStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "ActivityOffStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "ActivityOffWorkStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "ActivityOutOfOfficeStatus": {
          "Disabled": false,
          "Colour": "#ae00ff"
        },
        "ActivityPresenceUnknownStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "ActivityPresentingStatus": {
          "Disabled": false,
          "Colour": "#960000"
        },
        "ActivityUrgentInterruptionsOnlyStatus": {
          "Disabled": false,
          "Colour": "#560061"
        }
      },
      "UseActivityStatus": false
    },
    "Yeelight": {
      "IsEnabled": false,
      "SelectedItemId": "",
      "Brightness": 100,
      "Statuses": {
        "AvailabilityAvailableStatus": {
          "Disabled": false,
          "Colour": "#00ff55"
        },
        "AvailabilityAvailableIdleStatus": {
          "Disabled": false,
          "Colour": "#FFFF00"
        },
        "AvailabilityAwayStatus": {
          "Disabled": false,
          "Colour": "#FFFF00"
        },
        "AvailabilityBeRightBackStatus": {
          "Disabled": false,
          "Colour": "#FFFF00"
        },
        "AvailabilityBusyStatus": {
          "Disabled": false,
          "Colour": "#FF3300"
        },
        "AvailabilityBusyIdleStatus": {
          "Disabled": false,
          "Colour": "#FFFF00"
        },
        "AvailabilityDoNotDisturbStatus": {
          "Disabled": false,
          "Colour": "#B03CDE"
        },
        "AvailabilityOfflineStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "AvailabilityPresenceUnknownStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "AvailabilityOffStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "ActivityAvailableStatus": {
          "Disabled": false,
          "Colour": "#4f824f"
        },
        "ActivityAwayStatus": {
          "Disabled": false,
          "Colour": "#ffff00"
        },
        "ActivityBeRightBackStatus": {
          "Disabled": false,
          "Colour": "#ffff00"
        },
        "ActivityBusyStatus": {
          "Disabled": false,
          "Colour": "#ff0000"
        },
        "ActivityDoNotDisturbStatus": {
          "Disabled": false,
          "Colour": "#960000"
        },
        "ActivityInACallStatus": {
          "Disabled": false,
          "Colour": "#ff0000"
        },
        "ActivityInAConferenceCallStatus": {
          "Disabled": false,
          "Colour": "#ff00d4"
        },
        "ActivityInactiveStatus": {
          "Disabled": false,
          "Colour": "#ffff00"
        },
        "ActivityInAMeetingStatus": {
          "Disabled": false,
          "Colour": "#ff0000"
        },
        "ActivityOfflineStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "ActivityOffStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "ActivityOffWorkStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "ActivityOutOfOfficeStatus": {
          "Disabled": false,
          "Colour": "#ae00ff"
        },
        "ActivityPresenceUnknownStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "ActivityPresentingStatus": {
          "Disabled": false,
          "Colour": "#960000"
        },
        "ActivityUrgentInterruptionsOnlyStatus": {
          "Disabled": false,
          "Colour": "#560061"
        }
      },
      "UseActivityStatus": false
    },
    "Wiz": {
      "IsEnabled": false,
      "SelectedItemId": "",
      "Brightness": 100,
      "Statuses": {
        "AvailabilityAvailableStatus": {
          "Disabled": false,
          "Colour": "#00ff55"
        },
        "AvailabilityAvailableIdleStatus": {
          "Disabled": false,
          "Colour": "#FFFF00"
        },
        "AvailabilityAwayStatus": {
          "Disabled": false,
          "Colour": "#FFFF00"
        },
        "AvailabilityBeRightBackStatus": {
          "Disabled": false,
          "Colour": "#FFFF00"
        },
        "AvailabilityBusyStatus": {
          "Disabled": false,
          "Colour": "#FF3300"
        },
        "AvailabilityBusyIdleStatus": {
          "Disabled": false,
          "Colour": "#FFFF00"
        },
        "AvailabilityDoNotDisturbStatus": {
          "Disabled": false,
          "Colour": "#B03CDE"
        },
        "AvailabilityOfflineStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "AvailabilityPresenceUnknownStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "AvailabilityOffStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "ActivityAvailableStatus": {
          "Disabled": false,
          "Colour": "#4f824f"
        },
        "ActivityAwayStatus": {
          "Disabled": false,
          "Colour": "#ffff00"
        },
        "ActivityBeRightBackStatus": {
          "Disabled": false,
          "Colour": "#ffff00"
        },
        "ActivityBusyStatus": {
          "Disabled": false,
          "Colour": "#ff0000"
        },
        "ActivityDoNotDisturbStatus": {
          "Disabled": false,
          "Colour": "#960000"
        },
        "ActivityInACallStatus": {
          "Disabled": false,
          "Colour": "#ff0000"
        },
        "ActivityInAConferenceCallStatus": {
          "Disabled": false,
          "Colour": "#ff00d4"
        },
        "ActivityInactiveStatus": {
          "Disabled": false,
          "Colour": "#ffff00"
        },
        "ActivityInAMeetingStatus": {
          "Disabled": false,
          "Colour": "#ff0000"
        },
        "ActivityOfflineStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "ActivityOffStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "ActivityOffWorkStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "ActivityOutOfOfficeStatus": {
          "Disabled": false,
          "Colour": "#ae00ff"
        },
        "ActivityPresenceUnknownStatus": {
          "Disabled": false,
          "Colour": "#FFFFFF"
        },
        "ActivityPresentingStatus": {
          "Disabled": false,
          "Colour": "#960000"
        },
        "ActivityUrgentInterruptionsOnlyStatus": {
          "Disabled": false,
          "Colour": "#560061"
        }
      },
      "UseActivityStatus": false
    }
  },
  "AppType": "Desktop"
}

**Comment by isaacrlevin** [comment]
Just set Available and Busy and manually switch in Teams and report back if that works

**Comment by netsmith** [comment]
Thats fixed it thanks. I never even thought of setting a 'Busy' call as I don't want any action to kick off when that happens. I just wanted my api to be called when I was set to available. No probs though, I can work with this now I know you need both. Thanks for the support. Chris.
