### ISSUE TITLE
Mic mute (unmute) status

### ISSUE THREAD

**Issue by pauliusbau** [isaacrlevin/presencelight#712]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I forget to mute or unmute myself during Team call. It's quite hard to know if your microphone is on, when Teams windows is in a background. Like when one is doing something useful during a looong call.

**Describe the solution you'd like**
I would like to have an ability to ping serial device ar call custom api with microphone mute/unmute status information. Ideally I would like to build a small USB led light witch would light up when I am unmuted.

**Describe alternatives you've considered**
I looked into mutesync.com, but their app didn't work properly on my workstation. Also I really need an ability to communicate with serial device or api calls.

**Additional context**
Thanks for creating this app!

**Comment by isaacrlevin** [comment]
This is outside the scope of PresenceLight as your request has nothing to do with Teams. Closing

**Comment by pauliusbau** [comment]
:( It's exactly MS Teams related. My suggestion was to monitor and act on **Teams** call Mic status (mute/unmute):
![paveikslas](https://user-images.githubusercontent.com/5681726/185046657-cf0d6c37-6db6-4785-8cee-419ad4c49791.png)

**Comment by isaacrlevin** [comment]
Sorry meant Presence related.
