### ISSUE TITLE
Wont connect to Teams anymore, exception seen in the logs

### ISSUE THREAD

**Issue by fcusano9** [isaacrlevin/presencelight#719]
**Describe the bug**
Great job with the app, I am really loving it and it has been working great until today.

Now when I open the app I just see a spinner where you normally see your Teams status. I have tried fully closing the app but that didn't fix it. A reinstall will probably fix it but I don't want to re-apply all of my settings.

Logs:
[log-2022090108.zip](https://github.com/isaacrlevin/presencelight/files/9469662/log-2022090108.zip)

**To Reproduce**
1. Open app and observe issue

**Screenshots**
![image](https://user-images.githubusercontent.com/25214122/187910662-2cdcb527-b52c-46b6-8ecf-2e38834beae8.png)

## Further details
- OS: Windows
- PresenceLight App Type: Desktop
- PresenceLight Build: Microsoft Store
- PresenceLight Version: 5.5.17
- Did you clear settings.json: No (C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json
- ASP.NET Core version: Not sure

**Comment by punocchio1** [comment]
I just installed the app for the first time and I am seeing the exact same issue, so unlikely an uninstall/reinstall will resolve it. 

Error message I see in live logging is "Error Occured Getting Batch Content from Graph Api - GraphWrapper:GetBatchContent Line: 106"

**Comment by SHHA24** [comment]
Same issue - https://github.com/isaacrlevin/presencelight/issues/721#issue-1368079601

**Comment by isaacrlevin** [comment]
@fcusano9 @punocchio1 are you still seeing this? Curious to see if it was some weird Graph hiccup

**Comment by isaacrlevin** [comment]
Closing
