### ISSUE TITLE
Graph Connection 

### ISSUE THREAD

**Issue by SHHA24** [isaacrlevin/presencelight#721]
Running version 5.5.17 , on Win11.

It was working fine but now just get a spinning wheel on the Teams Status tab, and the below error message. 

 
![logs](https://user-images.githubusercontent.com/62449702/189400517-930fe104-fbdf-422e-860d-a1e0ca68214f.png)

When my PC started it normally opens the web browser and signs into Teams and then the presence light minimizes down. But its not doing that anymore.

**Comment by isaacrlevin** [comment]
Do you have any more logs than this? There are some file logs as well

**Comment by jeroenterheerdt** [comment]
having the same issue - here's a log file: 
[log-2022092810.zip](https://github.com/isaacrlevin/presencelight/files/9667689/log-2022092810.zip)

**Comment by isaacrlevin** [comment]
@jeroenterheerdt can you try to logout of PresenceLight and log back in?

**Comment by jeroenterheerdt** [comment]
Not sure how to, because there is nothing in the UI that allows me to log out / log back in:
![image](https://user-images.githubusercontent.com/8188990/193104054-14b01fe1-92ae-4865-a28b-1fadf58796ec.png)

I tried restarting the app / rebooting, but that did not help at all.

**Comment by jeroenterheerdt** [comment]
I did, but for whatever reason that fixed it now. Only difference is that I was working from home yesterday when I tried that.

**Comment by isaacrlevin** [comment]
It might have been some caching issue. Glad you got it working

**Comment by isaacrlevin** [comment]
Closing
