### ISSUE TITLE
Ability to manually PAUSE the light presence syncing

### ISSUE THREAD

**Issue by sborg-ms** [isaacrlevin/PresenceLight#73]
Could you extend the working hours feature to also allow a manual PAUSE toggle on this settings - if we just want to stop it syncing for a particular period and manually set/re-enable without having to exit the app!

**Comment by isaacrlevin** [comment]
So basically move the button on the sign-in page?

**Comment by sborg-ms** [comment]
OK - so when i looked at that checkbox "Teams Sync Enabled" i supposed i interpreted it as do we want to have teams sync setup enabled  - but are you saying this check box is only stopping the ONGOING regular syncing between app and teams and does not affect the actual setup?

**Comment by sborg-ms** [comment]
further - testing this one - if i uncheck the sync enabled - then say turn off the LIFX light - then turn on the checkbox again it does not start syncing again (confirmed by manually changing status) and does not turn the light back on....   I had to exit and restart the app. Then it turn light on with correct status (as check box was sync'd)
Expected?

**Comment by isaacrlevin** [comment]
Please try the latest nightly, as I have cleaned up the light sync process

**Comment by sborg-ms** [comment]
New nightly build -2.0.73.0  - installed the Light Sync Enabled was NOT pre-checked.  Checking it ON did not see the syncing start - had to exit and restart app for it to pick up current presence BUT it still does not auto sync when testing manually by changing presence status  (stuck on what it started up with)

**Comment by warthurton** [comment]
My current work around is to suspend the PresenceLight process  (pssuspend PresenceLight) when I want syncing to stop and then resuming (pssuspend -r PresenceLight) the process when I want it going again.  I have this triggered at lock of my computer if it detects that I'm on the office dock.  It resumes (or tries to) whenever I unlock the PC.  The working hours feature takes care of the rest.

Not elegant but it works pretty well.

**Comment by isaacrlevin** [comment]
Try 2.0.75 I removed some light value caching

**Comment by sborg-ms** [comment]
on 2.0.75 - after start it still does not auto sync when testing manually by changing presence status (stuck on what it started up with)  [current released version still works fine]

**Comment by sborg-ms** [comment]
Update: With the manual work around for issue #72 in place and the working hours time set it now is correctly auto sync when testing manually by changing presence status!

**Comment by sborg-ms** [comment]
2.0.75.0 - Light Sync Enabled checkbox - now seems to correctly pause the syncing of the teams presence status - it does however leave it set to the last colour/prescience that was active?  Thinking however if this should return it to no colour (like what happens when you exit the app), rather than the last known status/colour - thoughts?

**Comment by isaacrlevin** [comment]
Added to 2.0.85
