### ISSUE TITLE
Webcam status

### ISSUE THREAD

**Issue by lbbeurmann** [isaacrlevin/presencelight#738]
I need a way to show that my webcam is active within MS Teams to keep my family out of my office and off camera.

Is there a way to have the app check whether or not the webcam is active in Teams and have a corresponding setting to reflect that?  Since my smart bulb is already red when I am in a meeting, could there be a setting to have it flash at a specified interval while my camera is on? 

I have seen some solutions online that use python scripting to do this, but that is way over my head.

**Comment by isaacrlevin** [comment]
This is outside the scope of PresenceLight. Would love to see you fork and create any experience you want using PL as a framework
