### ISSUE TITLE
PresenceLight lost connection to teams and is no longer working

### ISSUE THREAD

**Issue by tonyfitzs** [isaacrlevin/presencelight#744]
Teams crashed pretty convincingly not so long ago and needed to be re-installed and now PresenceLight is no longer able to sync with Teams. I expect it is a simple matter of re-installing but I thought I would let you know just in case there is an easy way of fixing it 

Application Type
AppPackage
Application Version
5.5.18
Install Location
C:\Program Files\WindowsApps\37828IsaacLevin.197278F15330A.Nightly_5.5.18.0_x64__jvewcxq8vj8qt\PresenceLight\
Install Date
27/07/2022 10:37 AM
Runtime Version
6.0.7+0ec02c8c96e2eda06dc5b5edfdbdba0f36415082

**Comment by isaacrlevin** [comment]
Are you still seeing this issue? If so, can you provide logs?

**Comment by isaacrlevin** [comment]
Closing. please re-open if you are having issues
