### ISSUE TITLE
Activity Off Work missing in CustomAPI

### ISSUE THREAD

**Issue by tom1104** [isaacrlevin/presencelight#765]
**Describe the bug**
when switching Teams to Offline, the status of PresenceLight changes to: Availability: Offline / Activity: Off Work

Activity Off and Offline is available, but Off Work is missing.

**Expected behavior**
Activity Off Work should be available and work the same way as Off and Offline.

Application Type: AppPackage
Application Version: 5.5.17
Install Location: C:\Program Files\WindowsApps\37828IsaacLevin.197278F15330A_5.5.17.0_x64__zfcjmmeb3zeaa\PresenceLight\
Install Date: 07.11.2022 13:42
Runtime Version: 6.0.5+70ae3df4a6f3c92fb6b315afc405edd10ff38579

**Comment by isaacrlevin** [comment]
@tom1104 
Can you try the latest nightly?

**Comment by isaacrlevin** [comment]
Fixed in Store version
