### ISSUE TITLE
Idea: Allow custom mapping of colours to status

### ISSUE THREAD

**Issue by bjeans** [isaacrlevin/PresenceLight#77]
it would be great to be able to choose the colors that you want displayed for each status vs. the pre-defined colours.

Effectively taking some of the work from #56 and making similar options with colour pickers available in settings would allow for custom colouring.

**Comment by ben-pearson** [comment]
Also adding the ability to select to no colour/off for some statuses. I'd like to only have the light on only if I'm unavailable. Wasting precious electricity telling people to come talk to me.

**Comment by ben-pearson** [comment]
@isaacrlevin I've created a pull request for my work on customising colours for Philips Hue.

Apologies I've never used github before and haven't written any Microsoft for 20 years. Let me know if anything needs work

**Comment by isaacrlevin** [comment]
@ben-pearson I merged your PR, thanks!

@bjeans support for color picking was added for LIFX and Hue, available in Nightly. Let me know how it goes
