### ISSUE TITLE
An unhandled error has occurred. Reload

### ISSUE THREAD

**Issue by BenTheCloudGuy** [isaacrlevin/presencelight#773]
**Describe the bug**
An unhandled error has occurred. Reload. When this error happens, I'm unable to do anything else in the app, including checking the live logs to help understand what is causing this issue.

**To Reproduce**

**Expected behavior**
To be able to view logs and other menu options.

**Screenshots**

## Further details
- OS: Windows 11
- PresenceLight App Type Desktop
- PresenceLight Build Store
- PresenceLight Version 
- Did you clear settings.json? - Yes (C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json
- ASP.NET Core version

**Comment by isaacrlevin** [comment]
Are there log files? They are located here

> C:\Users\username\AppData\Local\PresenceLight\logs\DesktopClient\

**Comment by isaacrlevin** [comment]
Closing as need more info. Please reopen a new issue
