### ISSUE TITLE
Idea: Different brightness levels per lighting type

### ISSUE THREAD

**Issue by bjeans** [isaacrlevin/PresenceLight#78]
I currently have both Hue and Lifx bulbs setup to reflect my presence.  I would love to be able to set brightness individually vs. globally as the brightness of the lights is different as well as the locations in which they are positioned have different background light levels.

**Comment by isaacrlevin** [comment]
This has been added to the latest nightly, let me know if it works

**Comment by isaacrlevin** [comment]
@bjeans give it a try

**Comment by bjeans** [comment]
works for me, however, I did initially miss the fact that I had to deselect the "Lights use Same brightness" setting in the settings tab before the individual light brightness took effect.

Thanks!
