### ISSUE TITLE
Philips Hue Cloud Config Not Working

### ISSUE THREAD

**Issue by jjjjjjjj99** [isaacrlevin/presencelight#785]
When trying to use Hue cloud, it allows me to press "Login to Hue Cloud" and then takes me out to Philips website where I then "grant permission".  The web page tells me to return to the app... however nothing happens/changes in the app screen to allow me to configure my Hue setup.

Have tried clearing out my settings file today but observed no change/difference in behavior.

App Ver: 5.5.17
Windows 11 Enterprise Build 22621

[log-2023010316.txt](https://github.com/isaacrlevin/presencelight/files/10339831/log-2023010316.txt)

![image](https://user-images.githubusercontent.com/18564207/210442540-fd6a5879-4ebe-4f78-9da4-80a539d69934.png)

**Comment by isaacrlevin** [comment]
Closing as you open 2 issues related to similar things
