### ISSUE TITLE
Use local teams api for realtime updates

### ISSUE THREAD

**Issue by svrooij** [isaacrlevin/presencelight#798]
Have you seen the messages on the Teams/Streamdeck integration on Twitter?

Long story short, they build a localhost websocket in the latest version of the teams client. Once you connect, you get realtime **IsInMeeting** updates. 
https://lostdomain.notion.site/Microsoft-Teams-WebSocket-API-5c042838bc3e4731bdfe679e864ab52a

This could be a great addition to your app.

I already [build](https://github.com/svrooij/teams-monitor) something in C# that connects to it, that you can easily copy.

**Comment by isaacrlevin** [comment]
The only problem is that this tethers PL to the box that Teams is running on. Is is against the #1 value prop of PL, that you don't need to run PL on a device that is connected to a light OR Teams. I might be interested in providing an option for folks to use the WebSocket approach, but I would love to see a PR for it!

**Comment by isaacrlevin** [comment]
Closing as this is against one of the core parts of PresenceLight
