### ISSUE TITLE
Docker container?

### ISSUE THREAD

**Issue by mzac** [isaacrlevin/PresenceLight#80]
Would there be any way to deploy the build in a docker container since you're using new modern build methods?

**Comment by isaacrlevin** [comment]
Are you talking about the Blazor app? I wouldn't see why not. Would have to punch a hole in the container firewall to allow access to the user admin screen

**Comment by mzac** [comment]
I guess.. I don't know much about Blazor but I did find this.  For the admin page, maybe the app could generate a token that would be displayed in the docker log file (a bit like codeserver does) and then you could use that token to login?

https://chrissainty.com/containerising-blazor-applications-with-docker-containerising-a-blazor-server-app/

**Comment by isaacrlevin** [comment]
PresenceLight now supports running in docker and docker-compose. More info in Worker readme
