### ISSUE TITLE
Integration with Homebridge / Homekit?

### ISSUE THREAD

**Issue by Spanishu** [isaacrlevin/PresenceLight#81]
I know this might be a bit far reaching but I am running a lot of things with Homebridge. It allows for many custom API to be running on Homekit which is much more restrictive. 
The advantage is that you can use a more open environment as well and are not as tied to a specific vendor. 
Thanks in advance

**Comment by isaacrlevin** [comment]
Have you tried the custom API screen?

**Comment by isaacrlevin** [comment]
Closing as been waiting a bit for a question answered. Feel free to reopen

**Comment by Spanishu** [comment]
Hi, 
sorry was quite busy in the last couple of weeks. I have looked at the custom API part, however, I am really not a coder so I am a bit lost here. The solution I would like to interface with is https://github.com/dresden-elektronik/deconz-rest-plugin/wiki
If you feel like it and have some time, would be cool to get some guidance. 
The API will need authentication, that much I do know
The other think I look for is simply when busy, switch on a light, if not switch it off. 
Thanks a lot in advance
