### ISSUE TITLE
Presence app stopped worked

### ISSUE THREAD

**Issue by sborg-ms** [isaacrlevin/presencelight#810]
App recently stopped working - rebooted and re-installed again (latest ver same)

**Screenshots**
<img width="588" alt="image" src="https://user-images.githubusercontent.com/67351620/221074149-d48c3027-3ec9-4847-bd4f-dbbe75a53103.png">

**Comment by isaacrlevin** [comment]
What version?

**Comment by sborg-ms** [comment]
Only ever used the Nightly build - cant get ver from app as its not loading but when trying to reinstall it says v5.5.40.0
<img width="348" alt="image" src="https://user-images.githubusercontent.com/67351620/221989994-fdb150a8-ffc2-40df-882e-240dd4a48a17.png">

**Comment by isaacrlevin** [comment]
Just made an update, try now

**Comment by sborg-ms** [comment]
that new version has installed and app and the staus is working again!
