### ISSUE TITLE
Add USB LED support - Mfg: ThingM, Model Blink(1)

### ISSUE THREAD

**Issue by jescodev** [isaacrlevin/presencelight#817]
The USB LED made by ThingM is very popular and a simple USB LED status LED. 
Possibly add direct support for controlling this LED.
Company web site is: ThingM.com
The Blink(1) LED can be controlled via IFTTT, but direct API would simplify setup.

**Comment by isaacrlevin** [comment]
Did you try using  the Custom API? I do no have resources to build a custom solution for this light.

**Comment by jescodev** [comment]
Ok, no problem- I will look into that, the project is an interesting design and will be something I can dig into.
BTW- is there any way to set something in the Presence Light (code?) to monitor the status of other contact than myself - which I can see status of in Teams, but really I wanted a Boss/Supervisor Alert was really my goal with this (jokingly referred to as DEFCON Status among peers).
https://en.wikipedia.org/wiki/DEFCON

Thanks for the great work, I did find that as-is I can see a better status of what I am posting, than what is shown in teams, I'll look into the extended API for the USB-LED and let you know if I get it to work.
-James




 

    On Monday, March 20, 2023 at 01:39:08 PM PDT, Isaac Levin ***@***.***> wrote:  
 
 


Did you try using the Custom API? I do no have resources to build a custom solution for this light.

**Comment by jescodev** [comment]
Thx for quick reply- I will look at the "graphing API"- seems like that is where many get the status from.


 

    On Tuesday, March 21, 2023 at 09:06:53 AM PDT, Isaac Levin ***@***.***> wrote:  
 
 


It would be a considerable effort to add something like that. Not sure if I would need to add additional scopes to PresenceLight in graph.
