### ISSUE TITLE
windows defender prevents start of app

### ISSUE THREAD

**Issue by JoernBerkefeld** [isaacrlevin/presencelight#818]
hi Isaac, I was trying to install your app via MS store but that is blocked on my company laptop. When I then tried to simply download it from your git repo and start it, Windows Defender stepped in and blocked it. Any ideas?

Thank you :)

**Comment by isaacrlevin** [comment]
Have you tried to install from the MS Store?
https://www.bing.com/ck/a?!&&p=8c7acfc115653f3cJmltdHM9MTY3OTI3MDQwMCZpZ3VpZD0wNTBkNThmMy1mNzE4LTZhYTktMGU1Yi00YTkzZjZiMDZiNTUmaW5zaWQ9NTIxNQ&ptn=3&hsh=3&fclid=050d58f3-f718-6aa9-0e5b-4a93f6b06b55&psq=presencelight&u=a1aHR0cHM6Ly9hcHBzLm1pY3Jvc29mdC5jb20vc3RvcmUvZGV0YWlsLzlORkZLRDhHWk5MNz9obD1lbi11cyZnbD1VUw&ntb=1

**Comment by isaacrlevin** [comment]
If you cannot install from the store OR install locally, I don't know how to help you. The app has been certified by Microsoft but obviously your company has some group policy here. I would talk to your IT department to identify what with PL is triggering Defender to block it.

**Comment by JoernBerkefeld** [comment]
ok, thank you @isaacrlevin

**Comment by isaacrlevin** [comment]
Closing, let me know if you get more info
