### ISSUE TITLE
"Unhandled error" using Microsoft Store or Nightly version

### ISSUE THREAD

**Issue by jorgebtx** [isaacrlevin/presencelight#820]
**Describe the bug**
I can install and launch the app, authenticate and access presence in Graph, but as soon as I click to search for a Wiz light, I get the unhandled error and the app freezes.

**To Reproduce**
1. Go to 'Wiz lights section'
2. Click on 'Find Wiz Light'
3. See error

**Expected behavior**
I expect it to find a light and allow me to connect

**Screenshots**
See attached
[log-2023052511.zip](https://github.com/isaacrlevin/presencelight/files/11567245/log-2023052511.zip)

![UnhandledError](https://github.com/isaacrlevin/presencelight/assets/134634229/e6535c15-95b3-463f-bd5b-aabb6ac713fa)

## Further details
- OS: Windows 11 22H2
- PresenceLight App - Type Desktop
- PresenceLight Build - Nightly or Store
- PresenceLight Version - 5.6.1
- Did you clear settings.json? Yes
- ASP.NET Core version - 6.0.16

**Comment by isaacrlevin** [comment]
Looks like this is some issue connecting to Wiz lights. I opened an issue on that repo. In the meantime, Wiz will not work sadly

**Comment by jorgebtx** [comment]
I appreciate the quick investigation. In the meantime, I'll give it a whirl with a Yeelight.
