### ISSUE TITLE
Add option for presence sync based on Zoom

### ISSUE THREAD

**Issue by gregsedwards** [isaacrlevin/presencelight#828]
I've just discovered your PresenceLight app, and I love it. My company uses Zoom instead of Teams (😪) as well as a third-party platform called MangoApps, and I'd love the option to coordinate my LIFX presence lights with these as well. I wonder whether you might consider expanding the app to work with additional presence services or just your overall Windows presence (focus mode). Thanks for considering!

**Comment by isaacrlevin** [comment]
I have talked to the folks at Zoom and there is no interest on their part to have an API that can work in the same way Microsoft Graph/Teams does. Sadly I can't do more in this regard.
