### ISSUE TITLE
LFX not syncing post update

### ISSUE THREAD

**Issue by sborg-ms** [isaacrlevin/presencelight#836]
LFX lights no longer syncing with teams.

Seeing errors in live log
<html>
<body>

8/01/2024 4:50:51 PM +11:00 | Error | Error occurred Setting Color - MainWindow.xaml:SetColor Line: 268
-- | -- | --
Error | Error Occurred Setting Color - LifxService:SetColor Line: 175
Information | PresenceLight Running in Teams Mode - MainWindow.xaml:InteractWithLights Line: 574

</body>
</html> 
 
## Further details
- OS:  WIn11 23H2
- PresenceLight App Type (**Desktop**)
- PresenceLight Build (**Nightly** )
- PresenceLight Version (**5.6.120**)

**Comment by isaacrlevin** [comment]
Did you try to uninstall/reinstall?

**Comment by sborg-ms** [comment]
So just installed your new nightly build - Application Version 5.7.1

Still seeing similar/same errors
<img width="687" alt="image" src="https://github.com/isaacrlevin/presencelight/assets/67351620/e0e88ec3-76f9-48e1-aedd-d44cd734f7fb">

**Comment by sborg-ms** [comment]
`{"Timestamp":"2024-01-18T14:32:53.8840578+11:00","Level":"Information","MessageTemplate":"PresenceLight Running in Teams Mode - MainWindow.xaml:InteractWithLights Line: 575","Properties":{"SourceContext":"PresenceLight.MainWindow","LineNumber":575,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"InteractWithLights","Application":"PresenceLight"}}
{"Timestamp":"2024-01-18T14:32:54.2811459+11:00","Level":"Error","MessageTemplate":"Error Occurred Setting Color - LifxService:SetColor Line: 175","Exception":"System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at PresenceLight.Core.LIFXService.SetColor(String availability, String activity, String lightId, String apiKey) in D:\\a\\presencelight\\presencelight\\src\\PresenceLight.Core\\Lights\\LifxServices\\LifxService.cs:line 116","Properties":{"SourceContext":"PresenceLight.Core.LIFXService","LineNumber":175,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\PresenceLight.Core\\Lights\\LifxServices\\LifxService.cs","MemberName":"SetColor","Application":"PresenceLight"}}
{"Timestamp":"2024-01-18T14:32:54.2819688+11:00","Level":"Error","MessageTemplate":"Error occurred Setting Color - MainWindow.xaml:SetColor Line: 269","Exception":"System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at PresenceLight.Core.LIFXService.SetColor(String availability, String activity, String lightId, String apiKey) in D:\\a\\presencelight\\presencelight\\src\\PresenceLight.Core\\Lights\\LifxServices\\LifxService.cs:line 116\r\n   at PresenceLight.Core.LifxServices.SetColorHandler.Handle(SetColorCommand command, CancellationToken cancellationToken) in D:\\a\\presencelight\\presencelight\\src\\PresenceLight.Core\\Lights\\LifxServices\\SetColor\\SetColorHandler.cs:line 24\r\n   at PresenceLight.MainWindow.SetColor(String color, String activity) in D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs:line 241","Properties":{"SourceContext":"PresenceLight.MainWindow","LineNumber":269,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight\\MainWindow.xaml.cs","MemberName":"SetColor","Application":"PresenceLight"}}`

**Comment by isaacrlevin** [comment]
I just downloaded the latest nightly and was able to setup connection to a LIFX light without issue. Few questions for you

Are you using custom colors?
Are you using Activity Statuses?

Might be helpful to see your settings file (you can get it in the About page)

**Comment by sborg-ms** [comment]
No custom colours -- i do see the "Use Activity Statuses" is checked in UX.   This config has not changed for a very long while and all this only started after the 30Dec update!
 
settings file:
`{
  "SendDiagnosticData": true,
  "StartMinimized": true,
  "IconType": "White",
  "LightSettings": {
    "HoursPassedStatus": "Off",
    "SyncLights": true,
    "WorkingDays": "Monday|Tuesday|Wednesday|Thursday|Friday",
    "UseWorkingHours": true,
    "UseAmPm": false,
    "WorkingHoursStartTime": "08:00:00",
    "WorkingHoursEndTime": "17:30:00",
    "PollingInterval": 5.0,
    "UseDefaultBrightness": true,
    "DefaultBrightness": 100,
    "CustomApi": {
      "CustomApiTimeout": 100.0,
      "IgnoreCertificateErrors": false,
      "UseBasicAuth": false,
      "BasicAuthUserName": "",
      "BasicAuthUserPassword": "",
      "CustomApiAvailable": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiBusy": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiBeRightBack": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiAway": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiDoNotDisturb": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiAvailableIdle": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiOffline": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiOff": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityAvailable": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityInACall": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityInAConferenceCall": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityInAMeeting": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityPresenting": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityBusy": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityAway": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityBeRightBack": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityDoNotDisturb": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityIdle": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityOffline": {
        "Method": "",
        "Uri": ""
      },
      "CustomApiActivityOff": {
        "Method": "",
        "Uri": ""
      },
      "IsEnabled": false,
      "SelectedItemId": "",
      "Brightness": 100,
      "Statuses": null,
      "UseActivityStatus": false
    },
    "LocalSerialHost": null,
    "LIFX": {
      "LIFXApiKey": "***",
      "LIFXClientId": "***",
      "LIFXClientSecret": "***",
      "IsEnabled": true,
      "SelectedItemId": "id:d073d540948e",
      "Brightness": 100,
      "Statuses": {
        "AvailabilityAvailableStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityAvailableIdleStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityAwayStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityBeRightBackStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityBusyStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityBusyIdleStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityDoNotDisturbStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityOfflineStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityPresenceUnknownStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityOffStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityAvailableStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityAwayStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityBeRightBackStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityBusyStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityDoNotDisturbStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityInACallStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityInAConferenceCallStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityInactiveStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityInAMeetingStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityOfflineStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityOffStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityOffWorkStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityOutOfOfficeStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityPresenceUnknownStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityPresentingStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityUrgentInterruptionsOnlyStatus": {
          "Disabled": false,
          "Color": null
        }
      },
      "UseActivityStatus": true
    },
    "Hue": {
      "RemoteHueClientId": "gGfuKceD3oJG9KlJJB8bAetwmkRXG0cM",
      "RemoteHueClientAppName": "presencelight",
      "RemoteHueClientSecret": "YlN05wbDztd4h7UC",
      "HueApiKey": "",
      "HueIpAddress": "",
      "UseRemoteApi": false,
      "RemoteBridgeId": "",
      "IsEnabled": false,
      "SelectedItemId": "",
      "Brightness": 100,
      "Statuses": {
        "AvailabilityAvailableStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityAvailableIdleStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityAwayStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityBeRightBackStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityBusyStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityBusyIdleStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityDoNotDisturbStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityOfflineStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityPresenceUnknownStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityOffStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityAvailableStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityAwayStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityBeRightBackStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityBusyStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityDoNotDisturbStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityInACallStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityInAConferenceCallStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityInactiveStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityInAMeetingStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityOfflineStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityOffStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityOffWorkStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityOutOfOfficeStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityPresenceUnknownStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityPresentingStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityUrgentInterruptionsOnlyStatus": {
          "Disabled": false,
          "Color": null
        }
      },
      "UseActivityStatus": false
    },
    "Yeelight": {
      "IsEnabled": false,
      "SelectedItemId": "",
      "Brightness": 100,
      "Statuses": {
        "AvailabilityAvailableStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityAvailableIdleStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityAwayStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityBeRightBackStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityBusyStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityBusyIdleStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityDoNotDisturbStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityOfflineStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityPresenceUnknownStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityOffStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityAvailableStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityAwayStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityBeRightBackStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityBusyStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityDoNotDisturbStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityInACallStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityInAConferenceCallStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityInactiveStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityInAMeetingStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityOfflineStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityOffStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityOffWorkStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityOutOfOfficeStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityPresenceUnknownStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityPresentingStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityUrgentInterruptionsOnlyStatus": {
          "Disabled": false,
          "Color": null
        }
      },
      "UseActivityStatus": false
    },
    "Wiz": {
      "IsEnabled": false,
      "SelectedItemId": "",
      "Brightness": 100,
      "Statuses": {
        "AvailabilityAvailableStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityAvailableIdleStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityAwayStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityBeRightBackStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityBusyStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityBusyIdleStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityDoNotDisturbStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityOfflineStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityPresenceUnknownStatus": {
          "Disabled": false,
          "Color": null
        },
        "AvailabilityOffStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityAvailableStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityAwayStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityBeRightBackStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityBusyStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityDoNotDisturbStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityInACallStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityInAConferenceCallStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityInactiveStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityInAMeetingStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityOfflineStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityOffStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityOffWorkStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityOutOfOfficeStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityPresenceUnknownStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityPresentingStatus": {
          "Disabled": false,
          "Color": null
        },
        "ActivityUrgentInterruptionsOnlyStatus": {
          "Disabled": false,
          "Color": null
        }
      },
      "UseActivityStatus": false
    }
  },
  "AppType": "Desktop",
  "AADSettings": null
}`

**Comment by sborg-ms** [comment]
ok - so was experimenting with your qn around statuses - seems all the status colours were changed at some point to all be set to
<img width="181" alt="image" src="https://github.com/isaacrlevin/presencelight/assets/67351620/cd3f5d87-6d8d-4fea-a15d-c8dc32c211ef">
I manually set one (available color and it set the lifx) - will have to do all the statuses colours now i suspect?!

**Comment by sborg-ms** [comment]
believe i set all the colours explicitly now for the LIFX - its working and removed one of the errors appearing but still see this one regularly..   ideas?

<img width="672" alt="image" src="https://github.com/isaacrlevin/presencelight/assets/67351620/eef76b4e-254b-490e-a4f3-51c593d1e75c">

**Comment by isaacrlevin** [comment]
can I see your working settings file?

**Comment by sborg-ms** [comment]
additonallly -- 
If i try to SET COLOR here
<img width="380" alt="image" src="https://github.com/isaacrlevin/presencelight/assets/67351620/8b0e004a-e003-4b34-be21-6e23bb5be01c">

It sets the lifx colour but then notes the failure and the UX is stuck and have to exit app...
<img width="740" alt="image" src="https://github.com/isaacrlevin/presencelight/assets/67351620/6669f468-3fe1-4df4-add0-ace83d1bc2b0">

**Comment by isaacrlevin** [comment]
Yea I am not sure what is going on with your setup, but I downloaded the settings file that comes with the Nightly version and the nulls you are seeing your settings are not here. I would recommend uninstalling both nightly and the version from the store. After that restart your machine and install nightly.

**Comment by sborg-ms** [comment]
MMm - ok... only have (ever) had nightly installed.   
Will work thru the uninstall & install (setup for lifx again) and see how it goes then!

**Comment by sborg-ms** [comment]
OK - complete uninstall/reboot/reinstall.  Its better and mostly working.

I could however not get it to save the working hours via UX - had to manually add to setting.json
    "UseAmPm": false,
    "WorkingHoursStartTime": "08:00:00",
    "WorkingHoursEndTime": "17:30:00",
    
    Then after its syncing with teams and updating lifx as expected.
    
    Thanks

**Comment by isaacrlevin** [comment]
So odd, I was able to update the working hours to your settings via the UI in nightly just now.... Not sure what is going on with you r setup.

**Comment by isaacrlevin** [comment]
@sborg-ms are you still having this issue?

**Comment by sborg-ms** [comment]
thanks - its been stable even with the last couple of nightly updates so i think we are good. thanks.
