### ISSUE TITLE
Using a Philips Wiz Connected Bulb

### ISSUE THREAD

**Issue by andyman60** [isaacrlevin/presencelight#846]
### Discussed in https://github.com/isaacrlevin/presencelight/discussions/845

<div type='discussions-op-text'>

<sup>Originally posted by **andyman60** January 11, 2024</sup>
Just got a Wiz Connected Philips bulb, and I'm trying to get my Teams status to match... I've got the app installed from the Microsoft store, but it doesn't look like there's any option under the "Configure Lights" for the Wiz type of Philips Bulbs. Maybe I'm missing something? 
![PL](https://github.com/isaacrlevin/presencelight/assets/13338845/6e34753a-ae34-4daa-a2fb-29c62b0020ae)
</div>

**Comment by isaacrlevin** [comment]
There is an issue with dimming on the Wiz A20 bulb which is what I have, so I turned it off. I added it back to the Nightly version of you are interested.

**Comment by isaacrlevin** [comment]
Added back to release
