### ISSUE TITLE
Custom API - REST API Body Support

### ISSUE THREAD

**Issue by stefanstranger** [isaacrlevin/presencelight#848]
Thanks for creating presenselight. 

I want to use the Custom API functionality to send Teams presence information to my [Ulanzi](https://www.ulanzi.com/products/ulanzi-pixel-smart-clock-2882?ref=28e02dxl) Pixel Clock flashed with [Awtrix](https://github.com/Blueforcer/awtrix-light).

The REST API of the Awtrix expects a REST API body to be send for notifications. 

Is there an option to include a REST API body message for the Custom API REST methods in PresenceLight?

Regards,
Stefan

**Comment by isaacrlevin** [comment]
Currently the CustomApi mechanism only has support for querystring parameters. I am more than happy to review a PR to add a REST body to that functionality.

**Comment by stefanstranger** [comment]
Hi Isaac,

I'm not a developer but when I've time I can try to have a go. I already forked the repo. So that part is already done ;-)

/Stefan

**Comment by stefanstranger** [comment]
Got it working! Will do some more tests before submitting the PR.

**Comment by isaacrlevin** [comment]
Functionality added in #850. Will close when Release published

**Comment by isaacrlevin** [comment]
Closing
