### ISSUE TITLE
Feature request: integrate Home Assistant // mqtt

### ISSUE THREAD

**Issue by peterossege** [isaacrlevin/presencelight#871]
I want to connect your App to Home Assistant. I'm a beginner and want to find an easy way ;-)

Alternatively: can you describe how to use custom API with HA? 

Proposal: MQTT post

**Comment by pauliusbau** [comment]
Haven't tested it yet, but it seems that there is a way to integrate with Home Assistant:
https://github.com/isaacrlevin/presencelight/blob/main/docs/configure-custom-api.md

**Comment by isaacrlevin** [comment]
@peterossege have you tried the doc that @pauliusbau mentioned? If so, what issues are you having?

**Comment by peterossege** [comment]
Works perfect, thank you!--- Keep in touch, klick here!Peter Ossege * Rossweg 55 * 48432 RheineTel.: +49 5975 93885 * mobil: +49 151 68948914Am 19.02.2024 um 09:51 schrieb Paulius Bautrėnas ***@***.***>:﻿
Haven't tested it yet, but it seems that there is a way to integrate with Home Assistant:
https://github.com/isaacrlevin/presencelight/blob/main/docs/configure-custom-api.md
