### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by virginiabradley** [isaacrlevin/presencelight#885]
When I open the PresenceLight app (**Desktop Version**), it shows a blank screen with an error message "An unhandled error has occured" at the bottom. There is a reload button option, which when clicked does nothing.

I've been using the Philips Hue integration. The light itself works with the Hue app, but PresenceLight seems to be unresponsive. I've restarted my computer, turned on and off the sync within the PresenceLight app, and nothing works.

![PresenceLight Error](https://github.com/isaacrlevin/presencelight/assets/163877825/d2bfe972-0e59-4c29-bad9-f57ae17917bc)

Unfortunately, I cannot access the "About" section of the app to give further build details.

**Comment by cobbtm2003** [comment]
I ran into this same thing today.  I went to remove the program and instead went to advanced options and chose to reset the application and repair it.  After that i started the app and it now works as designed.

**Comment by isaacrlevin** [comment]
If resetting the app (or uninstall/reinstall) does not resolve the issue, open a new one with adequate logs.
