### ISSUE TITLE
Approval request not being received by Teams Admin

### ISSUE THREAD

**Issue by syberz** [isaacrlevin/presencelight#886]
**Describe the bug**
When logging in with my Microsoft account I need to request approval for the app, however my Admin never receives said request.

**To Reproduce**
1. Open app
2. Browser tab (Chrome) opens automatically with a Microsoft login screen
3. Select my Microsoft account to log in
4. Get the approval screen
4.1 Instead of the app name it says "unverified" next to the icon
4.2 I enter a justification
4.3. Click send
5. See a Request Pending confirmation screen.
6. Clicking "Back to app" yields a blank page with the following messages: "Authentication failed. You can return to the application. Feel free to close this browser tab. Error details: error authentication_canceled error_description: User canceled authentication."
7. Admin doesn't receive any emails about my request
8. User app requests section in Teams is empty

**Expected behavior**
Admin receives a permission request, accepts it and then I can see my Teams status in Presencelight.

**Screenshots**

## Further details
- OS: Windows 11
- PresenceLight App Type (Desktop)
- PresenceLight Build (8.0.2+1381d5ebd2ab1f292848d5b19b80cf71ac332508)
- PresenceLight Version (5.8.4)
- Did you clear settings.json? (No, fresh install)
- ASP.NET Core version (I don't know)

**Comment by isaacrlevin** [comment]
This is all on the Entra side, no idea how I can even debug this. If your admin doesn't receive the request I would see if they can go into Entra and see any consent requests.
