### ISSUE TITLE
2.0.85.0 Install fails

### ISSUE THREAD

**Issue by sborg-ms** [isaacrlevin/PresenceLight#89]
Trying to upgrade or install the new nightly fails.

App installation failed with error message: Deployment Add operation with target volume C: on Package 37828IsaacLevin.197278F15330A.Nightly_2.0.85.0_neutral_~_jvewcxq8vj8qt from:  (PresenceLight.Package_2.0.85.0_x86.appxbundle)  failed with error 0x80190193. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x80190193)

After a reboot have uninstalled and tried fresh with the same above.

**Comment by isaacrlevin** [comment]
Weird, that error doesn't show up on that page. What build of Windows do you have? I was just able to install nightly on 19042

**Comment by sborg-ms** [comment]
same as previous nightly installs.  19041.329   - but this morning it installed :) and is now running.

**Comment by isaacrlevin** [comment]
Nice, closing issue
