### ISSUE TITLE
Error (again) using app with Hue Remote API

### ISSUE THREAD

**Issue by MarcusBluestein** [isaacrlevin/presencelight#896]
I had an issue with the app and remote API months ago and you helped me resolve it.  The problems return a few weeks ago and I have not been able to use the app since.  I confirmed that I am running the nightly build version (5.8.6) and reinstalled it to be sure.

In the app, I get this:
Error Occurred Connecting to Hue, please try again

In the logs I get this:

{"Timestamp":"2024-05-17T12:23:41.2766113-04:00","Level":"Information","MessageTemplate":"Get Hue Lights Initialized","Properties":{"SourceContext":"PresenceLight.Razor.Components.Pages.HueSetup","Application":"PresenceLight"}}
{"Timestamp":"2024-05-17T12:23:41.9179340-04:00","Level":"Error","MessageTemplate":"Error Getting Lights - RemoteHueService:GetLights Line: 287","Exception":"Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: U. Path '', line 0, position 0.\r\n   at Newtonsoft.Json.JsonTextReader.ParseValue()\r\n   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)\r\n   at Q42.HueApi.HueClient.DeserializeDefaultHueResult(String json)\r\n   at Q42.HueApi.HueClient.SearchNewLightsAsync(IEnumerable`1 deviceIds)\r\n   at PresenceLight.Core.RemoteHueService.GetLights() in D:\\a\\presencelight\\presencelight\\src\\PresenceLight.Core\\Lights\\RemoteHueServices\\RemoteHueService.cs:line 279","Properties":{"SourceContext":"PresenceLight.Core.RemoteHueService","LineNumber":287,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\PresenceLight.Core\\Lights\\RemoteHueServices\\RemoteHueService.cs","MemberName":"GetLights","Application":"PresenceLight"}}

Any ideas?

**Comment by isaacrlevin** [comment]
Just confirmed a fresh download of nightly (and release) works with Hue local and Hue remote. I would validate you can get lights using postman or some other REST tool

**Comment by MarcusBluestein** [comment]
Thanks.  I could connect to my Hue system locally and through the Hue website.

I fully deleted PresenceLight and reinstalled it.  Seems to work again.

Thanks

Marcus Bluestein | Kraft & Kennedy, Inc.
+1 (212) 692-5602 | ***@***.***

________________________________
