### ISSUE TITLE
Login and LIFX Personal Access Token do not persist on shutdown. 

### ISSUE THREAD

**Issue by BBQSean** [isaacrlevin/PresenceLight#9]
LIFX API key is visible when logging into https://cloud.lifx.com only once, it should persist in PresenceLight, otherwise first-run setup including request of a new token must be done every time it is run.

**Comment by isaacrlevin** [comment]
What version of the app do you have? I believe this was fixes a few versions ago

**Comment by BBQSean** [comment]
[cid:image001.png@01D61954.B9A6C530]

**Comment by BBQSean** [comment]
Attempted on 1.0.136.0 (Nightly) and still having the issue after reboot. Set Graph Presence and Configure LIFX are both set back to first-run experience.

**Comment by isaacrlevin** [comment]
Yep, I am aware of the issue and working on a fix

**Comment by isaacrlevin** [comment]
Issue is now fixed with latest nightly v1.0.140.0
