### ISSUE TITLE
Wiz Connection Issue

### ISSUE THREAD

**Issue by acjohnson615** [isaacrlevin/presencelight#916]
**Describe the bug**

When I go to Connect to Wiz it tries to load and then the program goes unresponcive.

**To Reproduce**

1 Go to configure lights, Wiz
2 Secelct Connect to Wiz
3 Click Find Wiz Lights
4 Program goes into Not Responging

**Expected behavior**

Options to find and setup my Wiz Light

**Screenshots**

![image](https://github.com/isaacrlevin/presencelight/assets/173696096/d1e47076-f101-4eb2-9075-8eeacbfd82a3)

## Further details
Win 11
- PresenceLight App Type (Desktop, Blazor)
Desktop Win Store
- PresenceLight Build (Nightly, Store, etc)
- PresenceLight Version (The # in About)
5.8.7
- Did you clear settings.json? (C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json
Yes
- ASP.NET Core version

**Comment by Tails5280** [comment]
I'm also having the same issue. I had it working before but went back to make some changes and now keep getting the same. I tried v5.8.6 as well and that did the same thing.

**Comment by DJCisMe** [comment]
Hello, I am having an issue Configuring Wiz Light. As soon as I click Find Wiz Lights I get a red bar at the bottom that says an "An unhandled error has occurred. Reload.
![image](https://github.com/user-attachments/assets/3ad507f0-d60e-4297-8606-0194fda46730)
What is appropriate way to clear the settings.json file ? Maybe I am doing it wrong.

**Comment by isaacrlevin** [comment]
Did you try uninstalling and reinstalling the app?

**Comment by isaacrlevin** [comment]
Confirmed that a fresh install of PresenceLight is able to connect to WIz without issue. I would try uninstalling  the app, ensure your settings file is cleaned (aka no lights set in it) and reinstall the app.

**Comment by mrBobMusic** [comment]
I have the same issue, so I uninstalled the app, rebooted and reinstalled. But the issue persist. When I select Wiz light, the app eventually locks up.
Here's a portion of my log. Is the log referencing "D" drive? If it is, I don't have a "D" drive, only "C". 
"Properties":{"SourceContext":"PresenceLight.MainWindow","LineNumber":180,"FilePath":"D:\\a\\presencelight\\presencelight\\src\\DesktopClient\\PresenceLight
