### ISSUE TITLE
Feature: Ability to set preference for light action after work hours

### ISSUE THREAD

**Issue by sborg-ms** [isaacrlevin/PresenceLight#92]
ITs great to have the working hours - need a setting to allow a preferred behaviour on what happens to the light after it crosses the workday boundary - idea would be to allow
1. Turn off light
2. Leave last status active

**Comment by isaacrlevin** [comment]
Added to nightly version 3.0.20

**Comment by isaacrlevin** [comment]
@sborg-ms can you test?

**Comment by sborg-ms** [comment]
I have been using/testing action1 - It turns OFF as per my setting successfully every day!

**Comment by isaacrlevin** [comment]
Great, cool to close?

**Comment by sborg-ms** [comment]
Yep - tested all three settings and working as expected.
