### ISSUE TITLE
WIZ Brightness Level

### ISSUE THREAD

**Issue by sdcox89** [isaacrlevin/presencelight#929]
**Describe the bug**
When using WIZ LED Strip synced with Teams the brightness level is very low when set to 100.

**Expected behavior**

Expected the brightness to be the same as when using the WIZ light via the phone app.

## Further details
- OS: Windows 11
- PresenceLight App Type Desktop
- PresenceLight Build Store
- PresenceLight Version 5.8.7
- Did you clear settings.json?(C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json No
- ASP.NET Core version

**Comment by isaacrlevin** [comment]
This is a known issue sadly.
https://github.com/isaacrlevin/presencelight/issues/488
