### ISSUE TITLE
Feature request: Notification of Teams unread chat.

### ISSUE THREAD

**Issue by noyard** [isaacrlevin/presencelight#930]
**Is your feature request related to a problem? Please describe.**
my problem is I have a few Azure remote desktops with different Teams IDs associated with them.  I would like to know if I have unread chats and be notified by the presencelight.

**Describe the solution you'd like**
If unread teams messages, either blink or fade in/out the light or offer a different color. 

**Describe alternatives you've considered**
Since these are completely separate teams instances, the only solution I have found is manually check.

**Additional context**

**Comment by fisch192** [comment]
This could be usefull also for incoming calls

**Comment by isaacrlevin** [comment]
This is outside the scope of PresenceLight as it was created to broadcast Teams presence, not report on Teams usage. If this is something you would like, I encourage you to open a PR with this functionality
