### ISSUE TITLE
"An unhandled error has occurred. Reload"

### ISSUE THREAD

**Issue by DJCisMe** [isaacrlevin/presencelight#933]
Hello, I am having an issue Configuring Wiz Light. 

**To Reproduce**
As soon as I click Find Wiz Lights I get a red bar at the bottom that says an "An unhandled error has occurred. Reload.

**Expected behavior**
Discover my light

**Screenshots**
![image](https://github.com/user-attachments/assets/d19de150-b14a-4d6c-842b-4fc93927354f)

## Further details
Application Version
5.8.7
Install Location
C:\Program Files\WindowsApps\37828IsaacLevin.197278F15330A.Nightly_5.8.7.0_x64__jvewcxq8vj8qt\PresenceLight\
Install Date
2024-10-14 8:57 AM
Runtime Version
8.0.5+087e15321bb712ef6fe8b0ba6f8bd12facf92629

- Did you clear settings.json? 
- I believe so. I am able to reset it in WIndows Apps. I have also tried to delete the file. I have uninstalled & re-installed.
-
- (C:\Users\username\AppData\Local\Packages\37828IsaacLevin.197278F15330A.SomeValue\LocalState\settings.json

I do see this in the log -- SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 2 column 1 of the JSON data
-

**Comment by isaacrlevin** [comment]
Did you try uninstalling the reinstalling the app?

**Comment by isaacrlevin** [comment]
Just confirmed a fresh version of the app has working Wiz support. Closing
