### ISSUE TITLE
Start of executable program files and scripts

### ISSUE THREAD

**Issue by simon-t1** [isaacrlevin/presencelight#936]
Hello Isaac,

thank you for your excellent software presencelight.

Is it possible for you to add the start of executable programs and scripts?

I would like to be reminded of various manual tasks at the start and end of a Teams meeting.
For this I would like to have a small message displayed using a script (VBS or PS1).
I would also like to have all Windows minimized when a Teams meeting/phone call starts.
This could also be done very easily with a script.

It would be ideal if a configuration page like the one in "Custom API" was available,
where you can store the path to executable EXE/script file and the parameters for each status.

Then you would have almost unlimited actions and execution options.

As a workaround, I thought about installing a web service that calls the scripts for me and whose URLs I then store in "Custom API".

I am not a developer and do not know exactly what information would be helpful.
If you are still missing information, please feel free to contact me.

Many thanks and kind regards
Simon

**Comment by isaacrlevin** [comment]
This is outside the scope of PresenceLight today. I recommend you fork the repo and add the functionality you are looking for. Feel free to email me if you run into issues with Entra configuration
