### ISSUE TITLE
Bug? PresenceLight changes light color if started outside of sync hours

### ISSUE THREAD

**Issue by bjeans** [isaacrlevin/PresenceLight#95]
It seems that PresenceLight doesn't respect the working hours setting on initial startup.  If I reboot my machine (or restart the app) outside of my configured working hours my lights are changed to match my teams presence, however, any subsequent change to teams presence doesn't change the lights.

It's like the app doesn't check the working hours setting on initial startup, only on subsequent poll cycles.

**Comment by isaacrlevin** [comment]
This is fixed in latest Nightly
