### ISSUE TITLE
Add additional Light - Windows Dynamic Lighting

### ISSUE THREAD

**Issue by jadler-aus** [isaacrlevin/presencelight#955]
I have been thinking about a status light for Teams and how best to create / implement from a simple hardware device. Unfortunately there seems to be no easy way to maintain interoperability. 

With Windows11 and now Windows 10 supporting Dynamic Lighting as a HID standard and more devices being supported all the time, this would be a great way of providing a universality of control. 

**Describe the solution you'd like**
I would love to see PresenceLight support Windows Dynamic Lighting as a light sync option. Allowing it to be a foreground and background app (perhaps even changing status whether MS Teams is in the foreground or background).

This would mean, PresenceLight could set the light colour of a HID.LampArray device / multiple devices based on teams presence. This is a totally device agnostic solution while still maintaining standards and ease of use.

Cheap devices could be used to create a StatusLight or it can tie into existing eco-systems that support the HID-LampArray class - eg many mice and keyboards - laptop accent led's etc.

https://www.wisdpi.com/products/windows-dynamic-lighting-controller-support-dynamic-lighting-on-windows-11

Info I have found that might be helpful:

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/devices-sensors/lighting-dynamic-lamparray.md
https://learn.microsoft.com/en-us/uwp/api/windows.devices.lights?view=winrt-22621
https://learn.microsoft.com/en-us/windows/uwp/devices-sensors/lighting-dynamic-lamparray
https://github.com/[microsoft/Dynamic-Lighting-AutoRGB](https://github.com/microsoft/Dynamic-Lighting-AutoRGB)

**Comment by isaacrlevin** [comment]
I do not own this physical device so would not be able to test it. I welcome a PR if you want this functionality
