### ISSUE TITLE
PL on MS Store not updating

### ISSUE THREAD

**Issue by Shrekmachine** [isaacrlevin/PresenceLight#96]
Still showing as 2.0.51.0
![image](https://user-images.githubusercontent.com/8019511/87412360-3cf4dc80-c5c9-11ea-8f8c-8fa14d8b9a15.png)

**Comment by isaacrlevin** [comment]
I haven't pushed to the store in a bit because I wanted a stable nightly. Will push today

**Comment by Shrekmachine** [comment]
Ah, ok. little confusing as the version is already marked as 2.0.69.0
![image](https://user-images.githubusercontent.com/8019511/87437445-a0453580-c5ee-11ea-981e-223a7eb00e2a.png)

**Comment by isaacrlevin** [comment]
Yea @github caches the image.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
