### ISSUE TITLE
Light shows purple instead of read for "Focusing" status

### ISSUE THREAD

**Issue by therealjohn** [isaacrlevin/PresenceLight#97]
I have time blocked on my calendar as "Focus" time, configured using Dynamics. In Teams, the status shows as "Focusing" and it's similar to Do not Disturb. The color is red in Teams, by the app shows it as Purple. I'd expect it to be red.

**Comment by isaacrlevin** [comment]
I chose purple to differentiate DnD vs Busy, so this is by design.
